// <auto-generated>
// Code generated by csilgen; DO NOT EDIT.
// </auto-generated>
#nullable enable

namespace Longhouse.Client;

/// <summary>Server handler interface for the AuthService service.</summary>
public interface IAuthService
{
    LoginResponse Login(LoginRequest loginRequest);
    LoginResponse Complete(CompleteRequest completeRequest);
    LoginResponse Refresh(EmptyRequest emptyRequest);
    EmptyResponse Logout(EmptyRequest emptyRequest);
    MeResponse Me(EmptyRequest emptyRequest);
}

/// <summary>Server handler interface for the DevAuthService service.</summary>
public interface IDevAuthService
{
    DevUsersResponse ListDevUsers(EmptyRequest emptyRequest);
    LoginResponse DevLogin(DevLoginRequest devLoginRequest);
}

/// <summary>Server handler interface for the HouseService service.</summary>
public interface IHouseService
{
    House CreateHouse(House house);
    House GetHouse(HouseID houseID);
    House UpdateHouse(House house);
    EmptyResponse DeleteHouse(HouseID houseID);
    System.Collections.Generic.List<House> ListHouses(HouseListRequest houseListRequest);
}

/// <summary>Server handler interface for the MemberService service.</summary>
public interface IMemberService
{
    Member CreateMember(Member member);
    Member GetMember(MemberID memberID);
    Member GetMemberByIdentity(Member member);
    Member UpdateMember(Member member);
    EmptyResponse DeactivateMember(MemberID memberID);
    EmptyResponse ReactivateMember(MemberID memberID);
    System.Collections.Generic.List<Member> ListMembers(HouseScopedListRequest houseScopedListRequest);
}

/// <summary>Server handler interface for the TrustedDomainService service.</summary>
public interface ITrustedDomainService
{
    TrustedDomain AddTrustedDomain(TrustedDomain trustedDomain);
    EmptyResponse RemoveTrustedDomain(TrustedDomainID trustedDomainID);
    System.Collections.Generic.List<TrustedDomain> ListTrustedDomains(HouseID houseID);
    BoolResponse IsDomainTrusted(TrustedDomain trustedDomain);
}

/// <summary>Server handler interface for the RoleService service.</summary>
public interface IRoleService
{
    Role CreateRole(Role role);
    Role UpdateRole(Role role);
    EmptyResponse DeleteRole(RoleID roleID);
    System.Collections.Generic.List<Role> ListRoles(HouseScopedListRequest houseScopedListRequest);
    EmptyResponse GrantRole(MemberRoleRef memberRoleRef);
    EmptyResponse RevokeRole(MemberRoleRef memberRoleRef);
    System.Collections.Generic.List<Role> ListMemberRoles(MemberScopedListRequest memberScopedListRequest);
}

/// <summary>Server handler interface for the SkillService service.</summary>
public interface ISkillService
{
    Skill CreateSkill(Skill skill);
    Skill UpdateSkill(Skill skill);
    EmptyResponse DeleteSkill(SkillID skillID);
    System.Collections.Generic.List<Skill> ListSkills(HouseScopedListRequest houseScopedListRequest);
    EmptyResponse AddMemberSkill(MemberSkillRef memberSkillRef);
    EmptyResponse RemoveMemberSkill(MemberSkillRef memberSkillRef);
    System.Collections.Generic.List<Skill> ListMemberSkills(MemberScopedListRequest memberScopedListRequest);
    EmptyResponse AddGroupSkill(GroupSkillRef groupSkillRef);
    EmptyResponse RemoveGroupSkill(GroupSkillRef groupSkillRef);
    System.Collections.Generic.List<Skill> ListGroupSkills(GroupID groupID);
}

/// <summary>Server handler interface for the GroupService service.</summary>
public interface IGroupService
{
    Group CreateGroup(Group group);
    Group UpdateGroup(Group group);
    EmptyResponse DeleteGroup(GroupID groupID);
    System.Collections.Generic.List<Group> ListGroups(HouseScopedListRequest houseScopedListRequest);
    EmptyResponse AddGroupMember(GroupMemberRef groupMemberRef);
    EmptyResponse RemoveGroupMember(GroupMemberRef groupMemberRef);
    System.Collections.Generic.List<Member> ListGroupMembers(MemberScopedListRequest memberScopedListRequest);
}

/// <summary>Server handler interface for the ProjectService service.</summary>
public interface IProjectService
{
    Project CreateProject(Project project);
    Project GetProject(ProjectID projectID);
    Project UpdateProject(Project project);
    EmptyResponse DeleteProject(ProjectID projectID);
    ProjectList ListProjects(HouseScopedListRequest houseScopedListRequest);
    TaskList ListProjectTasks(ProjectScopedListRequest projectScopedListRequest);
    EmptyResponse AddProjectTask(ProjectTaskOrderRequest projectTaskOrderRequest);
    EmptyResponse RemoveProjectTask(ProjectTaskRef projectTaskRef);
    EmptyResponse SetProjectTaskPosition(ProjectTaskOrderRequest projectTaskOrderRequest);
    System.Collections.Generic.List<Member> ListProjectMembers(ProjectID projectID);
    EmptyResponse AddProjectMember(ProjectMemberRef projectMemberRef);
    EmptyResponse RemoveProjectMember(ProjectMemberRef projectMemberRef);
    System.Collections.Generic.List<Member> ListProjectOwners(ProjectID projectID);
    EmptyResponse AddProjectOwner(ProjectOwnerRef projectOwnerRef);
    EmptyResponse RemoveProjectOwner(ProjectOwnerRef projectOwnerRef);
    System.Collections.Generic.List<Milestone> ListMilestones(ProjectID projectID);
    Milestone CreateMilestone(Milestone milestone);
    Milestone UpdateMilestone(Milestone milestone);
    EmptyResponse DeleteMilestone(MilestoneID milestoneID);
    Project SetProjectVisibility(SetProjectVisibilityRequest setProjectVisibilityRequest);
    System.Collections.Generic.List<Grant> ListProjectGrants(ProjectID projectID);
    EmptyResponse PutProjectGrant(PutProjectGrantRequest putProjectGrantRequest);
    EmptyResponse DeleteProjectGrant(ProjectGrantRef projectGrantRef);
}

/// <summary>Server handler interface for the EventService service.</summary>
public interface IEventService
{
    Event CreateEvent(Event @event);
    Event GetEvent(EventID eventID);
    Event UpdateEvent(Event @event);
    EmptyResponse DeleteEvent(EventID eventID);
    EmptyResponse DeleteEventAndFuture(EventID eventID);
    System.Collections.Generic.List<Event> ListEvents(HouseScopedListRequest houseScopedListRequest);
}

/// <summary>Server handler interface for the TaskService service.</summary>
public interface ITaskService
{
    Task CreateTask(Task task);
    Task GetTask(TaskID taskID);
    Task UpdateTask(Task task);
    EmptyResponse DeleteTask(TaskID taskID);
    TaskList ListTasks(HouseScopedListRequest houseScopedListRequest);
    Task SetTaskVisibility(SetTaskVisibilityRequest setTaskVisibilityRequest);
    System.Collections.Generic.List<Grant> ListTaskGrants(TaskID taskID);
    EmptyResponse PutTaskGrant(PutTaskGrantRequest putTaskGrantRequest);
    EmptyResponse DeleteTaskGrant(TaskGrantRef taskGrantRef);
}

/// <summary>Server handler interface for the DependencyService service.</summary>
public interface IDependencyService
{
    EmptyResponse AddDependency(DependencyRef dependencyRef);
    EmptyResponse RemoveDependency(DependencyRef dependencyRef);
    DependencyGraph GetDependencies(DependencyTarget dependencyTarget);
}

/// <summary>Server handler interface for the CommentService service.</summary>
public interface ICommentService
{
    Comment CreateComment(Comment comment);
    Comment GetComment(CommentID commentID);
    Comment UpdateComment(Comment comment);
    EmptyResponse DeleteComment(CommentID commentID);
    System.Collections.Generic.List<Comment> ListComments(CommentListRequest commentListRequest);
}

/// <summary>Server handler interface for the NotificationService service.</summary>
public interface INotificationService
{
    System.Collections.Generic.List<Notification> ListNotifications(NotificationListRequest notificationListRequest);
    NotificationUnreadCount UnreadCount(HouseID houseID);
    Notification MarkRead(NotificationID notificationID);
    EmptyResponse MarkAllRead(HouseID houseID);
}

/// <summary>Server handler interface for the ShareService service.</summary>
public interface IShareService
{
    Share CreateShare(Share share);
    EmptyResponse DeleteShare(ShareID shareID);
    System.Collections.Generic.List<Share> ListSharesByResource(ResourceRef resourceRef);
    Share CheckAccess(ShareAccessRequest shareAccessRequest);
}

/// <summary>Server handler interface for the MemberAuditService service.</summary>
public interface IMemberAuditService
{
    System.Collections.Generic.List<MemberAudit> ListAuditsForMember(MemberScopedListRequest memberScopedListRequest);
}

/// <summary>Server handler interface for the SettingsService service.</summary>
public interface ISettingsService
{
    EffectiveSettings GetSettings(HouseID houseID);
    EffectiveSettings UpdateSettings(UpdateSettingsRequest updateSettingsRequest);
}

/// <summary>Server handler interface for the BugService service.</summary>
public interface IBugService
{
    Task ReportBug(BugReportRequest bugReportRequest);
}

/// <summary>Server handler interface for the AuditService service.</summary>
public interface IAuditService
{
    AuditPage QueryAudit(AuditQuery auditQuery);
}

/// <summary>Server handler interface for the TrashService service.</summary>
public interface ITrashService
{
    TrashPage ListTrash(HouseScopedListRequest houseScopedListRequest);
    EmptyResponse Restore(RestoreRequest restoreRequest);
    EmptyResponse Purge(PurgeRequest purgeRequest);
}

