name: Longhouse Release
description: "Build release images and deploy Longhouse when a release tag is pushed."

on:
  events:
    - tag_created
  branches:
    - "v*"

jobs:
  longhouse-api-build-and-deploy:
    job_file: api-build-and-deploy.yaml

  longhouse-web-build-and-deploy:
    job_file: web-build-and-deploy.yaml

  longhouse-deploy-tnl:
    job_file: deploy-tnl-example.yaml
    depends_on:
      - longhouse-api-build-and-deploy
      - longhouse-web-build-and-deploy

  longhouse-deploy-catalystsquad:
    job_file: deploy-catalystsquad.yaml
    depends_on:
      - longhouse-api-build-and-deploy
      - longhouse-web-build-and-deploy
