// Code generated by csilgen; DO NOT EDIT.

plugins {
    kotlin("jvm") version "2.0.21"
    `maven-publish`
}

group = "com.catalystcommunity.longhouse.client"
version = "0.14.2"

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(17)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
