/* Generated service handler structs and routers. */
/* Code generated by csilgen; DO NOT EDIT. */
#ifndef CSILGEN_SERVER_GEN_H
#define CSILGEN_SERVER_GEN_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include "types.gen.h"

/* CsilgenCodec is the consumer-supplied (de)serialization layer for channel
 * messages. The generator is codec-agnostic; the implementer wires this to
 * CBOR, JSON, or whatever its protocol expects. decode returns 0 on success. */
typedef struct CsilgenCodec {
    int (*decode)(void *self, const uint8_t *data, size_t len, void *out);
    int (*encode)(void *self, const void *value, uint8_t **out, size_t *out_len);
    void *self;
} CsilgenCodec;

/* AuthHandlers is the host's implementation of the AuthService service. */
typedef struct AuthHandlers {
    int (*login)(void *ctx, const LoginRequest *req, LoginResponse *resp);
    int (*complete)(void *ctx, const CompleteRequest *req, LoginResponse *resp);
    int (*refresh)(void *ctx, const EmptyRequest *req, LoginResponse *resp);
    int (*logout)(void *ctx, const EmptyRequest *req, EmptyResponse *resp);
    int (*me)(void *ctx, const EmptyRequest *req, MeResponse *resp);
} AuthHandlers;

/* DevAuthHandlers is the host's implementation of the DevAuthService service. */
typedef struct DevAuthHandlers {
    int (*list_dev_users)(void *ctx, const EmptyRequest *req, DevUsersResponse *resp);
    int (*dev_login)(void *ctx, const DevLoginRequest *req, LoginResponse *resp);
} DevAuthHandlers;

/* HouseHandlers is the host's implementation of the HouseService service. */
typedef struct HouseHandlers {
    int (*create_house)(void *ctx, const House *req, House *resp);
    int (*get_house)(void *ctx, const HouseID *req, House *resp);
    int (*update_house)(void *ctx, const House *req, House *resp);
    int (*delete_house)(void *ctx, const HouseID *req, EmptyResponse *resp);
    int (*list_houses)(void *ctx, const HouseListRequest *req, House * *resp);
} HouseHandlers;

/* MemberHandlers is the host's implementation of the MemberService service. */
typedef struct MemberHandlers {
    int (*create_member)(void *ctx, const Member *req, Member *resp);
    int (*get_member)(void *ctx, const MemberID *req, Member *resp);
    int (*get_member_by_identity)(void *ctx, const Member *req, Member *resp);
    int (*update_member)(void *ctx, const Member *req, Member *resp);
    int (*deactivate_member)(void *ctx, const MemberID *req, EmptyResponse *resp);
    int (*reactivate_member)(void *ctx, const MemberID *req, EmptyResponse *resp);
    int (*list_members)(void *ctx, const HouseScopedListRequest *req, Member * *resp);
} MemberHandlers;

/* TrustedDomainHandlers is the host's implementation of the TrustedDomainService service. */
typedef struct TrustedDomainHandlers {
    int (*add_trusted_domain)(void *ctx, const TrustedDomain *req, TrustedDomain *resp);
    int (*remove_trusted_domain)(void *ctx, const TrustedDomainID *req, EmptyResponse *resp);
    int (*list_trusted_domains)(void *ctx, const HouseID *req, TrustedDomain * *resp);
    int (*is_domain_trusted)(void *ctx, const TrustedDomain *req, BoolResponse *resp);
} TrustedDomainHandlers;

/* RoleHandlers is the host's implementation of the RoleService service. */
typedef struct RoleHandlers {
    int (*create_role)(void *ctx, const Role *req, Role *resp);
    int (*update_role)(void *ctx, const Role *req, Role *resp);
    int (*delete_role)(void *ctx, const RoleID *req, EmptyResponse *resp);
    int (*list_roles)(void *ctx, const HouseScopedListRequest *req, Role * *resp);
    int (*grant_role)(void *ctx, const MemberRoleRef *req, EmptyResponse *resp);
    int (*revoke_role)(void *ctx, const MemberRoleRef *req, EmptyResponse *resp);
    int (*list_member_roles)(void *ctx, const MemberScopedListRequest *req, Role * *resp);
} RoleHandlers;

/* SkillHandlers is the host's implementation of the SkillService service. */
typedef struct SkillHandlers {
    int (*create_skill)(void *ctx, const Skill *req, Skill *resp);
    int (*update_skill)(void *ctx, const Skill *req, Skill *resp);
    int (*delete_skill)(void *ctx, const SkillID *req, EmptyResponse *resp);
    int (*list_skills)(void *ctx, const HouseScopedListRequest *req, Skill * *resp);
    int (*add_member_skill)(void *ctx, const MemberSkillRef *req, EmptyResponse *resp);
    int (*remove_member_skill)(void *ctx, const MemberSkillRef *req, EmptyResponse *resp);
    int (*list_member_skills)(void *ctx, const MemberScopedListRequest *req, Skill * *resp);
    int (*add_group_skill)(void *ctx, const GroupSkillRef *req, EmptyResponse *resp);
    int (*remove_group_skill)(void *ctx, const GroupSkillRef *req, EmptyResponse *resp);
    int (*list_group_skills)(void *ctx, const GroupID *req, Skill * *resp);
} SkillHandlers;

/* GroupHandlers is the host's implementation of the GroupService service. */
typedef struct GroupHandlers {
    int (*create_group)(void *ctx, const Group *req, Group *resp);
    int (*update_group)(void *ctx, const Group *req, Group *resp);
    int (*delete_group)(void *ctx, const GroupID *req, EmptyResponse *resp);
    int (*list_groups)(void *ctx, const HouseScopedListRequest *req, Group * *resp);
    int (*add_group_member)(void *ctx, const GroupMemberRef *req, EmptyResponse *resp);
    int (*remove_group_member)(void *ctx, const GroupMemberRef *req, EmptyResponse *resp);
    int (*list_group_members)(void *ctx, const MemberScopedListRequest *req, Member * *resp);
} GroupHandlers;

/* ProjectHandlers is the host's implementation of the ProjectService service. */
typedef struct ProjectHandlers {
    int (*create_project)(void *ctx, const Project *req, Project *resp);
    int (*get_project)(void *ctx, const ProjectID *req, Project *resp);
    int (*update_project)(void *ctx, const Project *req, Project *resp);
    int (*delete_project)(void *ctx, const ProjectID *req, EmptyResponse *resp);
    int (*list_projects)(void *ctx, const HouseScopedListRequest *req, ProjectList *resp);
    int (*list_project_tasks)(void *ctx, const ProjectScopedListRequest *req, TaskList *resp);
    int (*add_project_task)(void *ctx, const ProjectTaskOrderRequest *req, EmptyResponse *resp);
    int (*remove_project_task)(void *ctx, const ProjectTaskRef *req, EmptyResponse *resp);
    int (*set_project_task_position)(void *ctx, const ProjectTaskOrderRequest *req, EmptyResponse *resp);
    int (*list_project_members)(void *ctx, const ProjectID *req, Member * *resp);
    int (*add_project_member)(void *ctx, const ProjectMemberRef *req, EmptyResponse *resp);
    int (*remove_project_member)(void *ctx, const ProjectMemberRef *req, EmptyResponse *resp);
    int (*list_project_owners)(void *ctx, const ProjectID *req, Member * *resp);
    int (*add_project_owner)(void *ctx, const ProjectOwnerRef *req, EmptyResponse *resp);
    int (*remove_project_owner)(void *ctx, const ProjectOwnerRef *req, EmptyResponse *resp);
    int (*list_milestones)(void *ctx, const ProjectID *req, Milestone * *resp);
    int (*create_milestone)(void *ctx, const Milestone *req, Milestone *resp);
    int (*update_milestone)(void *ctx, const Milestone *req, Milestone *resp);
    int (*delete_milestone)(void *ctx, const MilestoneID *req, EmptyResponse *resp);
    int (*set_project_visibility)(void *ctx, const SetProjectVisibilityRequest *req, Project *resp);
    int (*list_project_grants)(void *ctx, const ProjectID *req, Grant * *resp);
    int (*put_project_grant)(void *ctx, const PutProjectGrantRequest *req, EmptyResponse *resp);
    int (*delete_project_grant)(void *ctx, const ProjectGrantRef *req, EmptyResponse *resp);
} ProjectHandlers;

/* EventHandlers is the host's implementation of the EventService service. */
typedef struct EventHandlers {
    int (*create_event)(void *ctx, const Event *req, Event *resp);
    int (*get_event)(void *ctx, const EventID *req, Event *resp);
    int (*update_event)(void *ctx, const Event *req, Event *resp);
    int (*delete_event)(void *ctx, const EventID *req, EmptyResponse *resp);
    int (*delete_event_and_future)(void *ctx, const EventID *req, EmptyResponse *resp);
    int (*list_events)(void *ctx, const HouseScopedListRequest *req, Event * *resp);
} EventHandlers;

/* TaskHandlers is the host's implementation of the TaskService service. */
typedef struct TaskHandlers {
    int (*create_task)(void *ctx, const Task *req, Task *resp);
    int (*get_task)(void *ctx, const TaskID *req, Task *resp);
    int (*update_task)(void *ctx, const Task *req, Task *resp);
    int (*delete_task)(void *ctx, const TaskID *req, EmptyResponse *resp);
    int (*list_tasks)(void *ctx, const HouseScopedListRequest *req, TaskList *resp);
    int (*set_task_visibility)(void *ctx, const SetTaskVisibilityRequest *req, Task *resp);
    int (*list_task_grants)(void *ctx, const TaskID *req, Grant * *resp);
    int (*put_task_grant)(void *ctx, const PutTaskGrantRequest *req, EmptyResponse *resp);
    int (*delete_task_grant)(void *ctx, const TaskGrantRef *req, EmptyResponse *resp);
} TaskHandlers;

/* DependencyHandlers is the host's implementation of the DependencyService service. */
typedef struct DependencyHandlers {
    int (*add_dependency)(void *ctx, const DependencyRef *req, EmptyResponse *resp);
    int (*remove_dependency)(void *ctx, const DependencyRef *req, EmptyResponse *resp);
    int (*get_dependencies)(void *ctx, const DependencyTarget *req, DependencyGraph *resp);
} DependencyHandlers;

/* CommentHandlers is the host's implementation of the CommentService service. */
typedef struct CommentHandlers {
    int (*create_comment)(void *ctx, const Comment *req, Comment *resp);
    int (*get_comment)(void *ctx, const CommentID *req, Comment *resp);
    int (*update_comment)(void *ctx, const Comment *req, Comment *resp);
    int (*delete_comment)(void *ctx, const CommentID *req, EmptyResponse *resp);
    int (*list_comments)(void *ctx, const CommentListRequest *req, Comment * *resp);
} CommentHandlers;

/* NotificationHandlers is the host's implementation of the NotificationService service. */
typedef struct NotificationHandlers {
    int (*list_notifications)(void *ctx, const NotificationListRequest *req, Notification * *resp);
    int (*unread_count)(void *ctx, const HouseID *req, NotificationUnreadCount *resp);
    int (*mark_read)(void *ctx, const NotificationID *req, Notification *resp);
    int (*mark_all_read)(void *ctx, const HouseID *req, EmptyResponse *resp);
} NotificationHandlers;

/* ShareHandlers is the host's implementation of the ShareService service. */
typedef struct ShareHandlers {
    int (*create_share)(void *ctx, const Share *req, Share *resp);
    int (*delete_share)(void *ctx, const ShareID *req, EmptyResponse *resp);
    int (*list_shares_by_resource)(void *ctx, const ResourceRef *req, Share * *resp);
    int (*check_access)(void *ctx, const ShareAccessRequest *req, Share *resp);
} ShareHandlers;

/* MemberAuditHandlers is the host's implementation of the MemberAuditService service. */
typedef struct MemberAuditHandlers {
    int (*list_audits_for_member)(void *ctx, const MemberScopedListRequest *req, MemberAudit * *resp);
} MemberAuditHandlers;

/* SettingsHandlers is the host's implementation of the SettingsService service. */
typedef struct SettingsHandlers {
    int (*get_settings)(void *ctx, const HouseID *req, EffectiveSettings *resp);
    int (*update_settings)(void *ctx, const UpdateSettingsRequest *req, EffectiveSettings *resp);
} SettingsHandlers;

/* BugHandlers is the host's implementation of the BugService service. */
typedef struct BugHandlers {
    int (*report_bug)(void *ctx, const BugReportRequest *req, Task *resp);
} BugHandlers;

/* AuditHandlers is the host's implementation of the AuditService service. */
typedef struct AuditHandlers {
    int (*query_audit)(void *ctx, const AuditQuery *req, AuditPage *resp);
} AuditHandlers;

/* TrashHandlers is the host's implementation of the TrashService service. */
typedef struct TrashHandlers {
    int (*list_trash)(void *ctx, const HouseScopedListRequest *req, TrashPage *resp);
    int (*restore)(void *ctx, const RestoreRequest *req, EmptyResponse *resp);
    int (*purge)(void *ctx, const PurgeRequest *req, EmptyResponse *resp);
} TrashHandlers;

#endif /* CSILGEN_SERVER_GEN_H */
