/* Generated CSIL value types. */
/* Code generated by csilgen; DO NOT EDIT. */
#ifndef CSILGEN_TYPES_GEN_H
#define CSILGEN_TYPES_GEN_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef struct CsilBytes {
    uint8_t *data;
    size_t len;
} CsilBytes;

/* TaskStatus is an enumeration. */
typedef enum TaskStatus {
    TASK_STATUS_OPEN,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_DONE,
    TASK_STATUS_CANCELLED,
} TaskStatus;

/* TargetType is an enumeration. */
typedef enum TargetType {
    TARGET_TYPE_EVENT,
    TARGET_TYPE_TASK,
    TARGET_TYPE_PROJECT,
} TargetType;

/* AccessLevel is an enumeration. */
typedef enum AccessLevel {
    ACCESS_LEVEL_NONE,
    ACCESS_LEVEL_READ,
    ACCESS_LEVEL_EDIT,
    ACCESS_LEVEL_FULL,
} AccessLevel;

/* GranteeType is an enumeration. */
typedef enum GranteeType {
    GRANTEE_TYPE_MEMBER,
    GRANTEE_TYPE_GROUP,
} GranteeType;

/* ResourceType is an enumeration. */
typedef enum ResourceType {
    RESOURCE_TYPE_EVENT,
    RESOURCE_TYPE_TASK,
    RESOURCE_TYPE_HOUSE,
} ResourceType;

/* ProjectStatus is an enumeration. */
typedef enum ProjectStatus {
    PROJECT_STATUS_ACTIVE,
    PROJECT_STATUS_ARCHIVED,
} ProjectStatus;

/* DependencyNodeType is an enumeration. */
typedef enum DependencyNodeType {
    DEPENDENCY_NODE_TYPE_TASK,
    DEPENDENCY_NODE_TYPE_PROJECT,
} DependencyNodeType;

/* RecurrenceFreq is an enumeration. */
typedef enum RecurrenceFreq {
    RECURRENCE_FREQ_HOURLY,
    RECURRENCE_FREQ_DAILY,
    RECURRENCE_FREQ_WEEKLY,
    RECURRENCE_FREQ_MONTHLY,
    RECURRENCE_FREQ_QUARTERLY,
    RECURRENCE_FREQ_YEARLY,
} RecurrenceFreq;

/* MilestoneState is an enumeration. */
typedef enum MilestoneState {
    MILESTONE_STATE_DONE,
    MILESTONE_STATE_CURRENT,
    MILESTONE_STATE_FUTURE,
} MilestoneState;

/* Forward declarations (resolve mutual and out-of-order references). */
typedef struct House House;
typedef struct Member Member;
typedef struct TrustedDomain TrustedDomain;
typedef struct Role Role;
typedef struct MemberRole MemberRole;
typedef struct MemberAudit MemberAudit;
typedef struct Skill Skill;
typedef struct MemberSkill MemberSkill;
typedef struct GroupSkill GroupSkill;
typedef struct Group Group;
typedef struct GroupMember GroupMember;
typedef struct Project Project;
typedef struct ProjectTask ProjectTask;
typedef struct ProjectMember ProjectMember;
typedef struct ProjectOwner ProjectOwner;
typedef struct Milestone Milestone;
typedef struct Event Event;
typedef struct Task Task;
typedef struct Comment Comment;
typedef struct Share Share;
typedef struct HouseSummary HouseSummary;
typedef struct HouseRoles HouseRoles;
typedef struct Identity Identity;
typedef struct LoginRequest LoginRequest;
typedef struct CompleteRequest CompleteRequest;
typedef struct LoginResponse LoginResponse;
typedef struct DevUserEntry DevUserEntry;
typedef struct DevUsersResponse DevUsersResponse;
typedef struct DevLoginRequest DevLoginRequest;
typedef struct MeResponse MeResponse;
typedef struct EmptyRequest EmptyRequest;
typedef struct EmptyResponse EmptyResponse;
typedef struct BoolResponse BoolResponse;
typedef struct HouseListRequest HouseListRequest;
typedef struct HouseScopedListRequest HouseScopedListRequest;
typedef struct TaskList TaskList;
typedef struct ProjectList ProjectList;
typedef struct MemberScopedListRequest MemberScopedListRequest;
typedef struct ProjectScopedListRequest ProjectScopedListRequest;
typedef struct CommentListRequest CommentListRequest;
typedef struct Notification Notification;
typedef struct NotificationListRequest NotificationListRequest;
typedef struct NotificationUnreadCount NotificationUnreadCount;
typedef struct ShareAccessRequest ShareAccessRequest;
typedef struct ResourceRef ResourceRef;
typedef struct MemberRoleRef MemberRoleRef;
typedef struct MemberSkillRef MemberSkillRef;
typedef struct GroupSkillRef GroupSkillRef;
typedef struct GroupMemberRef GroupMemberRef;
typedef struct ProjectTaskRef ProjectTaskRef;
typedef struct ProjectTaskOrderRequest ProjectTaskOrderRequest;
typedef struct ProjectMemberRef ProjectMemberRef;
typedef struct ProjectOwnerRef ProjectOwnerRef;
typedef struct DependencyRef DependencyRef;
typedef struct DependencyTarget DependencyTarget;
typedef struct DependencyNode DependencyNode;
typedef struct DependencyGraph DependencyGraph;
typedef struct Grant Grant;
typedef struct TaskGrantRef TaskGrantRef;
typedef struct PutTaskGrantRequest PutTaskGrantRequest;
typedef struct SetTaskVisibilityRequest SetTaskVisibilityRequest;
typedef struct ProjectGrantRef ProjectGrantRef;
typedef struct PutProjectGrantRequest PutProjectGrantRequest;
typedef struct SetProjectVisibilityRequest SetProjectVisibilityRequest;
typedef struct EffectiveSettings EffectiveSettings;
typedef struct UpdateSettingsRequest UpdateSettingsRequest;
typedef struct BugReportRequest BugReportRequest;
typedef struct ServiceError ServiceError;
typedef struct AuditEntry AuditEntry;
typedef struct AuditQuery AuditQuery;
typedef struct AuditPage AuditPage;
typedef struct TrashItem TrashItem;
typedef struct TrashPage TrashPage;
typedef struct RestoreRequest RestoreRequest;
typedef struct PurgeRequest PurgeRequest;

/* HouseID is a type alias. */
typedef char *HouseID;

/* MemberID is a type alias. */
typedef char *MemberID;

/* RoleID is a type alias. */
typedef char *RoleID;

/* SkillID is a type alias. */
typedef char *SkillID;

/* GroupID is a type alias. */
typedef char *GroupID;

/* ProjectID is a type alias. */
typedef char *ProjectID;

/* EventID is a type alias. */
typedef char *EventID;

/* TaskID is a type alias. */
typedef char *TaskID;

/* CommentID is a type alias. */
typedef char *CommentID;

/* ShareID is a type alias. */
typedef char *ShareID;

/* TrustedDomainID is a type alias. */
typedef char *TrustedDomainID;

/* MemberAuditID is a type alias. */
typedef char *MemberAuditID;

/* MilestoneID is a type alias. */
typedef char *MilestoneID;

/* NotificationID is a type alias. */
typedef char *NotificationID;

/* NotificationEventID is a type alias. */
typedef char *NotificationEventID;

/* Timestamp is a type alias. */
typedef char *Timestamp;

/* AuditID is a type alias. */
typedef char *AuditID;

/* Identity is a structured data type. */
typedef struct Identity {
    char *domain;
    char *user_id;
    char *display_name;
    HouseRoles *houses;
    size_t houses_count;
    int64_t iat;
    int64_t exp;
} Identity;

/* LoginRequest is a structured data type. */
typedef struct LoginRequest {
    char *signed_assertion;
} LoginRequest;

/* CompleteRequest is a structured data type. */
typedef struct CompleteRequest {
    char *encrypted_token;
} CompleteRequest;

/* DevUsersResponse is a structured data type. */
typedef struct DevUsersResponse {
    DevUserEntry *users;
    size_t users_count;
} DevUsersResponse;

/* EmptyRequest is a structured data type. */
typedef struct EmptyRequest {
} EmptyRequest;

/* EmptyResponse is a structured data type. */
typedef struct EmptyResponse {
} EmptyResponse;

/* BoolResponse is a structured data type. */
typedef struct BoolResponse {
    bool value;
} BoolResponse;

/* HouseListRequest is a structured data type. */
typedef struct HouseListRequest {
    uint64_t *limit;
    uint64_t *offset;
} HouseListRequest;

/* TaskList is a structured data type. */
typedef struct TaskList {
    Task *tasks;
    size_t tasks_count;
    uint64_t hidden_count;
} TaskList;

/* ProjectList is a structured data type. */
typedef struct ProjectList {
    Project *projects;
    size_t projects_count;
    uint64_t hidden_count;
} ProjectList;

/* NotificationUnreadCount is a structured data type. */
typedef struct NotificationUnreadCount {
    uint64_t count;
} NotificationUnreadCount;

/* DependencyGraph is a structured data type. */
typedef struct DependencyGraph {
    DependencyNode *dependencies;
    size_t dependencies_count;
    DependencyNode *dependents;
    size_t dependents_count;
} DependencyGraph;

/* EffectiveSettings is a structured data type. */
typedef struct EffectiveSettings {
    bool *bug_reports_enabled;
    ProjectID *bug_reports_project_id;
    AccessLevel *default_project_visibility;
} EffectiveSettings;

/* ServiceError is a structured data type. */
typedef struct ServiceError {
    uint64_t code;
    char *message;
} ServiceError;

/* AuditPage is a structured data type. */
typedef struct AuditPage {
    AuditEntry *entries;
    size_t entries_count;
    char *next_cursor;
} AuditPage;

/* TrashPage is a structured data type. */
typedef struct TrashPage {
    TrashItem *items;
    size_t items_count;
    char *next_cursor;
} TrashPage;

/* House is a structured data type. */
typedef struct House {
    HouseID house_id;
    char *name;
    char *description;
    Timestamp created_at;
    Timestamp updated_at;
} House;

/* Member is a structured data type. */
typedef struct Member {
    MemberID member_id;
    HouseID house_id;
    char *linkkeys_domain;
    char *linkkeys_user_id;
    char *display_name;
    char *email;
    char *avatar_url;
    CsilBytes *cached_public_key;
    Timestamp created_at;
    Timestamp updated_at;
    Timestamp *last_seen_at;
    Timestamp *deactivated_at;
} Member;

/* TrustedDomain is a structured data type. */
typedef struct TrustedDomain {
    TrustedDomainID trusted_domain_id;
    HouseID house_id;
    char *domain;
    Timestamp created_at;
} TrustedDomain;

/* Role is a structured data type. */
typedef struct Role {
    RoleID role_id;
    HouseID house_id;
    char *name;
    char *description;
    Timestamp created_at;
    Timestamp updated_at;
} Role;

/* MemberRole is a structured data type. */
typedef struct MemberRole {
    MemberID member_id;
    RoleID role_id;
    Timestamp created_at;
} MemberRole;

/* MemberAudit is a structured data type. */
typedef struct MemberAudit {
    MemberAuditID audit_id;
    HouseID house_id;
    MemberID subject_member_id;
    MemberID *actor_member_id;
    char *action;
    char *target_type;
    char *target_id;
    char *detail;
    Timestamp created_at;
} MemberAudit;

/* Skill is a structured data type. */
typedef struct Skill {
    SkillID skill_id;
    HouseID house_id;
    char *name;
    char *description;
    Timestamp created_at;
    Timestamp updated_at;
} Skill;

/* MemberSkill is a structured data type. */
typedef struct MemberSkill {
    MemberID member_id;
    SkillID skill_id;
    Timestamp created_at;
} MemberSkill;

/* GroupSkill is a structured data type. */
typedef struct GroupSkill {
    GroupID group_id;
    SkillID skill_id;
    Timestamp created_at;
} GroupSkill;

/* Group is a structured data type. */
typedef struct Group {
    GroupID group_id;
    HouseID house_id;
    char *name;
    char *description;
    Timestamp created_at;
    Timestamp updated_at;
} Group;

/* GroupMember is a structured data type. */
typedef struct GroupMember {
    GroupID group_id;
    MemberID member_id;
    Timestamp created_at;
} GroupMember;

/* Project is a structured data type. */
typedef struct Project {
    ProjectID project_id;
    HouseID house_id;
    char *name;
    char *description;
    char *category;
    ProjectStatus *status;
    AccessLevel *visibility;
    MemberID *created_by_member_id;
    Timestamp created_at;
    Timestamp updated_at;
} Project;

/* ProjectTask is a structured data type. */
typedef struct ProjectTask {
    ProjectID project_id;
    TaskID task_id;
    int64_t position;
    Timestamp created_at;
} ProjectTask;

/* ProjectMember is a structured data type. */
typedef struct ProjectMember {
    ProjectID project_id;
    MemberID member_id;
    Timestamp created_at;
} ProjectMember;

/* ProjectOwner is a structured data type. */
typedef struct ProjectOwner {
    ProjectID project_id;
    MemberID member_id;
    Timestamp created_at;
} ProjectOwner;

/* Milestone is a structured data type. */
typedef struct Milestone {
    MilestoneID milestone_id;
    ProjectID project_id;
    char *label;
    char *when_label;
    MilestoneState state;
    int64_t position;
    Timestamp created_at;
    Timestamp updated_at;
} Milestone;

/* Event is a structured data type. */
typedef struct Event {
    EventID event_id;
    HouseID house_id;
    MemberID owner_member_id;
    char *title;
    char *description;
    char *location;
    Timestamp *starts_at;
    Timestamp *ends_at;
    bool *all_day;
    RecurrenceFreq *recurrence_freq;
    int64_t *recurrence_interval;
    int64_t *recurrence_by_weekday;
    size_t recurrence_by_weekday_count;
    int64_t *recurrence_by_setpos;
    Timestamp *next_recurrence_at;
    EventID *recurrence_root_event_id;
    Timestamp created_at;
    Timestamp updated_at;
} Event;

/* Task is a structured data type. */
typedef struct Task {
    TaskID task_id;
    HouseID house_id;
    MemberID owner_member_id;
    MemberID *assignees;
    size_t assignees_count;
    SkillID *assigned_to_skill_id;
    TaskID *parent_task_id;
    AccessLevel *visibility;
    char *title;
    char *description;
    TaskStatus *status;
    Timestamp *due_at;
    char *tag;
    uint64_t *estimate_minutes;
    RecurrenceFreq *recurrence_freq;
    int64_t *recurrence_interval;
    int64_t *recurrence_by_weekday;
    size_t recurrence_by_weekday_count;
    int64_t *recurrence_by_setpos;
    Timestamp *next_recurrence_at;
    TaskID *recurrence_root_task_id;
    Timestamp *deleted_at;
    Timestamp created_at;
    Timestamp updated_at;
} Task;

/* Comment is a structured data type. */
typedef struct Comment {
    CommentID comment_id;
    HouseID house_id;
    MemberID member_id;
    TargetType target_type;
    char *target_id;
    char *body;
    Timestamp created_at;
    Timestamp updated_at;
} Comment;

/* Share is a structured data type. */
typedef struct Share {
    ShareID share_id;
    HouseID house_id;
    MemberID shared_by;
    char *linkkeys_domain;
    char *linkkeys_user_id;
    ResourceType resource_type;
    char *resource_id;
    AccessLevel *access_level;
    Timestamp created_at;
    Timestamp *expires_at;
} Share;

/* HouseSummary is a structured data type. */
typedef struct HouseSummary {
    HouseID house_id;
    char *name;
    MemberID member_id;
    char **roles;
    size_t roles_count;
} HouseSummary;

/* HouseRoles is a structured data type. */
typedef struct HouseRoles {
    HouseID house;
    MemberID member;
    char **roles;
    size_t roles_count;
} HouseRoles;

/* LoginResponse is a structured data type. */
typedef struct LoginResponse {
    char *token;
    char *domain;
    char *user_id;
    char *display_name;
    Timestamp expires_at;
} LoginResponse;

/* DevUserEntry is a structured data type. */
typedef struct DevUserEntry {
    MemberID member_id;
    HouseID house_id;
    char *house_name;
    char *display_name;
    char *linkkeys_domain;
    char *linkkeys_user_id;
    char **roles;
    size_t roles_count;
} DevUserEntry;

/* DevLoginRequest is a structured data type. */
typedef struct DevLoginRequest {
    MemberID member_id;
} DevLoginRequest;

/* MeResponse is a structured data type. */
typedef struct MeResponse {
    char *domain;
    char *user_id;
    char *display_name;
    Timestamp expires_at;
    HouseSummary *houses;
    size_t houses_count;
} MeResponse;

/* HouseScopedListRequest is a structured data type. */
typedef struct HouseScopedListRequest {
    HouseID house_id;
    uint64_t *limit;
    uint64_t *offset;
} HouseScopedListRequest;

/* MemberScopedListRequest is a structured data type. */
typedef struct MemberScopedListRequest {
    HouseID house_id;
    MemberID member_id;
    uint64_t *limit;
    uint64_t *offset;
} MemberScopedListRequest;

/* ProjectScopedListRequest is a structured data type. */
typedef struct ProjectScopedListRequest {
    HouseID house_id;
    ProjectID project_id;
    uint64_t *limit;
    uint64_t *offset;
} ProjectScopedListRequest;

/* CommentListRequest is a structured data type. */
typedef struct CommentListRequest {
    TargetType target_type;
    char *target_id;
    uint64_t *limit;
    uint64_t *offset;
} CommentListRequest;

/* Notification is a structured data type. */
typedef struct Notification {
    NotificationID notification_id;
    HouseID house_id;
    MemberID member_id;
    char *kind;
    MemberID *actor_member_id;
    char *actor_name;
    char *target_type;
    char *target_id;
    char *target_title;
    char *body;
    bool read;
    Timestamp *read_at;
    Timestamp created_at;
} Notification;

/* NotificationListRequest is a structured data type. */
typedef struct NotificationListRequest {
    HouseID house_id;
    bool *unread_only;
    uint64_t *limit;
    uint64_t *offset;
} NotificationListRequest;

/* ShareAccessRequest is a structured data type. */
typedef struct ShareAccessRequest {
    char *linkkeys_domain;
    char *linkkeys_user_id;
    ResourceType resource_type;
    char *resource_id;
} ShareAccessRequest;

/* ResourceRef is a structured data type. */
typedef struct ResourceRef {
    ResourceType resource_type;
    char *resource_id;
} ResourceRef;

/* MemberRoleRef is a structured data type. */
typedef struct MemberRoleRef {
    MemberID member_id;
    RoleID role_id;
} MemberRoleRef;

/* MemberSkillRef is a structured data type. */
typedef struct MemberSkillRef {
    MemberID member_id;
    SkillID skill_id;
} MemberSkillRef;

/* GroupSkillRef is a structured data type. */
typedef struct GroupSkillRef {
    GroupID group_id;
    SkillID skill_id;
} GroupSkillRef;

/* GroupMemberRef is a structured data type. */
typedef struct GroupMemberRef {
    GroupID group_id;
    MemberID member_id;
} GroupMemberRef;

/* ProjectTaskRef is a structured data type. */
typedef struct ProjectTaskRef {
    ProjectID project_id;
    TaskID task_id;
} ProjectTaskRef;

/* ProjectTaskOrderRequest is a structured data type. */
typedef struct ProjectTaskOrderRequest {
    ProjectID project_id;
    TaskID task_id;
    int64_t position;
} ProjectTaskOrderRequest;

/* ProjectMemberRef is a structured data type. */
typedef struct ProjectMemberRef {
    ProjectID project_id;
    MemberID member_id;
} ProjectMemberRef;

/* ProjectOwnerRef is a structured data type. */
typedef struct ProjectOwnerRef {
    ProjectID project_id;
    MemberID member_id;
} ProjectOwnerRef;

/* DependencyRef is a structured data type. */
typedef struct DependencyRef {
    DependencyNodeType dependent_type;
    char *dependent_id;
    DependencyNodeType dependency_type;
    char *dependency_id;
} DependencyRef;

/* DependencyTarget is a structured data type. */
typedef struct DependencyTarget {
    DependencyNodeType type;
    char *id;
} DependencyTarget;

/* DependencyNode is a structured data type. */
typedef struct DependencyNode {
    DependencyNodeType type;
    char *id;
    char *title;
    char *status;
} DependencyNode;

/* Grant is a structured data type. */
typedef struct Grant {
    GranteeType grantee_type;
    char *grantee_id;
    AccessLevel access_level;
} Grant;

/* TaskGrantRef is a structured data type. */
typedef struct TaskGrantRef {
    TaskID task_id;
    GranteeType grantee_type;
    char *grantee_id;
} TaskGrantRef;

/* PutTaskGrantRequest is a structured data type. */
typedef struct PutTaskGrantRequest {
    TaskID task_id;
    GranteeType grantee_type;
    char *grantee_id;
    AccessLevel access_level;
} PutTaskGrantRequest;

/* SetTaskVisibilityRequest is a structured data type. */
typedef struct SetTaskVisibilityRequest {
    TaskID task_id;
    AccessLevel visibility;
} SetTaskVisibilityRequest;

/* ProjectGrantRef is a structured data type. */
typedef struct ProjectGrantRef {
    ProjectID project_id;
    GranteeType grantee_type;
    char *grantee_id;
} ProjectGrantRef;

/* PutProjectGrantRequest is a structured data type. */
typedef struct PutProjectGrantRequest {
    ProjectID project_id;
    GranteeType grantee_type;
    char *grantee_id;
    AccessLevel access_level;
} PutProjectGrantRequest;

/* SetProjectVisibilityRequest is a structured data type. */
typedef struct SetProjectVisibilityRequest {
    ProjectID project_id;
    AccessLevel visibility;
} SetProjectVisibilityRequest;

/* UpdateSettingsRequest is a structured data type. */
typedef struct UpdateSettingsRequest {
    HouseID house_id;
    EffectiveSettings settings;
} UpdateSettingsRequest;

/* BugReportRequest is a structured data type. */
typedef struct BugReportRequest {
    HouseID house_id;
    char *title;
    char *description;
} BugReportRequest;

/* AuditEntry is a structured data type. */
typedef struct AuditEntry {
    AuditID audit_id;
    HouseID *house_id;
    MemberID *actor_member_id;
    char *actor_domain;
    char *actor_user_id;
    char *service_name;
    char *method;
    char *action;
    char *resource_type;
    char *resource_id;
    char *outcome;
    char *before;
    char *after;
    char *detail;
    Timestamp created_at;
} AuditEntry;

/* AuditQuery is a structured data type. */
typedef struct AuditQuery {
    HouseID house_id;
    MemberID *actor_member_id;
    char *resource_type;
    char *action;
    Timestamp *since;
    Timestamp *until;
    char *cursor;
    uint64_t *limit;
} AuditQuery;

/* TrashItem is a structured data type. */
typedef struct TrashItem {
    char *resource_type;
    char *resource_id;
    HouseID house_id;
    char *title;
    Timestamp deleted_at;
    MemberID *deleted_by_member_id;
    char *deleted_op_id;
} TrashItem;

/* RestoreRequest is a structured data type. */
typedef struct RestoreRequest {
    HouseID house_id;
    char *deleted_op_id;
    char *resource_type;
    char *resource_id;
} RestoreRequest;

/* PurgeRequest is a structured data type. */
typedef struct PurgeRequest {
    HouseID house_id;
    char *resource_type;
    char *resource_id;
} PurgeRequest;

#endif /* CSILGEN_TYPES_GEN_H */
