// Package longhouseclient contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package longhouseclient

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. Both names are the verbatim CSIL names (service as written,
// op in kebab-case as written), ready to go on the wire unmodified. The generated
// client owns (de)serialization via the codec; the carrier only moves bytes, so
// it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// AuthClient is a typed client for the AuthService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type AuthClient struct {
	transport Transport
}

func NewAuthClient(transport Transport) *AuthClient {
	return &AuthClient{transport: transport}
}

func (c *AuthClient) Login(ctx context.Context, req LoginRequest) (LoginResponse, error) {
	var csilZero LoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "login", EncodeLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeLoginResponse(csilResp)
}

func (c *AuthClient) Complete(ctx context.Context, req CompleteRequest) (LoginResponse, error) {
	var csilZero LoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "complete", EncodeCompleteRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeLoginResponse(csilResp)
}

func (c *AuthClient) Refresh(ctx context.Context, req EmptyRequest) (LoginResponse, error) {
	var csilZero LoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "refresh", EncodeEmptyRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeLoginResponse(csilResp)
}

func (c *AuthClient) Logout(ctx context.Context, req EmptyRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "logout", EncodeEmptyRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *AuthClient) Me(ctx context.Context, req EmptyRequest) (MeResponse, error) {
	var csilZero MeResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "me", EncodeEmptyRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMeResponse(csilResp)
}

func (c *AuthClient) BeginCliLogin(ctx context.Context, req BeginCliLoginRequest) (BeginCliLoginResponse, error) {
	var csilZero BeginCliLoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "begin-cli-login", EncodeBeginCliLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBeginCliLoginResponse(csilResp)
}

func (c *AuthClient) InspectCliLogin(ctx context.Context, req ApproveCliLoginRequest) (CliLoginRequestInfo, error) {
	var csilZero CliLoginRequestInfo
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "inspect-cli-login", EncodeApproveCliLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCliLoginRequestInfo(csilResp)
}

func (c *AuthClient) ApproveCliLogin(ctx context.Context, req ApproveCliLoginRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "approve-cli-login", EncodeApproveCliLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *AuthClient) DenyCliLogin(ctx context.Context, req DenyCliLoginRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "deny-cli-login", EncodeDenyCliLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *AuthClient) ExchangeCliLogin(ctx context.Context, req ExchangeCliLoginRequest) (ExchangeCliLoginResponse, error) {
	var csilZero ExchangeCliLoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "exchange-cli-login", EncodeExchangeCliLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeExchangeCliLoginResponse(csilResp)
}

func (c *AuthClient) RefreshSession(ctx context.Context, req RefreshSessionRequest) (CliTokenResponse, error) {
	var csilZero CliTokenResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "refresh-session", EncodeRefreshSessionRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCliTokenResponse(csilResp)
}

func (c *AuthClient) ListSessions(ctx context.Context, req EmptyRequest) (CliSessionsResponse, error) {
	var csilZero CliSessionsResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "list-sessions", EncodeEmptyRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCliSessionsResponse(csilResp)
}

func (c *AuthClient) RevokeSession(ctx context.Context, req RevokeSessionRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "revoke-session", EncodeRevokeSessionRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

// DevAuthClient is a typed client for the DevAuthService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type DevAuthClient struct {
	transport Transport
}

func NewDevAuthClient(transport Transport) *DevAuthClient {
	return &DevAuthClient{transport: transport}
}

func (c *DevAuthClient) ListDevUsers(ctx context.Context, req EmptyRequest) (DevUsersResponse, error) {
	var csilZero DevUsersResponse
	csilResp, csilErr := c.transport.Call(ctx, "DevAuthService", "list-dev-users", EncodeEmptyRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDevUsersResponse(csilResp)
}

func (c *DevAuthClient) DevLogin(ctx context.Context, req DevLoginRequest) (LoginResponse, error) {
	var csilZero LoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "DevAuthService", "dev-login", EncodeDevLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeLoginResponse(csilResp)
}

// HouseClient is a typed client for the HouseService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type HouseClient struct {
	transport Transport
}

func NewHouseClient(transport Transport) *HouseClient {
	return &HouseClient{transport: transport}
}

func (c *HouseClient) CreateHouse(ctx context.Context, req House) (House, error) {
	var csilZero House
	csilResp, csilErr := c.transport.Call(ctx, "HouseService", "create-house", EncodeHouse(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeHouse(csilResp)
}

func (c *HouseClient) GetHouse(ctx context.Context, req HouseID) (House, error) {
	var csilZero House
	csilResp, csilErr := c.transport.Call(ctx, "HouseService", "get-house", EncodeHouseGetHouseRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeHouse(csilResp)
}

func (c *HouseClient) UpdateHouse(ctx context.Context, req House) (House, error) {
	var csilZero House
	csilResp, csilErr := c.transport.Call(ctx, "HouseService", "update-house", EncodeHouse(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeHouse(csilResp)
}

func (c *HouseClient) DeleteHouse(ctx context.Context, req HouseID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "HouseService", "delete-house", EncodeHouseDeleteHouseRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *HouseClient) ListHouses(ctx context.Context, req HouseListRequest) ([]House, error) {
	var csilZero []House
	csilResp, csilErr := c.transport.Call(ctx, "HouseService", "list-houses", EncodeHouseListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeHouseListHousesResponse(csilResp)
}

// MemberClient is a typed client for the MemberService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type MemberClient struct {
	transport Transport
}

func NewMemberClient(transport Transport) *MemberClient {
	return &MemberClient{transport: transport}
}

func (c *MemberClient) CreateMember(ctx context.Context, req Member) (Member, error) {
	var csilZero Member
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "create-member", EncodeMember(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMember(csilResp)
}

func (c *MemberClient) GetMember(ctx context.Context, req MemberID) (Member, error) {
	var csilZero Member
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "get-member", EncodeMemberGetMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMember(csilResp)
}

func (c *MemberClient) GetMemberByIdentity(ctx context.Context, req Member) (Member, error) {
	var csilZero Member
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "get-member-by-identity", EncodeMember(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMember(csilResp)
}

func (c *MemberClient) UpdateMember(ctx context.Context, req Member) (Member, error) {
	var csilZero Member
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "update-member", EncodeMember(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMember(csilResp)
}

func (c *MemberClient) DeactivateMember(ctx context.Context, req MemberID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "deactivate-member", EncodeMemberDeactivateMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *MemberClient) ReactivateMember(ctx context.Context, req MemberID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "reactivate-member", EncodeMemberReactivateMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *MemberClient) ListMembers(ctx context.Context, req HouseScopedListRequest) ([]Member, error) {
	var csilZero []Member
	csilResp, csilErr := c.transport.Call(ctx, "MemberService", "list-members", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMemberListMembersResponse(csilResp)
}

// TrustedDomainClient is a typed client for the TrustedDomainService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type TrustedDomainClient struct {
	transport Transport
}

func NewTrustedDomainClient(transport Transport) *TrustedDomainClient {
	return &TrustedDomainClient{transport: transport}
}

func (c *TrustedDomainClient) AddTrustedDomain(ctx context.Context, req TrustedDomain) (TrustedDomain, error) {
	var csilZero TrustedDomain
	csilResp, csilErr := c.transport.Call(ctx, "TrustedDomainService", "add-trusted-domain", EncodeTrustedDomain(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTrustedDomain(csilResp)
}

func (c *TrustedDomainClient) RemoveTrustedDomain(ctx context.Context, req TrustedDomainID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "TrustedDomainService", "remove-trusted-domain", EncodeTrustedDomainRemoveTrustedDomainRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *TrustedDomainClient) ListTrustedDomains(ctx context.Context, req HouseID) ([]TrustedDomain, error) {
	var csilZero []TrustedDomain
	csilResp, csilErr := c.transport.Call(ctx, "TrustedDomainService", "list-trusted-domains", EncodeTrustedDomainListTrustedDomainsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTrustedDomainListTrustedDomainsResponse(csilResp)
}

func (c *TrustedDomainClient) IsDomainTrusted(ctx context.Context, req TrustedDomain) (BoolResponse, error) {
	var csilZero BoolResponse
	csilResp, csilErr := c.transport.Call(ctx, "TrustedDomainService", "is-domain-trusted", EncodeTrustedDomain(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBoolResponse(csilResp)
}

// RoleClient is a typed client for the RoleService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type RoleClient struct {
	transport Transport
}

func NewRoleClient(transport Transport) *RoleClient {
	return &RoleClient{transport: transport}
}

func (c *RoleClient) CreateRole(ctx context.Context, req Role) (Role, error) {
	var csilZero Role
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "create-role", EncodeRole(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRole(csilResp)
}

func (c *RoleClient) UpdateRole(ctx context.Context, req Role) (Role, error) {
	var csilZero Role
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "update-role", EncodeRole(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRole(csilResp)
}

func (c *RoleClient) DeleteRole(ctx context.Context, req RoleID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "delete-role", EncodeRoleDeleteRoleRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *RoleClient) ListRoles(ctx context.Context, req HouseScopedListRequest) ([]Role, error) {
	var csilZero []Role
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "list-roles", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRoleListRolesResponse(csilResp)
}

func (c *RoleClient) GrantRole(ctx context.Context, req MemberRoleRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "grant-role", EncodeMemberRoleRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *RoleClient) RevokeRole(ctx context.Context, req MemberRoleRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "revoke-role", EncodeMemberRoleRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *RoleClient) ListMemberRoles(ctx context.Context, req MemberScopedListRequest) ([]Role, error) {
	var csilZero []Role
	csilResp, csilErr := c.transport.Call(ctx, "RoleService", "list-member-roles", EncodeMemberScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRoleListMemberRolesResponse(csilResp)
}

// SkillClient is a typed client for the SkillService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SkillClient struct {
	transport Transport
}

func NewSkillClient(transport Transport) *SkillClient {
	return &SkillClient{transport: transport}
}

func (c *SkillClient) CreateSkill(ctx context.Context, req Skill) (Skill, error) {
	var csilZero Skill
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "create-skill", EncodeSkill(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSkill(csilResp)
}

func (c *SkillClient) UpdateSkill(ctx context.Context, req Skill) (Skill, error) {
	var csilZero Skill
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "update-skill", EncodeSkill(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSkill(csilResp)
}

func (c *SkillClient) DeleteSkill(ctx context.Context, req SkillID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "delete-skill", EncodeSkillDeleteSkillRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *SkillClient) ListSkills(ctx context.Context, req HouseScopedListRequest) ([]Skill, error) {
	var csilZero []Skill
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "list-skills", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSkillListSkillsResponse(csilResp)
}

func (c *SkillClient) AddMemberSkill(ctx context.Context, req MemberSkillRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "add-member-skill", EncodeMemberSkillRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *SkillClient) RemoveMemberSkill(ctx context.Context, req MemberSkillRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "remove-member-skill", EncodeMemberSkillRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *SkillClient) ListMemberSkills(ctx context.Context, req MemberScopedListRequest) ([]Skill, error) {
	var csilZero []Skill
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "list-member-skills", EncodeMemberScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSkillListMemberSkillsResponse(csilResp)
}

func (c *SkillClient) AddGroupSkill(ctx context.Context, req GroupSkillRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "add-group-skill", EncodeGroupSkillRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *SkillClient) RemoveGroupSkill(ctx context.Context, req GroupSkillRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "remove-group-skill", EncodeGroupSkillRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *SkillClient) ListGroupSkills(ctx context.Context, req GroupID) ([]Skill, error) {
	var csilZero []Skill
	csilResp, csilErr := c.transport.Call(ctx, "SkillService", "list-group-skills", EncodeSkillListGroupSkillsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSkillListGroupSkillsResponse(csilResp)
}

// GroupClient is a typed client for the GroupService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type GroupClient struct {
	transport Transport
}

func NewGroupClient(transport Transport) *GroupClient {
	return &GroupClient{transport: transport}
}

func (c *GroupClient) CreateGroup(ctx context.Context, req Group) (Group, error) {
	var csilZero Group
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "create-group", EncodeGroup(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGroup(csilResp)
}

func (c *GroupClient) UpdateGroup(ctx context.Context, req Group) (Group, error) {
	var csilZero Group
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "update-group", EncodeGroup(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGroup(csilResp)
}

func (c *GroupClient) DeleteGroup(ctx context.Context, req GroupID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "delete-group", EncodeGroupDeleteGroupRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *GroupClient) ListGroups(ctx context.Context, req HouseScopedListRequest) ([]Group, error) {
	var csilZero []Group
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "list-groups", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGroupListGroupsResponse(csilResp)
}

func (c *GroupClient) AddGroupMember(ctx context.Context, req GroupMemberRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "add-group-member", EncodeGroupMemberRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *GroupClient) RemoveGroupMember(ctx context.Context, req GroupMemberRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "remove-group-member", EncodeGroupMemberRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *GroupClient) ListGroupMembers(ctx context.Context, req MemberScopedListRequest) ([]Member, error) {
	var csilZero []Member
	csilResp, csilErr := c.transport.Call(ctx, "GroupService", "list-group-members", EncodeMemberScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGroupListGroupMembersResponse(csilResp)
}

// ProjectClient is a typed client for the ProjectService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ProjectClient struct {
	transport Transport
}

func NewProjectClient(transport Transport) *ProjectClient {
	return &ProjectClient{transport: transport}
}

func (c *ProjectClient) CreateProject(ctx context.Context, req Project) (Project, error) {
	var csilZero Project
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "create-project", EncodeProject(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProject(csilResp)
}

func (c *ProjectClient) GetProject(ctx context.Context, req ProjectID) (Project, error) {
	var csilZero Project
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "get-project", EncodeProjectGetProjectRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProject(csilResp)
}

func (c *ProjectClient) UpdateProject(ctx context.Context, req Project) (Project, error) {
	var csilZero Project
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "update-project", EncodeProject(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProject(csilResp)
}

func (c *ProjectClient) DeleteProject(ctx context.Context, req ProjectID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "delete-project", EncodeProjectDeleteProjectRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) ListProjects(ctx context.Context, req HouseScopedListRequest) (ProjectList, error) {
	var csilZero ProjectList
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "list-projects", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProjectList(csilResp)
}

func (c *ProjectClient) ListProjectTasks(ctx context.Context, req ProjectScopedListRequest) (TaskList, error) {
	var csilZero TaskList
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "list-project-tasks", EncodeProjectScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTaskList(csilResp)
}

func (c *ProjectClient) AddProjectTask(ctx context.Context, req ProjectTaskOrderRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "add-project-task", EncodeProjectTaskOrderRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) RemoveProjectTask(ctx context.Context, req ProjectTaskRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "remove-project-task", EncodeProjectTaskRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) SetProjectTaskPosition(ctx context.Context, req ProjectTaskOrderRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "set-project-task-position", EncodeProjectTaskOrderRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) ListProjectMembers(ctx context.Context, req ProjectID) ([]Member, error) {
	var csilZero []Member
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "list-project-members", EncodeProjectListProjectMembersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProjectListProjectMembersResponse(csilResp)
}

func (c *ProjectClient) AddProjectMember(ctx context.Context, req ProjectMemberRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "add-project-member", EncodeProjectMemberRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) RemoveProjectMember(ctx context.Context, req ProjectMemberRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "remove-project-member", EncodeProjectMemberRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) ListProjectOwners(ctx context.Context, req ProjectID) ([]Member, error) {
	var csilZero []Member
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "list-project-owners", EncodeProjectListProjectOwnersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProjectListProjectOwnersResponse(csilResp)
}

func (c *ProjectClient) AddProjectOwner(ctx context.Context, req ProjectOwnerRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "add-project-owner", EncodeProjectOwnerRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) RemoveProjectOwner(ctx context.Context, req ProjectOwnerRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "remove-project-owner", EncodeProjectOwnerRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) ListMilestones(ctx context.Context, req ProjectID) ([]Milestone, error) {
	var csilZero []Milestone
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "list-milestones", EncodeProjectListMilestonesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProjectListMilestonesResponse(csilResp)
}

func (c *ProjectClient) CreateMilestone(ctx context.Context, req Milestone) (Milestone, error) {
	var csilZero Milestone
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "create-milestone", EncodeMilestone(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMilestone(csilResp)
}

func (c *ProjectClient) UpdateMilestone(ctx context.Context, req Milestone) (Milestone, error) {
	var csilZero Milestone
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "update-milestone", EncodeMilestone(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMilestone(csilResp)
}

func (c *ProjectClient) DeleteMilestone(ctx context.Context, req MilestoneID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "delete-milestone", EncodeProjectDeleteMilestoneRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) SetProjectVisibility(ctx context.Context, req SetProjectVisibilityRequest) (Project, error) {
	var csilZero Project
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "set-project-visibility", EncodeSetProjectVisibilityRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProject(csilResp)
}

func (c *ProjectClient) ListProjectGrants(ctx context.Context, req ProjectID) ([]Grant, error) {
	var csilZero []Grant
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "list-project-grants", EncodeProjectListProjectGrantsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeProjectListProjectGrantsResponse(csilResp)
}

func (c *ProjectClient) PutProjectGrant(ctx context.Context, req PutProjectGrantRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "put-project-grant", EncodePutProjectGrantRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ProjectClient) DeleteProjectGrant(ctx context.Context, req ProjectGrantRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ProjectService", "delete-project-grant", EncodeProjectGrantRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

// EventClient is a typed client for the EventService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type EventClient struct {
	transport Transport
}

func NewEventClient(transport Transport) *EventClient {
	return &EventClient{transport: transport}
}

func (c *EventClient) CreateEvent(ctx context.Context, req Event) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "create-event", EncodeEvent(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) GetEvent(ctx context.Context, req EventID) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "get-event", EncodeEventGetEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) UpdateEvent(ctx context.Context, req Event) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "update-event", EncodeEvent(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) DeleteEvent(ctx context.Context, req EventID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "delete-event", EncodeEventDeleteEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *EventClient) DeleteEventAndFuture(ctx context.Context, req EventID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "delete-event-and-future", EncodeEventDeleteEventAndFutureRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *EventClient) ListEvents(ctx context.Context, req HouseScopedListRequest) ([]Event, error) {
	var csilZero []Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "list-events", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventListEventsResponse(csilResp)
}

func (c *EventClient) GetCalendarView(ctx context.Context, req HouseID) (CalendarView, error) {
	var csilZero CalendarView
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "get-calendar-view", EncodeEventGetCalendarViewRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCalendarView(csilResp)
}

func (c *EventClient) SetCalendarView(ctx context.Context, req CalendarView) (CalendarView, error) {
	var csilZero CalendarView
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "set-calendar-view", EncodeCalendarView(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCalendarView(csilResp)
}

// TaskClient is a typed client for the TaskService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type TaskClient struct {
	transport Transport
}

func NewTaskClient(transport Transport) *TaskClient {
	return &TaskClient{transport: transport}
}

func (c *TaskClient) CreateTask(ctx context.Context, req Task) (Task, error) {
	var csilZero Task
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "create-task", EncodeTask(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTask(csilResp)
}

func (c *TaskClient) GetTask(ctx context.Context, req TaskID) (Task, error) {
	var csilZero Task
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "get-task", EncodeTaskGetTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTask(csilResp)
}

func (c *TaskClient) UpdateTask(ctx context.Context, req Task) (Task, error) {
	var csilZero Task
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "update-task", EncodeTask(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTask(csilResp)
}

func (c *TaskClient) DeleteTask(ctx context.Context, req TaskID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "delete-task", EncodeTaskDeleteTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *TaskClient) ListTasks(ctx context.Context, req HouseScopedListRequest) (TaskList, error) {
	var csilZero TaskList
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "list-tasks", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTaskList(csilResp)
}

func (c *TaskClient) SetTaskVisibility(ctx context.Context, req SetTaskVisibilityRequest) (Task, error) {
	var csilZero Task
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "set-task-visibility", EncodeSetTaskVisibilityRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTask(csilResp)
}

func (c *TaskClient) ListTaskGrants(ctx context.Context, req TaskID) ([]Grant, error) {
	var csilZero []Grant
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "list-task-grants", EncodeTaskListTaskGrantsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTaskListTaskGrantsResponse(csilResp)
}

func (c *TaskClient) PutTaskGrant(ctx context.Context, req PutTaskGrantRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "put-task-grant", EncodePutTaskGrantRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *TaskClient) DeleteTaskGrant(ctx context.Context, req TaskGrantRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "TaskService", "delete-task-grant", EncodeTaskGrantRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

// DependencyClient is a typed client for the DependencyService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type DependencyClient struct {
	transport Transport
}

func NewDependencyClient(transport Transport) *DependencyClient {
	return &DependencyClient{transport: transport}
}

func (c *DependencyClient) AddDependency(ctx context.Context, req DependencyRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "DependencyService", "add-dependency", EncodeDependencyRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *DependencyClient) RemoveDependency(ctx context.Context, req DependencyRef) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "DependencyService", "remove-dependency", EncodeDependencyRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *DependencyClient) GetDependencies(ctx context.Context, req DependencyTarget) (DependencyGraph, error) {
	var csilZero DependencyGraph
	csilResp, csilErr := c.transport.Call(ctx, "DependencyService", "get-dependencies", EncodeDependencyTarget(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDependencyGraph(csilResp)
}

// CommentClient is a typed client for the CommentService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type CommentClient struct {
	transport Transport
}

func NewCommentClient(transport Transport) *CommentClient {
	return &CommentClient{transport: transport}
}

func (c *CommentClient) CreateComment(ctx context.Context, req Comment) (Comment, error) {
	var csilZero Comment
	csilResp, csilErr := c.transport.Call(ctx, "CommentService", "create-comment", EncodeComment(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeComment(csilResp)
}

func (c *CommentClient) GetComment(ctx context.Context, req CommentID) (Comment, error) {
	var csilZero Comment
	csilResp, csilErr := c.transport.Call(ctx, "CommentService", "get-comment", EncodeCommentGetCommentRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeComment(csilResp)
}

func (c *CommentClient) UpdateComment(ctx context.Context, req Comment) (Comment, error) {
	var csilZero Comment
	csilResp, csilErr := c.transport.Call(ctx, "CommentService", "update-comment", EncodeComment(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeComment(csilResp)
}

func (c *CommentClient) DeleteComment(ctx context.Context, req CommentID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "CommentService", "delete-comment", EncodeCommentDeleteCommentRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *CommentClient) ListComments(ctx context.Context, req CommentListRequest) ([]Comment, error) {
	var csilZero []Comment
	csilResp, csilErr := c.transport.Call(ctx, "CommentService", "list-comments", EncodeCommentListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCommentListCommentsResponse(csilResp)
}

// NotificationClient is a typed client for the NotificationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type NotificationClient struct {
	transport Transport
}

func NewNotificationClient(transport Transport) *NotificationClient {
	return &NotificationClient{transport: transport}
}

func (c *NotificationClient) ListNotifications(ctx context.Context, req NotificationListRequest) ([]Notification, error) {
	var csilZero []Notification
	csilResp, csilErr := c.transport.Call(ctx, "NotificationService", "list-notifications", EncodeNotificationListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeNotificationListNotificationsResponse(csilResp)
}

func (c *NotificationClient) UnreadCount(ctx context.Context, req HouseID) (NotificationUnreadCount, error) {
	var csilZero NotificationUnreadCount
	csilResp, csilErr := c.transport.Call(ctx, "NotificationService", "unread-count", EncodeNotificationUnreadCountRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeNotificationUnreadCount(csilResp)
}

func (c *NotificationClient) MarkRead(ctx context.Context, req NotificationID) (Notification, error) {
	var csilZero Notification
	csilResp, csilErr := c.transport.Call(ctx, "NotificationService", "mark-read", EncodeNotificationMarkReadRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeNotification(csilResp)
}

func (c *NotificationClient) MarkAllRead(ctx context.Context, req HouseID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "NotificationService", "mark-all-read", EncodeNotificationMarkAllReadRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

// ShareClient is a typed client for the ShareService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ShareClient struct {
	transport Transport
}

func NewShareClient(transport Transport) *ShareClient {
	return &ShareClient{transport: transport}
}

func (c *ShareClient) CreateShare(ctx context.Context, req Share) (Share, error) {
	var csilZero Share
	csilResp, csilErr := c.transport.Call(ctx, "ShareService", "create-share", EncodeShare(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeShare(csilResp)
}

func (c *ShareClient) DeleteShare(ctx context.Context, req ShareID) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "ShareService", "delete-share", EncodeShareDeleteShareRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *ShareClient) ListSharesByResource(ctx context.Context, req ResourceRef) ([]Share, error) {
	var csilZero []Share
	csilResp, csilErr := c.transport.Call(ctx, "ShareService", "list-shares-by-resource", EncodeResourceRef(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeShareListSharesByResourceResponse(csilResp)
}

func (c *ShareClient) CheckAccess(ctx context.Context, req ShareAccessRequest) (Share, error) {
	var csilZero Share
	csilResp, csilErr := c.transport.Call(ctx, "ShareService", "check-access", EncodeShareAccessRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeShare(csilResp)
}

// MemberAuditClient is a typed client for the MemberAuditService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type MemberAuditClient struct {
	transport Transport
}

func NewMemberAuditClient(transport Transport) *MemberAuditClient {
	return &MemberAuditClient{transport: transport}
}

func (c *MemberAuditClient) ListAuditsForMember(ctx context.Context, req MemberScopedListRequest) ([]MemberAudit, error) {
	var csilZero []MemberAudit
	csilResp, csilErr := c.transport.Call(ctx, "MemberAuditService", "list-audits-for-member", EncodeMemberScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeMemberAuditListAuditsForMemberResponse(csilResp)
}

// SettingsClient is a typed client for the SettingsService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SettingsClient struct {
	transport Transport
}

func NewSettingsClient(transport Transport) *SettingsClient {
	return &SettingsClient{transport: transport}
}

func (c *SettingsClient) GetSettings(ctx context.Context, req HouseID) (EffectiveSettings, error) {
	var csilZero EffectiveSettings
	csilResp, csilErr := c.transport.Call(ctx, "SettingsService", "get-settings", EncodeSettingsGetSettingsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEffectiveSettings(csilResp)
}

func (c *SettingsClient) UpdateSettings(ctx context.Context, req UpdateSettingsRequest) (EffectiveSettings, error) {
	var csilZero EffectiveSettings
	csilResp, csilErr := c.transport.Call(ctx, "SettingsService", "update-settings", EncodeUpdateSettingsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEffectiveSettings(csilResp)
}

// BugClient is a typed client for the BugService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type BugClient struct {
	transport Transport
}

func NewBugClient(transport Transport) *BugClient {
	return &BugClient{transport: transport}
}

func (c *BugClient) ReportBug(ctx context.Context, req BugReportRequest) (Task, error) {
	var csilZero Task
	csilResp, csilErr := c.transport.Call(ctx, "BugService", "report-bug", EncodeBugReportRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTask(csilResp)
}

// AuditClient is a typed client for the AuditService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type AuditClient struct {
	transport Transport
}

func NewAuditClient(transport Transport) *AuditClient {
	return &AuditClient{transport: transport}
}

func (c *AuditClient) QueryAudit(ctx context.Context, req AuditQuery) (AuditPage, error) {
	var csilZero AuditPage
	csilResp, csilErr := c.transport.Call(ctx, "AuditService", "query-audit", EncodeAuditQuery(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAuditPage(csilResp)
}

// TrashClient is a typed client for the TrashService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type TrashClient struct {
	transport Transport
}

func NewTrashClient(transport Transport) *TrashClient {
	return &TrashClient{transport: transport}
}

func (c *TrashClient) ListTrash(ctx context.Context, req HouseScopedListRequest) (TrashPage, error) {
	var csilZero TrashPage
	csilResp, csilErr := c.transport.Call(ctx, "TrashService", "list-trash", EncodeHouseScopedListRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeTrashPage(csilResp)
}

func (c *TrashClient) Restore(ctx context.Context, req RestoreRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "TrashService", "restore", EncodeRestoreRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}

func (c *TrashClient) Purge(ctx context.Context, req PurgeRequest) (EmptyResponse, error) {
	var csilZero EmptyResponse
	csilResp, csilErr := c.transport.Call(ctx, "TrashService", "purge", EncodePurgeRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmptyResponse(csilResp)
}
