// Generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.

import 'csil_cbor.gen.dart';
import 'types.gen.dart';

/// The carrier seam a generated client delegates to. The generated client owns
/// (de)serialization — it encodes the typed request to CBOR and decodes the typed
/// response — so the carrier only moves bytes for the named (service, op).
abstract interface class CsilTransport {
  /// Perform the (service, op) call with the already-encoded request bytes and
  /// return the response bytes.
  List<int> call(String service, String op, List<int> request);
}

/// A typed, transport-agnostic client for the AuthService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class AuthClient {
  final CsilTransport transport;
  const AuthClient(this.transport);

  LoginResponse login(LoginRequest request) {
    final csilResp = transport.call('auth', 'Login', request.toCbor());
    return LoginResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  LoginResponse complete(CompleteRequest request) {
    final csilResp = transport.call('auth', 'Complete', request.toCbor());
    return LoginResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  LoginResponse refresh(EmptyRequest request) {
    final csilResp = transport.call('auth', 'Refresh', request.toCbor());
    return LoginResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse logout(EmptyRequest request) {
    final csilResp = transport.call('auth', 'Logout', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  MeResponse me(EmptyRequest request) {
    final csilResp = transport.call('auth', 'Me', request.toCbor());
    return MeResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the DevAuthService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class DevAuthClient {
  final CsilTransport transport;
  const DevAuthClient(this.transport);

  DevUsersResponse listDevUsers(EmptyRequest request) {
    final csilResp = transport.call('devauth', 'ListDevUsers', request.toCbor());
    return DevUsersResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  LoginResponse devLogin(DevLoginRequest request) {
    final csilResp = transport.call('devauth', 'DevLogin', request.toCbor());
    return LoginResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the HouseService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class HouseClient {
  final CsilTransport transport;
  const HouseClient(this.transport);

  House createHouse(House request) {
    final csilResp = transport.call('house', 'CreateHouse', request.toCbor());
    return House.fromCborValue(CsilCbor.decode(csilResp));
  }

  House getHouse(HouseId request) {
    final csilResp = transport.call('house', 'GetHouse', CsilCbor.encodeValue(request));
    return House.fromCborValue(CsilCbor.decode(csilResp));
  }

  House updateHouse(House request) {
    final csilResp = transport.call('house', 'UpdateHouse', request.toCbor());
    return House.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteHouse(HouseId request) {
    final csilResp = transport.call('house', 'DeleteHouse', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<House> listHouses(HouseListRequest request) {
    final csilResp = transport.call('house', 'ListHouses', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => House.fromCborValue(csilE)).cast<House>().toList();
  }

}

/// A typed, transport-agnostic client for the MemberService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class MemberClient {
  final CsilTransport transport;
  const MemberClient(this.transport);

  Member createMember(Member request) {
    final csilResp = transport.call('member', 'CreateMember', request.toCbor());
    return Member.fromCborValue(CsilCbor.decode(csilResp));
  }

  Member getMember(MemberId request) {
    final csilResp = transport.call('member', 'GetMember', CsilCbor.encodeValue(request));
    return Member.fromCborValue(CsilCbor.decode(csilResp));
  }

  Member getMemberByIdentity(Member request) {
    final csilResp = transport.call('member', 'GetMemberByIdentity', request.toCbor());
    return Member.fromCborValue(CsilCbor.decode(csilResp));
  }

  Member updateMember(Member request) {
    final csilResp = transport.call('member', 'UpdateMember', request.toCbor());
    return Member.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deactivateMember(MemberId request) {
    final csilResp = transport.call('member', 'DeactivateMember', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse reactivateMember(MemberId request) {
    final csilResp = transport.call('member', 'ReactivateMember', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Member> listMembers(HouseScopedListRequest request) {
    final csilResp = transport.call('member', 'ListMembers', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Member.fromCborValue(csilE)).cast<Member>().toList();
  }

}

/// A typed, transport-agnostic client for the TrustedDomainService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class TrustedDomainClient {
  final CsilTransport transport;
  const TrustedDomainClient(this.transport);

  TrustedDomain addTrustedDomain(TrustedDomain request) {
    final csilResp = transport.call('trusteddomain', 'AddTrustedDomain', request.toCbor());
    return TrustedDomain.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeTrustedDomain(TrustedDomainId request) {
    final csilResp = transport.call('trusteddomain', 'RemoveTrustedDomain', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<TrustedDomain> listTrustedDomains(HouseId request) {
    final csilResp = transport.call('trusteddomain', 'ListTrustedDomains', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => TrustedDomain.fromCborValue(csilE)).cast<TrustedDomain>().toList();
  }

  BoolResponse isDomainTrusted(TrustedDomain request) {
    final csilResp = transport.call('trusteddomain', 'IsDomainTrusted', request.toCbor());
    return BoolResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the RoleService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class RoleClient {
  final CsilTransport transport;
  const RoleClient(this.transport);

  Role createRole(Role request) {
    final csilResp = transport.call('role', 'CreateRole', request.toCbor());
    return Role.fromCborValue(CsilCbor.decode(csilResp));
  }

  Role updateRole(Role request) {
    final csilResp = transport.call('role', 'UpdateRole', request.toCbor());
    return Role.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteRole(RoleId request) {
    final csilResp = transport.call('role', 'DeleteRole', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Role> listRoles(HouseScopedListRequest request) {
    final csilResp = transport.call('role', 'ListRoles', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Role.fromCborValue(csilE)).cast<Role>().toList();
  }

  EmptyResponse grantRole(MemberRoleRef request) {
    final csilResp = transport.call('role', 'GrantRole', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse revokeRole(MemberRoleRef request) {
    final csilResp = transport.call('role', 'RevokeRole', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Role> listMemberRoles(MemberScopedListRequest request) {
    final csilResp = transport.call('role', 'ListMemberRoles', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Role.fromCborValue(csilE)).cast<Role>().toList();
  }

}

/// A typed, transport-agnostic client for the SkillService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class SkillClient {
  final CsilTransport transport;
  const SkillClient(this.transport);

  Skill createSkill(Skill request) {
    final csilResp = transport.call('skill', 'CreateSkill', request.toCbor());
    return Skill.fromCborValue(CsilCbor.decode(csilResp));
  }

  Skill updateSkill(Skill request) {
    final csilResp = transport.call('skill', 'UpdateSkill', request.toCbor());
    return Skill.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteSkill(SkillId request) {
    final csilResp = transport.call('skill', 'DeleteSkill', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Skill> listSkills(HouseScopedListRequest request) {
    final csilResp = transport.call('skill', 'ListSkills', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Skill.fromCborValue(csilE)).cast<Skill>().toList();
  }

  EmptyResponse addMemberSkill(MemberSkillRef request) {
    final csilResp = transport.call('skill', 'AddMemberSkill', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeMemberSkill(MemberSkillRef request) {
    final csilResp = transport.call('skill', 'RemoveMemberSkill', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Skill> listMemberSkills(MemberScopedListRequest request) {
    final csilResp = transport.call('skill', 'ListMemberSkills', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Skill.fromCborValue(csilE)).cast<Skill>().toList();
  }

  EmptyResponse addGroupSkill(GroupSkillRef request) {
    final csilResp = transport.call('skill', 'AddGroupSkill', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeGroupSkill(GroupSkillRef request) {
    final csilResp = transport.call('skill', 'RemoveGroupSkill', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Skill> listGroupSkills(GroupId request) {
    final csilResp = transport.call('skill', 'ListGroupSkills', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Skill.fromCborValue(csilE)).cast<Skill>().toList();
  }

}

/// A typed, transport-agnostic client for the GroupService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class GroupClient {
  final CsilTransport transport;
  const GroupClient(this.transport);

  Group createGroup(Group request) {
    final csilResp = transport.call('group', 'CreateGroup', request.toCbor());
    return Group.fromCborValue(CsilCbor.decode(csilResp));
  }

  Group updateGroup(Group request) {
    final csilResp = transport.call('group', 'UpdateGroup', request.toCbor());
    return Group.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteGroup(GroupId request) {
    final csilResp = transport.call('group', 'DeleteGroup', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Group> listGroups(HouseScopedListRequest request) {
    final csilResp = transport.call('group', 'ListGroups', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Group.fromCborValue(csilE)).cast<Group>().toList();
  }

  EmptyResponse addGroupMember(GroupMemberRef request) {
    final csilResp = transport.call('group', 'AddGroupMember', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeGroupMember(GroupMemberRef request) {
    final csilResp = transport.call('group', 'RemoveGroupMember', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Member> listGroupMembers(MemberScopedListRequest request) {
    final csilResp = transport.call('group', 'ListGroupMembers', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Member.fromCborValue(csilE)).cast<Member>().toList();
  }

}

/// A typed, transport-agnostic client for the ProjectService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class ProjectClient {
  final CsilTransport transport;
  const ProjectClient(this.transport);

  Project createProject(Project request) {
    final csilResp = transport.call('project', 'CreateProject', request.toCbor());
    return Project.fromCborValue(CsilCbor.decode(csilResp));
  }

  Project getProject(ProjectId request) {
    final csilResp = transport.call('project', 'GetProject', CsilCbor.encodeValue(request));
    return Project.fromCborValue(CsilCbor.decode(csilResp));
  }

  Project updateProject(Project request) {
    final csilResp = transport.call('project', 'UpdateProject', request.toCbor());
    return Project.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteProject(ProjectId request) {
    final csilResp = transport.call('project', 'DeleteProject', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  ProjectList listProjects(HouseScopedListRequest request) {
    final csilResp = transport.call('project', 'ListProjects', request.toCbor());
    return ProjectList.fromCborValue(CsilCbor.decode(csilResp));
  }

  TaskList listProjectTasks(ProjectScopedListRequest request) {
    final csilResp = transport.call('project', 'ListProjectTasks', request.toCbor());
    return TaskList.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse addProjectTask(ProjectTaskOrderRequest request) {
    final csilResp = transport.call('project', 'AddProjectTask', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeProjectTask(ProjectTaskRef request) {
    final csilResp = transport.call('project', 'RemoveProjectTask', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse setProjectTaskPosition(ProjectTaskOrderRequest request) {
    final csilResp = transport.call('project', 'SetProjectTaskPosition', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Member> listProjectMembers(ProjectId request) {
    final csilResp = transport.call('project', 'ListProjectMembers', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Member.fromCborValue(csilE)).cast<Member>().toList();
  }

  EmptyResponse addProjectMember(ProjectMemberRef request) {
    final csilResp = transport.call('project', 'AddProjectMember', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeProjectMember(ProjectMemberRef request) {
    final csilResp = transport.call('project', 'RemoveProjectMember', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Member> listProjectOwners(ProjectId request) {
    final csilResp = transport.call('project', 'ListProjectOwners', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Member.fromCborValue(csilE)).cast<Member>().toList();
  }

  EmptyResponse addProjectOwner(ProjectOwnerRef request) {
    final csilResp = transport.call('project', 'AddProjectOwner', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeProjectOwner(ProjectOwnerRef request) {
    final csilResp = transport.call('project', 'RemoveProjectOwner', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Milestone> listMilestones(ProjectId request) {
    final csilResp = transport.call('project', 'ListMilestones', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Milestone.fromCborValue(csilE)).cast<Milestone>().toList();
  }

  Milestone createMilestone(Milestone request) {
    final csilResp = transport.call('project', 'CreateMilestone', request.toCbor());
    return Milestone.fromCborValue(CsilCbor.decode(csilResp));
  }

  Milestone updateMilestone(Milestone request) {
    final csilResp = transport.call('project', 'UpdateMilestone', request.toCbor());
    return Milestone.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteMilestone(MilestoneId request) {
    final csilResp = transport.call('project', 'DeleteMilestone', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  Project setProjectVisibility(SetProjectVisibilityRequest request) {
    final csilResp = transport.call('project', 'SetProjectVisibility', request.toCbor());
    return Project.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Grant> listProjectGrants(ProjectId request) {
    final csilResp = transport.call('project', 'ListProjectGrants', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Grant.fromCborValue(csilE)).cast<Grant>().toList();
  }

  EmptyResponse putProjectGrant(PutProjectGrantRequest request) {
    final csilResp = transport.call('project', 'PutProjectGrant', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteProjectGrant(ProjectGrantRef request) {
    final csilResp = transport.call('project', 'DeleteProjectGrant', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the EventService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class EventClient {
  final CsilTransport transport;
  const EventClient(this.transport);

  Event createEvent(Event request) {
    final csilResp = transport.call('event', 'CreateEvent', request.toCbor());
    return Event.fromCborValue(CsilCbor.decode(csilResp));
  }

  Event getEvent(EventId request) {
    final csilResp = transport.call('event', 'GetEvent', CsilCbor.encodeValue(request));
    return Event.fromCborValue(CsilCbor.decode(csilResp));
  }

  Event updateEvent(Event request) {
    final csilResp = transport.call('event', 'UpdateEvent', request.toCbor());
    return Event.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteEvent(EventId request) {
    final csilResp = transport.call('event', 'DeleteEvent', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteEventAndFuture(EventId request) {
    final csilResp = transport.call('event', 'DeleteEventAndFuture', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Event> listEvents(HouseScopedListRequest request) {
    final csilResp = transport.call('event', 'ListEvents', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Event.fromCborValue(csilE)).cast<Event>().toList();
  }

}

/// A typed, transport-agnostic client for the TaskService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class TaskClient {
  final CsilTransport transport;
  const TaskClient(this.transport);

  Task createTask(Task request) {
    final csilResp = transport.call('task', 'CreateTask', request.toCbor());
    return Task.fromCborValue(CsilCbor.decode(csilResp));
  }

  Task getTask(TaskId request) {
    final csilResp = transport.call('task', 'GetTask', CsilCbor.encodeValue(request));
    return Task.fromCborValue(CsilCbor.decode(csilResp));
  }

  Task updateTask(Task request) {
    final csilResp = transport.call('task', 'UpdateTask', request.toCbor());
    return Task.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteTask(TaskId request) {
    final csilResp = transport.call('task', 'DeleteTask', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  TaskList listTasks(HouseScopedListRequest request) {
    final csilResp = transport.call('task', 'ListTasks', request.toCbor());
    return TaskList.fromCborValue(CsilCbor.decode(csilResp));
  }

  Task setTaskVisibility(SetTaskVisibilityRequest request) {
    final csilResp = transport.call('task', 'SetTaskVisibility', request.toCbor());
    return Task.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Grant> listTaskGrants(TaskId request) {
    final csilResp = transport.call('task', 'ListTaskGrants', CsilCbor.encodeValue(request));
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Grant.fromCborValue(csilE)).cast<Grant>().toList();
  }

  EmptyResponse putTaskGrant(PutTaskGrantRequest request) {
    final csilResp = transport.call('task', 'PutTaskGrant', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteTaskGrant(TaskGrantRef request) {
    final csilResp = transport.call('task', 'DeleteTaskGrant', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the DependencyService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class DependencyClient {
  final CsilTransport transport;
  const DependencyClient(this.transport);

  EmptyResponse addDependency(DependencyRef request) {
    final csilResp = transport.call('dependency', 'AddDependency', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse removeDependency(DependencyRef request) {
    final csilResp = transport.call('dependency', 'RemoveDependency', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  DependencyGraph getDependencies(DependencyTarget request) {
    final csilResp = transport.call('dependency', 'GetDependencies', request.toCbor());
    return DependencyGraph.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the CommentService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class CommentClient {
  final CsilTransport transport;
  const CommentClient(this.transport);

  Comment createComment(Comment request) {
    final csilResp = transport.call('comment', 'CreateComment', request.toCbor());
    return Comment.fromCborValue(CsilCbor.decode(csilResp));
  }

  Comment getComment(CommentId request) {
    final csilResp = transport.call('comment', 'GetComment', CsilCbor.encodeValue(request));
    return Comment.fromCborValue(CsilCbor.decode(csilResp));
  }

  Comment updateComment(Comment request) {
    final csilResp = transport.call('comment', 'UpdateComment', request.toCbor());
    return Comment.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteComment(CommentId request) {
    final csilResp = transport.call('comment', 'DeleteComment', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Comment> listComments(CommentListRequest request) {
    final csilResp = transport.call('comment', 'ListComments', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Comment.fromCborValue(csilE)).cast<Comment>().toList();
  }

}

/// A typed, transport-agnostic client for the NotificationService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class NotificationClient {
  final CsilTransport transport;
  const NotificationClient(this.transport);

  List<Notification> listNotifications(NotificationListRequest request) {
    final csilResp = transport.call('notification', 'ListNotifications', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Notification.fromCborValue(csilE)).cast<Notification>().toList();
  }

  NotificationUnreadCount unreadCount(HouseId request) {
    final csilResp = transport.call('notification', 'UnreadCount', CsilCbor.encodeValue(request));
    return NotificationUnreadCount.fromCborValue(CsilCbor.decode(csilResp));
  }

  Notification markRead(NotificationId request) {
    final csilResp = transport.call('notification', 'MarkRead', CsilCbor.encodeValue(request));
    return Notification.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse markAllRead(HouseId request) {
    final csilResp = transport.call('notification', 'MarkAllRead', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the ShareService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class ShareClient {
  final CsilTransport transport;
  const ShareClient(this.transport);

  Share createShare(Share request) {
    final csilResp = transport.call('share', 'CreateShare', request.toCbor());
    return Share.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse deleteShare(ShareId request) {
    final csilResp = transport.call('share', 'DeleteShare', CsilCbor.encodeValue(request));
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  List<Share> listSharesByResource(ResourceRef request) {
    final csilResp = transport.call('share', 'ListSharesByResource', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => Share.fromCborValue(csilE)).cast<Share>().toList();
  }

  Share checkAccess(ShareAccessRequest request) {
    final csilResp = transport.call('share', 'CheckAccess', request.toCbor());
    return Share.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the MemberAuditService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class MemberAuditClient {
  final CsilTransport transport;
  const MemberAuditClient(this.transport);

  List<MemberAudit> listAuditsForMember(MemberScopedListRequest request) {
    final csilResp = transport.call('memberaudit', 'ListAuditsForMember', request.toCbor());
    return (CsilCbor.decode(csilResp) as List).map((csilE) => MemberAudit.fromCborValue(csilE)).cast<MemberAudit>().toList();
  }

}

/// A typed, transport-agnostic client for the SettingsService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class SettingsClient {
  final CsilTransport transport;
  const SettingsClient(this.transport);

  EffectiveSettings getSettings(HouseId request) {
    final csilResp = transport.call('settings', 'GetSettings', CsilCbor.encodeValue(request));
    return EffectiveSettings.fromCborValue(CsilCbor.decode(csilResp));
  }

  EffectiveSettings updateSettings(UpdateSettingsRequest request) {
    final csilResp = transport.call('settings', 'UpdateSettings', request.toCbor());
    return EffectiveSettings.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the BugService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class BugClient {
  final CsilTransport transport;
  const BugClient(this.transport);

  Task reportBug(BugReportRequest request) {
    final csilResp = transport.call('bug', 'ReportBug', request.toCbor());
    return Task.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the AuditService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class AuditClient {
  final CsilTransport transport;
  const AuditClient(this.transport);

  AuditPage queryAudit(AuditQuery request) {
    final csilResp = transport.call('audit', 'QueryAudit', request.toCbor());
    return AuditPage.fromCborValue(CsilCbor.decode(csilResp));
  }

}

/// A typed, transport-agnostic client for the TrashService service. The client owns
/// (de)serialization; the carrier only moves bytes.
final class TrashClient {
  final CsilTransport transport;
  const TrashClient(this.transport);

  TrashPage listTrash(HouseScopedListRequest request) {
    final csilResp = transport.call('trash', 'ListTrash', request.toCbor());
    return TrashPage.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse restore(RestoreRequest request) {
    final csilResp = transport.call('trash', 'Restore', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

  EmptyResponse purge(PurgeRequest request) {
    final csilResp = transport.call('trash', 'Purge', request.toCbor());
    return EmptyResponse.fromCborValue(CsilCbor.decode(csilResp));
  }

}

