// The self-contained canonical CSIL CBOR codec.
//
// Code generated by csilgen; DO NOT EDIT.

import 'dart:convert';
import 'dart:typed_data';

/// A minimal canonical-CBOR (RFC 8949 subset) encoder/decoder over the dynamic
/// value tree the generated records map to. Scalars, bytes (major type 2),
/// timestamps (DateTime -> tag 0), lists, and maps are supported; the generated
/// records call this behind their toCbor/fromCbor.
class CsilCbor {
  static Uint8List encodeValue(Object? value) {
    final b = BytesBuilder();
    _enc(b, value);
    return b.toBytes();
  }

  static void _head(BytesBuilder b, int major, int n) {
    final mt = major << 5;
    if (n < 24) {
      b.addByte(mt | n);
    } else if (n < 0x100) {
      b.addByte(mt | 24);
      b.addByte(n);
    } else if (n < 0x10000) {
      b.addByte(mt | 25);
      b.addByte((n >> 8) & 0xff);
      b.addByte(n & 0xff);
    } else if (n < 0x100000000) {
      b.addByte(mt | 26);
      for (var i = 3; i >= 0; i--) {
        b.addByte((n >> (i * 8)) & 0xff);
      }
    } else {
      b.addByte(mt | 27);
      for (var i = 7; i >= 0; i--) {
        b.addByte((n >> (i * 8)) & 0xff);
      }
    }
  }

  static void _enc(BytesBuilder b, Object? v) {
    if (v == null) {
      b.addByte(0xf6);
    } else if (v is bool) {
      b.addByte(v ? 0xf5 : 0xf4);
    } else if (v is int) {
      if (v >= 0) {
        _head(b, 0, v);
      } else {
        _head(b, 1, -1 - v);
      }
    } else if (v is double) {
      b.addByte(0xfb);
      final bd = ByteData(8)..setFloat64(0, v, Endian.big);
      b.add(bd.buffer.asUint8List());
    } else if (v is String) {
      final u = utf8.encode(v);
      _head(b, 3, u.length);
      b.add(u);
    } else if (v is Uint8List) {
      _head(b, 2, v.length);
      b.add(v);
    } else if (v is DateTime) {
      b.addByte(0xc0);
      // Canonical RFC3339 (tag 0): Dart's toIso8601String always emits a
      // fractional-seconds part (.000); the wire form omits it when it is zero, so
      // strip an all-zero fraction to match the other languages byte-for-byte.
      final iso = v.toUtc().toIso8601String().replaceFirst(
        RegExp(r'\.0+Z$'),
        'Z',
      );
      final u = utf8.encode(iso);
      _head(b, 3, u.length);
      b.add(u);
    } else if (v is List) {
      _head(b, 4, v.length);
      for (final e in v) {
        _enc(b, e);
      }
    } else if (v is Map) {
      _head(b, 5, v.length);
      v.forEach((k, val) {
        _enc(b, k);
        _enc(b, val);
      });
    } else {
      throw ArgumentError('CsilCbor: cannot encode ${v.runtimeType}');
    }
  }

  static Object? decode(List<int> bytes) {
    final b = Uint8List.fromList(bytes);
    final r = _dec(b, 0, 0);
    if (r.next != b.length) {
      throw ArgumentError('CsilCbor: trailing bytes');
    }
    return r.value;
  }

  static T expectLiteral<T>(Object? actual, Object? expected, T value) {
    if (!_valueEquals(actual, expected)) {
      throw ArgumentError('CsilCbor: literal mismatch');
    }
    return value;
  }

  /// Validate that a decoded closed-set (all-literal choice) value is one of
  /// its declared members, returning it cast to `T`. The wire carries the bare
  /// literal for this shape (it is its own discriminant), so decode has no
  /// index to dispatch on the way a tagged-sum union does — membership is the
  /// only check available.
  static T expectOneOf<T>(Object? actual, List<T> allowed) {
    for (final a in allowed) {
      if (_valueEquals(actual, a)) return a;
    }
    throw ArgumentError('CsilCbor: value not a member of the closed set');
  }

  static bool _valueEquals(Object? a, Object? b) {
    if (a is Uint8List && b is Uint8List) {
      if (a.length != b.length) return false;
      for (var i = 0; i < a.length; i++) {
        if (a[i] != b[i]) return false;
      }
      return true;
    }
    if (a is List && b is List) {
      if (a.length != b.length) return false;
      for (var i = 0; i < a.length; i++) {
        if (!_valueEquals(a[i], b[i])) return false;
      }
      return true;
    }
    return a == b;
  }

  static _CsilRead _readArg(Uint8List b, int pos, int low) {
    if (low < 24) return _CsilRead(low, pos + 1);
    final width = low == 24 ? 1 : low == 25 ? 2 : low == 26 ? 4 : low == 27 ? 8 : 0;
    if (width == 0 || pos >= b.length || b.length - pos - 1 < width) {
      throw ArgumentError('CsilCbor: truncated argument');
    }
    if (low == 24) return _CsilRead(b[pos + 1], pos + 2);
    if (low == 25) return _CsilRead((b[pos + 1] << 8) | b[pos + 2], pos + 3);
    if (low == 26) {
      var v = 0;
      for (var i = 1; i <= 4; i++) {
        v = (v << 8) | b[pos + i];
      }
      return _CsilRead(v, pos + 5);
    }
    if (low == 27) {
      var v = 0;
      for (var i = 1; i <= 8; i++) {
        v = (v << 8) | b[pos + i];
      }
      return _CsilRead(v, pos + 9);
    }
    throw ArgumentError('CsilCbor: bad head');
  }

  static _CsilDecoded _dec(Uint8List b, int pos, int depth) {
    if (depth > 64) throw ArgumentError('CsilCbor: nesting limit exceeded');
    if (pos >= b.length) throw ArgumentError('CsilCbor: unexpected end of input');
    final ib = b[pos];
    final major = ib >> 5;
    final low = ib & 0x1f;
    if (major == 7) {
      if (low == 20) return _CsilDecoded(false, pos + 1);
      if (low == 21) return _CsilDecoded(true, pos + 1);
      if (low == 22 || low == 23) return _CsilDecoded(null, pos + 1);
      if (low == 26) {
        if (b.length - pos < 5) throw ArgumentError('CsilCbor: truncated float');
        final bd = ByteData.sublistView(b, pos + 1, pos + 5);
        return _CsilDecoded(bd.getFloat32(0, Endian.big), pos + 5);
      }
      if (low == 27) {
        if (b.length - pos < 9) throw ArgumentError('CsilCbor: truncated float');
        final bd = ByteData.sublistView(b, pos + 1, pos + 9);
        return _CsilDecoded(bd.getFloat64(0, Endian.big), pos + 9);
      }
      throw ArgumentError('CsilCbor: unsupported simple value');
    }
    final a = _readArg(b, pos, low);
    final arg = a.value;
    final p = a.next;
    switch (major) {
      case 0:
        return _CsilDecoded(arg, p);
      case 1:
        return _CsilDecoded(-1 - arg, p);
      case 2:
        if (arg > b.length - p) throw ArgumentError('CsilCbor: truncated byte string');
        return _CsilDecoded(Uint8List.sublistView(b, p, p + arg), p + arg);
      case 3:
        if (arg > b.length - p) throw ArgumentError('CsilCbor: truncated text string');
        return _CsilDecoded(utf8.decode(b.sublist(p, p + arg)), p + arg);
      case 4:
        if (arg > b.length - p) throw ArgumentError('CsilCbor: array length exceeds remaining input');
        final list = <Object?>[];
        var off4 = p;
        for (var i = 0; i < arg; i++) {
          final d = _dec(b, off4, depth + 1);
          list.add(d.value);
          off4 = d.next;
        }
        return _CsilDecoded(list, off4);
      case 5:
        if (arg > b.length - p) throw ArgumentError('CsilCbor: map length exceeds remaining input');
        final map = <Object?, Object?>{};
        var off5 = p;
        for (var i = 0; i < arg; i++) {
          final k = _dec(b, off5, depth + 1);
          final v = _dec(b, k.next, depth + 1);
          map[k.value] = v.value;
          off5 = v.next;
        }
        return _CsilDecoded(map, off5);
      case 6:
        final inner = _dec(b, p, depth + 1);
        if (arg == 0 && inner.value is String) {
          return _CsilDecoded(
            DateTime.parse(inner.value as String).toUtc(),
            inner.next,
          );
        }
        return _CsilDecoded(inner.value, inner.next);
      default:
        throw ArgumentError('CsilCbor: unsupported major $major');
    }
  }
}

class _CsilRead {
  final int value;
  final int next;
  const _CsilRead(this.value, this.next);
}

class _CsilDecoded {
  final Object? value;
  final int next;
  const _CsilDecoded(this.value, this.next);
}
