// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-typesonly

export type HouseID = string;

export type MemberID = string;

export type RoleID = string;

export type SkillID = string;

export type GroupID = string;

export type ProjectID = string;

export type EventID = string;

export type TaskID = string;

export type CommentID = string;

export type ShareID = string;

export type TrustedDomainID = string;

export type MemberAuditID = string;

export type MilestoneID = string;

export type Timestamp = string;

export type TaskStatus = unknown | unknown | unknown | unknown;

export type TargetType = unknown | unknown;

export type AccessLevel = unknown;

export type ResourceType = unknown | unknown | unknown;

export type ProjectStatus = unknown | unknown;

export type RecurrenceFreq = unknown | unknown | unknown | unknown | unknown | unknown;

export type MilestoneState = unknown | unknown | unknown;

export interface House {
  houseId: HouseID;
  name: string;
  description?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Member {
  memberId: MemberID;
  houseId: HouseID;
  linkkeysDomain: string;
  linkkeysUserId: string;
  displayName?: string;
  cachedPublicKey?: Uint8Array;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  lastSeenAt?: Timestamp;
}

export interface TrustedDomain {
  trustedDomainId: TrustedDomainID;
  houseId: HouseID;
  domain: string;
  createdAt: Timestamp;
}

export interface Role {
  roleId: RoleID;
  houseId: HouseID;
  name: string;
  description?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface MemberRole {
  memberId: MemberID;
  roleId: RoleID;
  createdAt: Timestamp;
}

export interface MemberAudit {
  auditId: MemberAuditID;
  houseId: HouseID;
  subjectMemberId: MemberID;
  actorMemberId?: MemberID;
  action: string;
  targetType?: string;
  targetId?: string;
  detail?: string;
  createdAt: Timestamp;
}

export interface Skill {
  skillId: SkillID;
  houseId: HouseID;
  name: string;
  description?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface MemberSkill {
  memberId: MemberID;
  skillId: SkillID;
  createdAt: Timestamp;
}

export interface GroupSkill {
  groupId: GroupID;
  skillId: SkillID;
  createdAt: Timestamp;
}

export interface Group {
  groupId: GroupID;
  houseId: HouseID;
  name: string;
  description?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface GroupMember {
  groupId: GroupID;
  memberId: MemberID;
  createdAt: Timestamp;
}

export interface Project {
  projectId: ProjectID;
  houseId: HouseID;
  name: string;
  description?: string;
  category?: string;
  status?: ProjectStatus;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface ProjectTask {
  projectId: ProjectID;
  taskId: TaskID;
  position: number;
  createdAt: Timestamp;
}

export interface ProjectMember {
  projectId: ProjectID;
  memberId: MemberID;
  createdAt: Timestamp;
}

export interface ProjectOwner {
  projectId: ProjectID;
  memberId: MemberID;
  createdAt: Timestamp;
}

export interface Milestone {
  milestoneId: MilestoneID;
  projectId: ProjectID;
  label: string;
  whenLabel: string;
  state: MilestoneState;
  position: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Event {
  eventId: EventID;
  houseId: HouseID;
  ownerMemberId: MemberID;
  title: string;
  description?: string;
  location?: string;
  startsAt?: Timestamp;
  endsAt?: Timestamp;
  allDay?: boolean;
  recurrenceFreq?: RecurrenceFreq;
  recurrenceInterval?: number;
  recurrenceByWeekday?: number[];
  recurrenceBySetpos?: number;
  nextRecurrenceAt?: Timestamp;
  recurrenceRootEventId?: EventID;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Task {
  taskId: TaskID;
  houseId: HouseID;
  ownerMemberId: MemberID;
  assignees?: MemberID[];
  assignedToSkillId?: SkillID;
  parentTaskId?: TaskID;
  title: string;
  description?: string;
  status?: TaskStatus;
  dueAt?: Timestamp;
  tag?: string;
  estimateMinutes?: number;
  recurrenceFreq?: RecurrenceFreq;
  recurrenceInterval?: number;
  recurrenceByWeekday?: number[];
  recurrenceBySetpos?: number;
  nextRecurrenceAt?: Timestamp;
  recurrenceRootTaskId?: TaskID;
  deletedAt?: Timestamp;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Comment {
  commentId: CommentID;
  houseId: HouseID;
  memberId: MemberID;
  targetType: TargetType;
  targetId: string;
  body: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Share {
  shareId: ShareID;
  houseId: HouseID;
  sharedBy: MemberID;
  linkkeysDomain: string;
  linkkeysUserId: string;
  resourceType: ResourceType;
  resourceId: string;
  accessLevel?: AccessLevel;
  createdAt: Timestamp;
  expiresAt?: Timestamp;
}

export interface HouseSummary {
  houseId: HouseID;
  name: string;
  memberId: MemberID;
  roles: string[];
}

export interface HouseRoles {
  house: HouseID;
  member: MemberID;
  roles: string[];
}

export interface Identity {
  domain: string;
  userId: string;
  displayName?: string;
  houses: HouseRoles[];
  iat: number;
  exp: number;
}

export interface LoginRequest {
  signedAssertion: string;
}

export interface CompleteRequest {
  encryptedToken: string;
}

export interface LoginResponse {
  token: string;
  domain: string;
  userId: string;
  displayName?: string;
  expiresAt: Timestamp;
}

export interface DevUserEntry {
  memberId: MemberID;
  houseId: HouseID;
  houseName: string;
  displayName?: string;
  linkkeysDomain?: string;
  linkkeysUserId?: string;
  roles: string[];
}

export interface DevUsersResponse {
  users: DevUserEntry[];
}

export interface DevLoginRequest {
  memberId: MemberID;
}

export interface MeResponse {
  domain: string;
  userId: string;
  displayName?: string;
  expiresAt: Timestamp;
  houses: HouseSummary[];
}

export interface EmptyRequest {
}

export interface EmptyResponse {
}

export interface BoolResponse {
  value: boolean;
}

export interface HouseListRequest {
  limit?: number;
  offset?: number;
}

export interface HouseScopedListRequest {
  houseId: HouseID;
  limit?: number;
  offset?: number;
}

export interface MemberScopedListRequest {
  houseId: HouseID;
  memberId: MemberID;
  limit?: number;
  offset?: number;
}

export interface ProjectScopedListRequest {
  houseId: HouseID;
  projectId: ProjectID;
  limit?: number;
  offset?: number;
}

export interface CommentListRequest {
  targetType: TargetType;
  targetId: string;
  limit?: number;
  offset?: number;
}

export interface ShareAccessRequest {
  linkkeysDomain: string;
  linkkeysUserId: string;
  resourceType: ResourceType;
  resourceId: string;
}

export interface ResourceRef {
  resourceType: ResourceType;
  resourceId: string;
}

export interface MemberRoleRef {
  memberId: MemberID;
  roleId: RoleID;
}

export interface MemberSkillRef {
  memberId: MemberID;
  skillId: SkillID;
}

export interface GroupSkillRef {
  groupId: GroupID;
  skillId: SkillID;
}

export interface GroupMemberRef {
  groupId: GroupID;
  memberId: MemberID;
}

export interface ProjectTaskRef {
  projectId: ProjectID;
  taskId: TaskID;
}

export interface ProjectTaskOrderRequest {
  projectId: ProjectID;
  taskId: TaskID;
  position: number;
}

export interface ProjectMemberRef {
  projectId: ProjectID;
  memberId: MemberID;
}

export interface ProjectOwnerRef {
  projectId: ProjectID;
  memberId: MemberID;
}

export interface EffectiveSettings {
  bugReportsEnabled?: boolean;
  bugReportsProjectId?: ProjectID;
}

export interface UpdateSettingsRequest {
  houseId: HouseID;
  settings: EffectiveSettings;
}

export interface BugReportRequest {
  houseId: HouseID;
  title: string;
  description?: string;
}

export interface ServiceError {
  code: number;
  message: string;
}

