# frozen_string_literal: true

# Code generated by csilgen; DO NOT EDIT.

Gem::Specification.new do |spec|
  spec.name = "longhouse_client"
  spec.version = "0.13.0"
  spec.summary = "CSIL-generated Ruby package longhouse_client."
  spec.authors = ["csilgen"]
  spec.license = "Apache-2.0"
  spec.required_ruby_version = ">= 3.2"
  spec.files = Dir["lib/**/*.rb"]
  spec.require_paths = ["lib"]
end
