# Generated service handlers from CSIL specification
# Do not edit this file manually

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Union
import json
from .types import *


from abc import ABC, abstractmethod

class ServiceError(Exception):
    """Transport-level error thrown by service routers and handlers."""
    def __init__(self, code: int, message: str):
        self.code = code
        self.message = message
        super().__init__(f"service error {code}: {message}")

class AuthServiceHandlers(ABC):
    """Server-side handlers for AuthService service operations."""

    @abstractmethod
    def login(self, req: LoginRequest, ctx: dict) -> Union[LoginResponse, ServiceError]:
        """login"""
        ...

    @abstractmethod
    def complete(self, req: CompleteRequest, ctx: dict) -> Union[LoginResponse, ServiceError]:
        """complete"""
        ...

    @abstractmethod
    def refresh(self, req: EmptyRequest, ctx: dict) -> Union[LoginResponse, ServiceError]:
        """refresh"""
        ...

    @abstractmethod
    def logout(self, req: EmptyRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """logout"""
        ...

    @abstractmethod
    def me(self, req: EmptyRequest, ctx: dict) -> Union[MeResponse, ServiceError]:
        """me"""
        ...

class DevAuthServiceHandlers(ABC):
    """Server-side handlers for DevAuthService service operations."""

    @abstractmethod
    def list_dev_users(self, req: EmptyRequest, ctx: dict) -> Union[DevUsersResponse, ServiceError]:
        """list-dev-users"""
        ...

    @abstractmethod
    def dev_login(self, req: DevLoginRequest, ctx: dict) -> Union[LoginResponse, ServiceError]:
        """dev-login"""
        ...

class HouseServiceHandlers(ABC):
    """Server-side handlers for HouseService service operations."""

    @abstractmethod
    def create_house(self, req: House, ctx: dict) -> Union[House, ServiceError]:
        """create-house"""
        ...

    @abstractmethod
    def get_house(self, req: HouseId, ctx: dict) -> Union[House, ServiceError]:
        """get-house"""
        ...

    @abstractmethod
    def update_house(self, req: House, ctx: dict) -> Union[House, ServiceError]:
        """update-house"""
        ...

    @abstractmethod
    def delete_house(self, req: HouseId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-house"""
        ...

    @abstractmethod
    def list_houses(self, req: HouseListRequest, ctx: dict) -> Union[List[House], ServiceError]:
        """list-houses"""
        ...

class MemberServiceHandlers(ABC):
    """Server-side handlers for MemberService service operations."""

    @abstractmethod
    def create_member(self, req: Member, ctx: dict) -> Union[Member, ServiceError]:
        """create-member"""
        ...

    @abstractmethod
    def get_member(self, req: MemberId, ctx: dict) -> Union[Member, ServiceError]:
        """get-member"""
        ...

    @abstractmethod
    def get_member_by_identity(self, req: Member, ctx: dict) -> Union[Member, ServiceError]:
        """get-member-by-identity"""
        ...

    @abstractmethod
    def update_member(self, req: Member, ctx: dict) -> Union[Member, ServiceError]:
        """update-member"""
        ...

    @abstractmethod
    def deactivate_member(self, req: MemberId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """deactivate-member"""
        ...

    @abstractmethod
    def reactivate_member(self, req: MemberId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """reactivate-member"""
        ...

    @abstractmethod
    def list_members(self, req: HouseScopedListRequest, ctx: dict) -> Union[List[Member], ServiceError]:
        """list-members"""
        ...

class TrustedDomainServiceHandlers(ABC):
    """Server-side handlers for TrustedDomainService service operations."""

    @abstractmethod
    def add_trusted_domain(self, req: TrustedDomain, ctx: dict) -> Union[TrustedDomain, ServiceError]:
        """add-trusted-domain"""
        ...

    @abstractmethod
    def remove_trusted_domain(self, req: TrustedDomainId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-trusted-domain"""
        ...

    @abstractmethod
    def list_trusted_domains(self, req: HouseId, ctx: dict) -> Union[List[TrustedDomain], ServiceError]:
        """list-trusted-domains"""
        ...

    @abstractmethod
    def is_domain_trusted(self, req: TrustedDomain, ctx: dict) -> Union[BoolResponse, ServiceError]:
        """is-domain-trusted"""
        ...

class RoleServiceHandlers(ABC):
    """Server-side handlers for RoleService service operations."""

    @abstractmethod
    def create_role(self, req: Role, ctx: dict) -> Union[Role, ServiceError]:
        """create-role"""
        ...

    @abstractmethod
    def update_role(self, req: Role, ctx: dict) -> Union[Role, ServiceError]:
        """update-role"""
        ...

    @abstractmethod
    def delete_role(self, req: RoleId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-role"""
        ...

    @abstractmethod
    def list_roles(self, req: HouseScopedListRequest, ctx: dict) -> Union[List[Role], ServiceError]:
        """list-roles"""
        ...

    @abstractmethod
    def grant_role(self, req: MemberRoleRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """grant-role"""
        ...

    @abstractmethod
    def revoke_role(self, req: MemberRoleRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """revoke-role"""
        ...

    @abstractmethod
    def list_member_roles(self, req: MemberScopedListRequest, ctx: dict) -> Union[List[Role], ServiceError]:
        """list-member-roles"""
        ...

class SkillServiceHandlers(ABC):
    """Server-side handlers for SkillService service operations."""

    @abstractmethod
    def create_skill(self, req: Skill, ctx: dict) -> Union[Skill, ServiceError]:
        """create-skill"""
        ...

    @abstractmethod
    def update_skill(self, req: Skill, ctx: dict) -> Union[Skill, ServiceError]:
        """update-skill"""
        ...

    @abstractmethod
    def delete_skill(self, req: SkillId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-skill"""
        ...

    @abstractmethod
    def list_skills(self, req: HouseScopedListRequest, ctx: dict) -> Union[List[Skill], ServiceError]:
        """list-skills"""
        ...

    @abstractmethod
    def add_member_skill(self, req: MemberSkillRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-member-skill"""
        ...

    @abstractmethod
    def remove_member_skill(self, req: MemberSkillRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-member-skill"""
        ...

    @abstractmethod
    def list_member_skills(self, req: MemberScopedListRequest, ctx: dict) -> Union[List[Skill], ServiceError]:
        """list-member-skills"""
        ...

    @abstractmethod
    def add_group_skill(self, req: GroupSkillRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-group-skill"""
        ...

    @abstractmethod
    def remove_group_skill(self, req: GroupSkillRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-group-skill"""
        ...

    @abstractmethod
    def list_group_skills(self, req: GroupId, ctx: dict) -> Union[List[Skill], ServiceError]:
        """list-group-skills"""
        ...

class GroupServiceHandlers(ABC):
    """Server-side handlers for GroupService service operations."""

    @abstractmethod
    def create_group(self, req: Group, ctx: dict) -> Union[Group, ServiceError]:
        """create-group"""
        ...

    @abstractmethod
    def update_group(self, req: Group, ctx: dict) -> Union[Group, ServiceError]:
        """update-group"""
        ...

    @abstractmethod
    def delete_group(self, req: GroupId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-group"""
        ...

    @abstractmethod
    def list_groups(self, req: HouseScopedListRequest, ctx: dict) -> Union[List[Group], ServiceError]:
        """list-groups"""
        ...

    @abstractmethod
    def add_group_member(self, req: GroupMemberRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-group-member"""
        ...

    @abstractmethod
    def remove_group_member(self, req: GroupMemberRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-group-member"""
        ...

    @abstractmethod
    def list_group_members(self, req: MemberScopedListRequest, ctx: dict) -> Union[List[Member], ServiceError]:
        """list-group-members"""
        ...

class ProjectServiceHandlers(ABC):
    """Server-side handlers for ProjectService service operations."""

    @abstractmethod
    def create_project(self, req: Project, ctx: dict) -> Union[Project, ServiceError]:
        """create-project"""
        ...

    @abstractmethod
    def get_project(self, req: ProjectId, ctx: dict) -> Union[Project, ServiceError]:
        """get-project"""
        ...

    @abstractmethod
    def update_project(self, req: Project, ctx: dict) -> Union[Project, ServiceError]:
        """update-project"""
        ...

    @abstractmethod
    def delete_project(self, req: ProjectId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-project"""
        ...

    @abstractmethod
    def list_projects(self, req: HouseScopedListRequest, ctx: dict) -> Union[ProjectList, ServiceError]:
        """list-projects"""
        ...

    @abstractmethod
    def list_project_tasks(self, req: ProjectScopedListRequest, ctx: dict) -> Union[TaskList, ServiceError]:
        """list-project-tasks"""
        ...

    @abstractmethod
    def add_project_task(self, req: ProjectTaskOrderRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-project-task"""
        ...

    @abstractmethod
    def remove_project_task(self, req: ProjectTaskRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-project-task"""
        ...

    @abstractmethod
    def set_project_task_position(self, req: ProjectTaskOrderRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """set-project-task-position"""
        ...

    @abstractmethod
    def list_project_members(self, req: ProjectId, ctx: dict) -> Union[List[Member], ServiceError]:
        """list-project-members"""
        ...

    @abstractmethod
    def add_project_member(self, req: ProjectMemberRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-project-member"""
        ...

    @abstractmethod
    def remove_project_member(self, req: ProjectMemberRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-project-member"""
        ...

    @abstractmethod
    def list_project_owners(self, req: ProjectId, ctx: dict) -> Union[List[Member], ServiceError]:
        """list-project-owners"""
        ...

    @abstractmethod
    def add_project_owner(self, req: ProjectOwnerRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-project-owner"""
        ...

    @abstractmethod
    def remove_project_owner(self, req: ProjectOwnerRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-project-owner"""
        ...

    @abstractmethod
    def list_milestones(self, req: ProjectId, ctx: dict) -> Union[List[Milestone], ServiceError]:
        """list-milestones"""
        ...

    @abstractmethod
    def create_milestone(self, req: Milestone, ctx: dict) -> Union[Milestone, ServiceError]:
        """create-milestone"""
        ...

    @abstractmethod
    def update_milestone(self, req: Milestone, ctx: dict) -> Union[Milestone, ServiceError]:
        """update-milestone"""
        ...

    @abstractmethod
    def delete_milestone(self, req: MilestoneId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-milestone"""
        ...

    @abstractmethod
    def set_project_visibility(self, req: SetProjectVisibilityRequest, ctx: dict) -> Union[Project, ServiceError]:
        """set-project-visibility"""
        ...

    @abstractmethod
    def list_project_grants(self, req: ProjectId, ctx: dict) -> Union[List[Grant], ServiceError]:
        """list-project-grants"""
        ...

    @abstractmethod
    def put_project_grant(self, req: PutProjectGrantRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """put-project-grant"""
        ...

    @abstractmethod
    def delete_project_grant(self, req: ProjectGrantRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-project-grant"""
        ...

class EventServiceHandlers(ABC):
    """Server-side handlers for EventService service operations."""

    @abstractmethod
    def create_event(self, req: Event, ctx: dict) -> Union[Event, ServiceError]:
        """create-event"""
        ...

    @abstractmethod
    def get_event(self, req: EventId, ctx: dict) -> Union[Event, ServiceError]:
        """get-event"""
        ...

    @abstractmethod
    def update_event(self, req: Event, ctx: dict) -> Union[Event, ServiceError]:
        """update-event"""
        ...

    @abstractmethod
    def delete_event(self, req: EventId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-event"""
        ...

    @abstractmethod
    def delete_event_and_future(self, req: EventId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-event-and-future"""
        ...

    @abstractmethod
    def list_events(self, req: HouseScopedListRequest, ctx: dict) -> Union[List[Event], ServiceError]:
        """list-events"""
        ...

class TaskServiceHandlers(ABC):
    """Server-side handlers for TaskService service operations."""

    @abstractmethod
    def create_task(self, req: Task, ctx: dict) -> Union[Task, ServiceError]:
        """create-task"""
        ...

    @abstractmethod
    def get_task(self, req: TaskId, ctx: dict) -> Union[Task, ServiceError]:
        """get-task"""
        ...

    @abstractmethod
    def update_task(self, req: Task, ctx: dict) -> Union[Task, ServiceError]:
        """update-task"""
        ...

    @abstractmethod
    def delete_task(self, req: TaskId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-task"""
        ...

    @abstractmethod
    def list_tasks(self, req: HouseScopedListRequest, ctx: dict) -> Union[TaskList, ServiceError]:
        """list-tasks"""
        ...

    @abstractmethod
    def set_task_visibility(self, req: SetTaskVisibilityRequest, ctx: dict) -> Union[Task, ServiceError]:
        """set-task-visibility"""
        ...

    @abstractmethod
    def list_task_grants(self, req: TaskId, ctx: dict) -> Union[List[Grant], ServiceError]:
        """list-task-grants"""
        ...

    @abstractmethod
    def put_task_grant(self, req: PutTaskGrantRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """put-task-grant"""
        ...

    @abstractmethod
    def delete_task_grant(self, req: TaskGrantRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-task-grant"""
        ...

class DependencyServiceHandlers(ABC):
    """Server-side handlers for DependencyService service operations."""

    @abstractmethod
    def add_dependency(self, req: DependencyRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """add-dependency"""
        ...

    @abstractmethod
    def remove_dependency(self, req: DependencyRef, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """remove-dependency"""
        ...

    @abstractmethod
    def get_dependencies(self, req: DependencyTarget, ctx: dict) -> Union[DependencyGraph, ServiceError]:
        """get-dependencies"""
        ...

class CommentServiceHandlers(ABC):
    """Server-side handlers for CommentService service operations."""

    @abstractmethod
    def create_comment(self, req: Comment, ctx: dict) -> Union[Comment, ServiceError]:
        """create-comment"""
        ...

    @abstractmethod
    def get_comment(self, req: CommentId, ctx: dict) -> Union[Comment, ServiceError]:
        """get-comment"""
        ...

    @abstractmethod
    def update_comment(self, req: Comment, ctx: dict) -> Union[Comment, ServiceError]:
        """update-comment"""
        ...

    @abstractmethod
    def delete_comment(self, req: CommentId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-comment"""
        ...

    @abstractmethod
    def list_comments(self, req: CommentListRequest, ctx: dict) -> Union[List[Comment], ServiceError]:
        """list-comments"""
        ...

class NotificationServiceHandlers(ABC):
    """Server-side handlers for NotificationService service operations."""

    @abstractmethod
    def list_notifications(self, req: NotificationListRequest, ctx: dict) -> Union[List[Notification], ServiceError]:
        """list-notifications"""
        ...

    @abstractmethod
    def unread_count(self, req: HouseId, ctx: dict) -> Union[NotificationUnreadCount, ServiceError]:
        """unread-count"""
        ...

    @abstractmethod
    def mark_read(self, req: NotificationId, ctx: dict) -> Union[Notification, ServiceError]:
        """mark-read"""
        ...

    @abstractmethod
    def mark_all_read(self, req: HouseId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """mark-all-read"""
        ...

class ShareServiceHandlers(ABC):
    """Server-side handlers for ShareService service operations."""

    @abstractmethod
    def create_share(self, req: Share, ctx: dict) -> Union[Share, ServiceError]:
        """create-share"""
        ...

    @abstractmethod
    def delete_share(self, req: ShareId, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """delete-share"""
        ...

    @abstractmethod
    def list_shares_by_resource(self, req: ResourceRef, ctx: dict) -> Union[List[Share], ServiceError]:
        """list-shares-by-resource"""
        ...

    @abstractmethod
    def check_access(self, req: ShareAccessRequest, ctx: dict) -> Union[Share, ServiceError]:
        """check-access"""
        ...

class MemberAuditServiceHandlers(ABC):
    """Server-side handlers for MemberAuditService service operations."""

    @abstractmethod
    def list_audits_for_member(self, req: MemberScopedListRequest, ctx: dict) -> Union[List[MemberAudit], ServiceError]:
        """list-audits-for-member"""
        ...

class SettingsServiceHandlers(ABC):
    """Server-side handlers for SettingsService service operations."""

    @abstractmethod
    def get_settings(self, req: HouseId, ctx: dict) -> Union[EffectiveSettings, ServiceError]:
        """get-settings"""
        ...

    @abstractmethod
    def update_settings(self, req: UpdateSettingsRequest, ctx: dict) -> Union[EffectiveSettings, ServiceError]:
        """update-settings"""
        ...

class BugServiceHandlers(ABC):
    """Server-side handlers for BugService service operations."""

    @abstractmethod
    def report_bug(self, req: BugReportRequest, ctx: dict) -> Union[Task, ServiceError]:
        """report-bug"""
        ...

class AuditServiceHandlers(ABC):
    """Server-side handlers for AuditService service operations."""

    @abstractmethod
    def query_audit(self, req: AuditQuery, ctx: dict) -> Union[AuditPage, ServiceError]:
        """query-audit"""
        ...

class TrashServiceHandlers(ABC):
    """Server-side handlers for TrashService service operations."""

    @abstractmethod
    def list_trash(self, req: HouseScopedListRequest, ctx: dict) -> Union[TrashPage, ServiceError]:
        """list-trash"""
        ...

    @abstractmethod
    def restore(self, req: RestoreRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """restore"""
        ...

    @abstractmethod
    def purge(self, req: PurgeRequest, ctx: dict) -> Union[EmptyResponse, ServiceError]:
        """purge"""
        ...

