// swift-tools-version:5.9
// LonghouseClient 0.13.0 — generated by csilgen; DO NOT EDIT.
// SwiftPM derives a published version from the package's git tag, so the version
// above is informational only.
import PackageDescription

let package = Package(
name: "LonghouseClient",
products: [
.library(name: "LonghouseClient", targets: ["LonghouseClient"]),
],
targets: [
.target(name: "LonghouseClient"),
]
)
