// Generated CSIL value types.
// Code generated by csilgen; DO NOT EDIT.

/// TaskStatus is an enumeration.
pub const TaskStatus = enum {
    open,
    in_progress,
    done,
    cancelled,

    pub fn wire_name(self: TaskStatus) []const u8 {
        return switch (self) {
            .open => "open",
            .in_progress => "in_progress",
            .done => "done",
            .cancelled => "cancelled",
        };
    }
};

/// TargetType is an enumeration.
pub const TargetType = enum {
    event,
    task,
    project,

    pub fn wire_name(self: TargetType) []const u8 {
        return switch (self) {
            .event => "event",
            .task => "task",
            .project => "project",
        };
    }
};

/// AccessLevel is an enumeration.
pub const AccessLevel = enum {
    none,
    read,
    edit,
    full,

    pub fn wire_name(self: AccessLevel) []const u8 {
        return switch (self) {
            .none => "none",
            .read => "read",
            .edit => "edit",
            .full => "full",
        };
    }
};

/// GranteeType is an enumeration.
pub const GranteeType = enum {
    member,
    group,

    pub fn wire_name(self: GranteeType) []const u8 {
        return switch (self) {
            .member => "member",
            .group => "group",
        };
    }
};

/// ResourceType is an enumeration.
pub const ResourceType = enum {
    event,
    task,
    house,

    pub fn wire_name(self: ResourceType) []const u8 {
        return switch (self) {
            .event => "event",
            .task => "task",
            .house => "house",
        };
    }
};

/// ProjectStatus is an enumeration.
pub const ProjectStatus = enum {
    active,
    archived,

    pub fn wire_name(self: ProjectStatus) []const u8 {
        return switch (self) {
            .active => "active",
            .archived => "archived",
        };
    }
};

/// DependencyNodeType is an enumeration.
pub const DependencyNodeType = enum {
    task,
    project,

    pub fn wire_name(self: DependencyNodeType) []const u8 {
        return switch (self) {
            .task => "task",
            .project => "project",
        };
    }
};

/// RecurrenceFreq is an enumeration.
pub const RecurrenceFreq = enum {
    hourly,
    daily,
    weekly,
    monthly,
    quarterly,
    yearly,

    pub fn wire_name(self: RecurrenceFreq) []const u8 {
        return switch (self) {
            .hourly => "hourly",
            .daily => "daily",
            .weekly => "weekly",
            .monthly => "monthly",
            .quarterly => "quarterly",
            .yearly => "yearly",
        };
    }
};

/// MilestoneState is an enumeration.
pub const MilestoneState = enum {
    done,
    current,
    future,

    pub fn wire_name(self: MilestoneState) []const u8 {
        return switch (self) {
            .done => "done",
            .current => "current",
            .future => "future",
        };
    }
};

/// HouseID is a type alias.
pub const HouseID = []const u8;

/// MemberID is a type alias.
pub const MemberID = []const u8;

/// RoleID is a type alias.
pub const RoleID = []const u8;

/// SkillID is a type alias.
pub const SkillID = []const u8;

/// GroupID is a type alias.
pub const GroupID = []const u8;

/// ProjectID is a type alias.
pub const ProjectID = []const u8;

/// EventID is a type alias.
pub const EventID = []const u8;

/// TaskID is a type alias.
pub const TaskID = []const u8;

/// CommentID is a type alias.
pub const CommentID = []const u8;

/// ShareID is a type alias.
pub const ShareID = []const u8;

/// TrustedDomainID is a type alias.
pub const TrustedDomainID = []const u8;

/// MemberAuditID is a type alias.
pub const MemberAuditID = []const u8;

/// MilestoneID is a type alias.
pub const MilestoneID = []const u8;

/// NotificationID is a type alias.
pub const NotificationID = []const u8;

/// NotificationEventID is a type alias.
pub const NotificationEventID = []const u8;

/// Timestamp is a type alias.
pub const Timestamp = []const u8;

/// AuditID is a type alias.
pub const AuditID = []const u8;

/// Identity is a structured data type.
pub const Identity = struct {
    domain: []const u8,
    user_id: []const u8,
    display_name: ?[]const u8 = null,
    houses: []HouseRoles,
    iat: i64,
    exp: i64,
};

/// LoginRequest is a structured data type.
pub const LoginRequest = struct {
    signed_assertion: []const u8,
};

/// CompleteRequest is a structured data type.
pub const CompleteRequest = struct {
    encrypted_token: []const u8,
};

/// DevUsersResponse is a structured data type.
pub const DevUsersResponse = struct {
    users: []DevUserEntry,
};

/// EmptyRequest is a structured data type.
pub const EmptyRequest = struct {
};

/// EmptyResponse is a structured data type.
pub const EmptyResponse = struct {
};

/// BoolResponse is a structured data type.
pub const BoolResponse = struct {
    value: bool,
};

/// HouseListRequest is a structured data type.
pub const HouseListRequest = struct {
    limit: ?u64 = null,
    offset: ?u64 = null,
};

/// TaskList is a structured data type.
pub const TaskList = struct {
    tasks: []Task,
    hidden_count: u64,
};

/// ProjectList is a structured data type.
pub const ProjectList = struct {
    projects: []Project,
    hidden_count: u64,
};

/// NotificationUnreadCount is a structured data type.
pub const NotificationUnreadCount = struct {
    count: u64,
};

/// DependencyGraph is a structured data type.
pub const DependencyGraph = struct {
    dependencies: []DependencyNode,
    dependents: []DependencyNode,
};

/// EffectiveSettings is a structured data type.
pub const EffectiveSettings = struct {
    bug_reports_enabled: ?bool = null,
    bug_reports_project_id: ?ProjectID = null,
    default_project_visibility: ?AccessLevel = null,
};

/// ServiceError is a structured data type.
pub const ServiceError = struct {
    code: u64,
    message: []const u8,
};

/// AuditPage is a structured data type.
pub const AuditPage = struct {
    entries: []AuditEntry,
    next_cursor: ?[]const u8 = null,
};

/// TrashPage is a structured data type.
pub const TrashPage = struct {
    items: []TrashItem,
    next_cursor: ?[]const u8 = null,
};

/// House is a structured data type.
pub const House = struct {
    house_id: HouseID,
    name: []const u8,
    description: ?[]const u8 = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// Member is a structured data type.
pub const Member = struct {
    member_id: MemberID,
    house_id: HouseID,
    linkkeys_domain: []const u8,
    linkkeys_user_id: []const u8,
    display_name: ?[]const u8 = null,
    email: ?[]const u8 = null,
    avatar_url: ?[]const u8 = null,
    cached_public_key: ?[]const u8 = null,
    created_at: Timestamp,
    updated_at: Timestamp,
    last_seen_at: ?Timestamp = null,
    deactivated_at: ?Timestamp = null,
};

/// TrustedDomain is a structured data type.
pub const TrustedDomain = struct {
    trusted_domain_id: TrustedDomainID,
    house_id: HouseID,
    domain: []const u8,
    created_at: Timestamp,
};

/// Role is a structured data type.
pub const Role = struct {
    role_id: RoleID,
    house_id: HouseID,
    name: []const u8,
    description: ?[]const u8 = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// MemberRole is a structured data type.
pub const MemberRole = struct {
    member_id: MemberID,
    role_id: RoleID,
    created_at: Timestamp,
};

/// MemberAudit is a structured data type.
pub const MemberAudit = struct {
    audit_id: MemberAuditID,
    house_id: HouseID,
    subject_member_id: MemberID,
    actor_member_id: ?MemberID = null,
    action: []const u8,
    target_type: ?[]const u8 = null,
    target_id: ?[]const u8 = null,
    detail: ?[]const u8 = null,
    created_at: Timestamp,
};

/// Skill is a structured data type.
pub const Skill = struct {
    skill_id: SkillID,
    house_id: HouseID,
    name: []const u8,
    description: ?[]const u8 = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// MemberSkill is a structured data type.
pub const MemberSkill = struct {
    member_id: MemberID,
    skill_id: SkillID,
    created_at: Timestamp,
};

/// GroupSkill is a structured data type.
pub const GroupSkill = struct {
    group_id: GroupID,
    skill_id: SkillID,
    created_at: Timestamp,
};

/// Group is a structured data type.
pub const Group = struct {
    group_id: GroupID,
    house_id: HouseID,
    name: []const u8,
    description: ?[]const u8 = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// GroupMember is a structured data type.
pub const GroupMember = struct {
    group_id: GroupID,
    member_id: MemberID,
    created_at: Timestamp,
};

/// Project is a structured data type.
pub const Project = struct {
    project_id: ProjectID,
    house_id: HouseID,
    name: []const u8,
    description: ?[]const u8 = null,
    category: ?[]const u8 = null,
    status: ?ProjectStatus = null,
    visibility: ?AccessLevel = null,
    created_by_member_id: ?MemberID = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// ProjectTask is a structured data type.
pub const ProjectTask = struct {
    project_id: ProjectID,
    task_id: TaskID,
    position: i64,
    created_at: Timestamp,
};

/// ProjectMember is a structured data type.
pub const ProjectMember = struct {
    project_id: ProjectID,
    member_id: MemberID,
    created_at: Timestamp,
};

/// ProjectOwner is a structured data type.
pub const ProjectOwner = struct {
    project_id: ProjectID,
    member_id: MemberID,
    created_at: Timestamp,
};

/// Milestone is a structured data type.
pub const Milestone = struct {
    milestone_id: MilestoneID,
    project_id: ProjectID,
    label: []const u8,
    when_label: []const u8,
    state: MilestoneState,
    position: i64,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// Event is a structured data type.
pub const Event = struct {
    event_id: EventID,
    house_id: HouseID,
    owner_member_id: MemberID,
    title: []const u8,
    description: ?[]const u8 = null,
    location: ?[]const u8 = null,
    starts_at: ?Timestamp = null,
    ends_at: ?Timestamp = null,
    all_day: ?bool = null,
    recurrence_freq: ?RecurrenceFreq = null,
    recurrence_interval: ?i64 = null,
    recurrence_by_weekday: ?[]i64 = null,
    recurrence_by_setpos: ?i64 = null,
    next_recurrence_at: ?Timestamp = null,
    recurrence_root_event_id: ?EventID = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// Task is a structured data type.
pub const Task = struct {
    task_id: TaskID,
    house_id: HouseID,
    owner_member_id: MemberID,
    assignees: ?[]MemberID = null,
    assigned_to_skill_id: ?SkillID = null,
    parent_task_id: ?TaskID = null,
    visibility: ?AccessLevel = null,
    title: []const u8,
    description: ?[]const u8 = null,
    status: ?TaskStatus = null,
    due_at: ?Timestamp = null,
    tag: ?[]const u8 = null,
    estimate_minutes: ?u64 = null,
    recurrence_freq: ?RecurrenceFreq = null,
    recurrence_interval: ?i64 = null,
    recurrence_by_weekday: ?[]i64 = null,
    recurrence_by_setpos: ?i64 = null,
    next_recurrence_at: ?Timestamp = null,
    recurrence_root_task_id: ?TaskID = null,
    deleted_at: ?Timestamp = null,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// Comment is a structured data type.
pub const Comment = struct {
    comment_id: CommentID,
    house_id: HouseID,
    member_id: MemberID,
    target_type: TargetType,
    target_id: []const u8,
    body: []const u8,
    created_at: Timestamp,
    updated_at: Timestamp,
};

/// Share is a structured data type.
pub const Share = struct {
    share_id: ShareID,
    house_id: HouseID,
    shared_by: MemberID,
    linkkeys_domain: []const u8,
    linkkeys_user_id: []const u8,
    resource_type: ResourceType,
    resource_id: []const u8,
    access_level: ?AccessLevel = null,
    created_at: Timestamp,
    expires_at: ?Timestamp = null,
};

/// HouseSummary is a structured data type.
pub const HouseSummary = struct {
    house_id: HouseID,
    name: []const u8,
    member_id: MemberID,
    roles: [][]const u8,
};

/// HouseRoles is a structured data type.
pub const HouseRoles = struct {
    house: HouseID,
    member: MemberID,
    roles: [][]const u8,
};

/// LoginResponse is a structured data type.
pub const LoginResponse = struct {
    token: []const u8,
    domain: []const u8,
    user_id: []const u8,
    display_name: ?[]const u8 = null,
    expires_at: Timestamp,
};

/// DevUserEntry is a structured data type.
pub const DevUserEntry = struct {
    member_id: MemberID,
    house_id: HouseID,
    house_name: []const u8,
    display_name: ?[]const u8 = null,
    linkkeys_domain: ?[]const u8 = null,
    linkkeys_user_id: ?[]const u8 = null,
    roles: [][]const u8,
};

/// DevLoginRequest is a structured data type.
pub const DevLoginRequest = struct {
    member_id: MemberID,
};

/// MeResponse is a structured data type.
pub const MeResponse = struct {
    domain: []const u8,
    user_id: []const u8,
    display_name: ?[]const u8 = null,
    expires_at: Timestamp,
    houses: []HouseSummary,
};

/// HouseScopedListRequest is a structured data type.
pub const HouseScopedListRequest = struct {
    house_id: HouseID,
    limit: ?u64 = null,
    offset: ?u64 = null,
};

/// MemberScopedListRequest is a structured data type.
pub const MemberScopedListRequest = struct {
    house_id: HouseID,
    member_id: MemberID,
    limit: ?u64 = null,
    offset: ?u64 = null,
};

/// ProjectScopedListRequest is a structured data type.
pub const ProjectScopedListRequest = struct {
    house_id: HouseID,
    project_id: ProjectID,
    limit: ?u64 = null,
    offset: ?u64 = null,
};

/// CommentListRequest is a structured data type.
pub const CommentListRequest = struct {
    target_type: TargetType,
    target_id: []const u8,
    limit: ?u64 = null,
    offset: ?u64 = null,
};

/// Notification is a structured data type.
pub const Notification = struct {
    notification_id: NotificationID,
    house_id: HouseID,
    member_id: MemberID,
    kind: []const u8,
    actor_member_id: ?MemberID = null,
    actor_name: []const u8,
    target_type: ?[]const u8 = null,
    target_id: ?[]const u8 = null,
    target_title: []const u8,
    body: []const u8,
    read: bool,
    read_at: ?Timestamp = null,
    created_at: Timestamp,
};

/// NotificationListRequest is a structured data type.
pub const NotificationListRequest = struct {
    house_id: HouseID,
    unread_only: ?bool = null,
    limit: ?u64 = null,
    offset: ?u64 = null,
};

/// ShareAccessRequest is a structured data type.
pub const ShareAccessRequest = struct {
    linkkeys_domain: []const u8,
    linkkeys_user_id: []const u8,
    resource_type: ResourceType,
    resource_id: []const u8,
};

/// ResourceRef is a structured data type.
pub const ResourceRef = struct {
    resource_type: ResourceType,
    resource_id: []const u8,
};

/// MemberRoleRef is a structured data type.
pub const MemberRoleRef = struct {
    member_id: MemberID,
    role_id: RoleID,
};

/// MemberSkillRef is a structured data type.
pub const MemberSkillRef = struct {
    member_id: MemberID,
    skill_id: SkillID,
};

/// GroupSkillRef is a structured data type.
pub const GroupSkillRef = struct {
    group_id: GroupID,
    skill_id: SkillID,
};

/// GroupMemberRef is a structured data type.
pub const GroupMemberRef = struct {
    group_id: GroupID,
    member_id: MemberID,
};

/// ProjectTaskRef is a structured data type.
pub const ProjectTaskRef = struct {
    project_id: ProjectID,
    task_id: TaskID,
};

/// ProjectTaskOrderRequest is a structured data type.
pub const ProjectTaskOrderRequest = struct {
    project_id: ProjectID,
    task_id: TaskID,
    position: i64,
};

/// ProjectMemberRef is a structured data type.
pub const ProjectMemberRef = struct {
    project_id: ProjectID,
    member_id: MemberID,
};

/// ProjectOwnerRef is a structured data type.
pub const ProjectOwnerRef = struct {
    project_id: ProjectID,
    member_id: MemberID,
};

/// DependencyRef is a structured data type.
pub const DependencyRef = struct {
    dependent_type: DependencyNodeType,
    dependent_id: []const u8,
    dependency_type: DependencyNodeType,
    dependency_id: []const u8,
};

/// DependencyTarget is a structured data type.
pub const DependencyTarget = struct {
    @"type": DependencyNodeType,
    id: []const u8,
};

/// DependencyNode is a structured data type.
pub const DependencyNode = struct {
    @"type": DependencyNodeType,
    id: []const u8,
    title: []const u8,
    status: ?[]const u8 = null,
};

/// Grant is a structured data type.
pub const Grant = struct {
    grantee_type: GranteeType,
    grantee_id: []const u8,
    access_level: AccessLevel,
};

/// TaskGrantRef is a structured data type.
pub const TaskGrantRef = struct {
    task_id: TaskID,
    grantee_type: GranteeType,
    grantee_id: []const u8,
};

/// PutTaskGrantRequest is a structured data type.
pub const PutTaskGrantRequest = struct {
    task_id: TaskID,
    grantee_type: GranteeType,
    grantee_id: []const u8,
    access_level: AccessLevel,
};

/// SetTaskVisibilityRequest is a structured data type.
pub const SetTaskVisibilityRequest = struct {
    task_id: TaskID,
    visibility: AccessLevel,
};

/// ProjectGrantRef is a structured data type.
pub const ProjectGrantRef = struct {
    project_id: ProjectID,
    grantee_type: GranteeType,
    grantee_id: []const u8,
};

/// PutProjectGrantRequest is a structured data type.
pub const PutProjectGrantRequest = struct {
    project_id: ProjectID,
    grantee_type: GranteeType,
    grantee_id: []const u8,
    access_level: AccessLevel,
};

/// SetProjectVisibilityRequest is a structured data type.
pub const SetProjectVisibilityRequest = struct {
    project_id: ProjectID,
    visibility: AccessLevel,
};

/// UpdateSettingsRequest is a structured data type.
pub const UpdateSettingsRequest = struct {
    house_id: HouseID,
    settings: EffectiveSettings,
};

/// BugReportRequest is a structured data type.
pub const BugReportRequest = struct {
    house_id: HouseID,
    title: []const u8,
    description: ?[]const u8 = null,
};

/// AuditEntry is a structured data type.
pub const AuditEntry = struct {
    audit_id: AuditID,
    house_id: ?HouseID = null,
    actor_member_id: ?MemberID = null,
    actor_domain: []const u8,
    actor_user_id: []const u8,
    service_name: []const u8,
    method: []const u8,
    action: []const u8,
    resource_type: ?[]const u8 = null,
    resource_id: ?[]const u8 = null,
    outcome: []const u8,
    before: ?[]const u8 = null,
    after: ?[]const u8 = null,
    detail: ?[]const u8 = null,
    created_at: Timestamp,
};

/// AuditQuery is a structured data type.
pub const AuditQuery = struct {
    house_id: HouseID,
    actor_member_id: ?MemberID = null,
    resource_type: ?[]const u8 = null,
    action: ?[]const u8 = null,
    since: ?Timestamp = null,
    until: ?Timestamp = null,
    cursor: ?[]const u8 = null,
    limit: ?u64 = null,
};

/// TrashItem is a structured data type.
pub const TrashItem = struct {
    resource_type: []const u8,
    resource_id: []const u8,
    house_id: HouseID,
    title: ?[]const u8 = null,
    deleted_at: Timestamp,
    deleted_by_member_id: ?MemberID = null,
    deleted_op_id: []const u8,
};

/// RestoreRequest is a structured data type.
pub const RestoreRequest = struct {
    house_id: HouseID,
    deleted_op_id: ?[]const u8 = null,
    resource_type: ?[]const u8 = null,
    resource_id: ?[]const u8 = null,
};

/// PurgeRequest is a structured data type.
pub const PurgeRequest = struct {
    house_id: HouseID,
    resource_type: []const u8,
    resource_id: []const u8,
};
