(* Code generated by csilgen; DO NOT EDIT. *)

open Types

(* The transport seam is supplied by the consumer: [call] performs the RPC named
   by (service, op) over its carrier and returns the raw reply payload, or an
   error string. The generated client owns serialization (it encodes the typed
   request and decodes the typed reply via [Codec]); the carrier only moves bytes. *)
type client = {
  call : service:string -> op:string -> payload:bytes -> (bytes, string) result;
}

let make_client ~call = { call }

module Auth_service = struct
  let login (c : client) (req : login_request) : (login_response, string) result =
    match c.call ~service:"AuthService" ~op:"login" ~payload:(Codec.encode_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_login_response_bytes payload)
    | Error _ as e -> e

  let complete (c : client) (req : complete_request) : (login_response, string) result =
    match c.call ~service:"AuthService" ~op:"complete" ~payload:(Codec.encode_complete_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_login_response_bytes payload)
    | Error _ as e -> e

  let refresh (c : client) (req : empty_request) : (login_response, string) result =
    match c.call ~service:"AuthService" ~op:"refresh" ~payload:(Codec.encode_empty_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_login_response_bytes payload)
    | Error _ as e -> e

  let logout (c : client) (req : empty_request) : (empty_response, string) result =
    match c.call ~service:"AuthService" ~op:"logout" ~payload:(Codec.encode_empty_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let me (c : client) (req : empty_request) : (me_response, string) result =
    match c.call ~service:"AuthService" ~op:"me" ~payload:(Codec.encode_empty_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_me_response_bytes payload)
    | Error _ as e -> e

  let begin_cli_login (c : client) (req : begin_cli_login_request) : (begin_cli_login_response, string) result =
    match c.call ~service:"AuthService" ~op:"begin-cli-login" ~payload:(Codec.encode_begin_cli_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_begin_cli_login_response_bytes payload)
    | Error _ as e -> e

  let inspect_cli_login (c : client) (req : approve_cli_login_request) : (cli_login_request_info, string) result =
    match c.call ~service:"AuthService" ~op:"inspect-cli-login" ~payload:(Codec.encode_approve_cli_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_cli_login_request_info_bytes payload)
    | Error _ as e -> e

  let approve_cli_login (c : client) (req : approve_cli_login_request) : (empty_response, string) result =
    match c.call ~service:"AuthService" ~op:"approve-cli-login" ~payload:(Codec.encode_approve_cli_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let deny_cli_login (c : client) (req : deny_cli_login_request) : (empty_response, string) result =
    match c.call ~service:"AuthService" ~op:"deny-cli-login" ~payload:(Codec.encode_deny_cli_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let exchange_cli_login (c : client) (req : exchange_cli_login_request) : (exchange_cli_login_response, string) result =
    match c.call ~service:"AuthService" ~op:"exchange-cli-login" ~payload:(Codec.encode_exchange_cli_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_exchange_cli_login_response_bytes payload)
    | Error _ as e -> e

  let refresh_session (c : client) (req : refresh_session_request) : (cli_token_response, string) result =
    match c.call ~service:"AuthService" ~op:"refresh-session" ~payload:(Codec.encode_refresh_session_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_cli_token_response_bytes payload)
    | Error _ as e -> e

  let list_sessions (c : client) (req : empty_request) : (cli_sessions_response, string) result =
    match c.call ~service:"AuthService" ~op:"list-sessions" ~payload:(Codec.encode_empty_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_cli_sessions_response_bytes payload)
    | Error _ as e -> e

  let revoke_session (c : client) (req : revoke_session_request) : (empty_response, string) result =
    match c.call ~service:"AuthService" ~op:"revoke-session" ~payload:(Codec.encode_revoke_session_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e
end

module Dev_auth_service = struct
  let list_dev_users (c : client) (req : empty_request) : (dev_users_response, string) result =
    match c.call ~service:"DevAuthService" ~op:"list-dev-users" ~payload:(Codec.encode_empty_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_dev_users_response_bytes payload)
    | Error _ as e -> e

  let dev_login (c : client) (req : dev_login_request) : (login_response, string) result =
    match c.call ~service:"DevAuthService" ~op:"dev-login" ~payload:(Codec.encode_dev_login_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_login_response_bytes payload)
    | Error _ as e -> e
end

module House_service = struct
  let create_house (c : client) (req : house) : (house, string) result =
    match c.call ~service:"HouseService" ~op:"create-house" ~payload:(Codec.encode_house_bytes req) with
    | Ok payload -> Ok (Codec.decode_house_bytes payload)
    | Error _ as e -> e

  let get_house (c : client)
      ~(encode_request : house_id -> bytes)
      (req : house_id) : (house, string) result =
    match c.call ~service:"HouseService" ~op:"get-house" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_house_bytes payload)
    | Error _ as e -> e

  let update_house (c : client) (req : house) : (house, string) result =
    match c.call ~service:"HouseService" ~op:"update-house" ~payload:(Codec.encode_house_bytes req) with
    | Ok payload -> Ok (Codec.decode_house_bytes payload)
    | Error _ as e -> e

  let delete_house (c : client)
      ~(encode_request : house_id -> bytes)
      (req : house_id) : (empty_response, string) result =
    match c.call ~service:"HouseService" ~op:"delete-house" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_houses (c : client)
      ~(decode_response : bytes -> house list)
      (req : house_list_request) : (house list, string) result =
    match c.call ~service:"HouseService" ~op:"list-houses" ~payload:(Codec.encode_house_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Member_service = struct
  let create_member (c : client) (req : member) : (member, string) result =
    match c.call ~service:"MemberService" ~op:"create-member" ~payload:(Codec.encode_member_bytes req) with
    | Ok payload -> Ok (Codec.decode_member_bytes payload)
    | Error _ as e -> e

  let get_member (c : client)
      ~(encode_request : member_id -> bytes)
      (req : member_id) : (member, string) result =
    match c.call ~service:"MemberService" ~op:"get-member" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_member_bytes payload)
    | Error _ as e -> e

  let get_member_by_identity (c : client) (req : member) : (member, string) result =
    match c.call ~service:"MemberService" ~op:"get-member-by-identity" ~payload:(Codec.encode_member_bytes req) with
    | Ok payload -> Ok (Codec.decode_member_bytes payload)
    | Error _ as e -> e

  let update_member (c : client) (req : member) : (member, string) result =
    match c.call ~service:"MemberService" ~op:"update-member" ~payload:(Codec.encode_member_bytes req) with
    | Ok payload -> Ok (Codec.decode_member_bytes payload)
    | Error _ as e -> e

  let deactivate_member (c : client)
      ~(encode_request : member_id -> bytes)
      (req : member_id) : (empty_response, string) result =
    match c.call ~service:"MemberService" ~op:"deactivate-member" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let reactivate_member (c : client)
      ~(encode_request : member_id -> bytes)
      (req : member_id) : (empty_response, string) result =
    match c.call ~service:"MemberService" ~op:"reactivate-member" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_members (c : client)
      ~(decode_response : bytes -> member list)
      (req : house_scoped_list_request) : (member list, string) result =
    match c.call ~service:"MemberService" ~op:"list-members" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Trusted_domain_service = struct
  let add_trusted_domain (c : client) (req : trusted_domain) : (trusted_domain, string) result =
    match c.call ~service:"TrustedDomainService" ~op:"add-trusted-domain" ~payload:(Codec.encode_trusted_domain_bytes req) with
    | Ok payload -> Ok (Codec.decode_trusted_domain_bytes payload)
    | Error _ as e -> e

  let remove_trusted_domain (c : client)
      ~(encode_request : trusted_domain_id -> bytes)
      (req : trusted_domain_id) : (empty_response, string) result =
    match c.call ~service:"TrustedDomainService" ~op:"remove-trusted-domain" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_trusted_domains (c : client)
      ~(encode_request : house_id -> bytes)
      ~(decode_response : bytes -> trusted_domain list)
      (req : house_id) : (trusted_domain list, string) result =
    match c.call ~service:"TrustedDomainService" ~op:"list-trusted-domains" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let is_domain_trusted (c : client) (req : trusted_domain) : (bool_response, string) result =
    match c.call ~service:"TrustedDomainService" ~op:"is-domain-trusted" ~payload:(Codec.encode_trusted_domain_bytes req) with
    | Ok payload -> Ok (Codec.decode_bool_response_bytes payload)
    | Error _ as e -> e
end

module Role_service = struct
  let create_role (c : client) (req : role) : (role, string) result =
    match c.call ~service:"RoleService" ~op:"create-role" ~payload:(Codec.encode_role_bytes req) with
    | Ok payload -> Ok (Codec.decode_role_bytes payload)
    | Error _ as e -> e

  let update_role (c : client) (req : role) : (role, string) result =
    match c.call ~service:"RoleService" ~op:"update-role" ~payload:(Codec.encode_role_bytes req) with
    | Ok payload -> Ok (Codec.decode_role_bytes payload)
    | Error _ as e -> e

  let delete_role (c : client)
      ~(encode_request : role_id -> bytes)
      (req : role_id) : (empty_response, string) result =
    match c.call ~service:"RoleService" ~op:"delete-role" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_roles (c : client)
      ~(decode_response : bytes -> role list)
      (req : house_scoped_list_request) : (role list, string) result =
    match c.call ~service:"RoleService" ~op:"list-roles" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let grant_role (c : client) (req : member_role_ref) : (empty_response, string) result =
    match c.call ~service:"RoleService" ~op:"grant-role" ~payload:(Codec.encode_member_role_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let revoke_role (c : client) (req : member_role_ref) : (empty_response, string) result =
    match c.call ~service:"RoleService" ~op:"revoke-role" ~payload:(Codec.encode_member_role_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_member_roles (c : client)
      ~(decode_response : bytes -> role list)
      (req : member_scoped_list_request) : (role list, string) result =
    match c.call ~service:"RoleService" ~op:"list-member-roles" ~payload:(Codec.encode_member_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Skill_service = struct
  let create_skill (c : client) (req : skill) : (skill, string) result =
    match c.call ~service:"SkillService" ~op:"create-skill" ~payload:(Codec.encode_skill_bytes req) with
    | Ok payload -> Ok (Codec.decode_skill_bytes payload)
    | Error _ as e -> e

  let update_skill (c : client) (req : skill) : (skill, string) result =
    match c.call ~service:"SkillService" ~op:"update-skill" ~payload:(Codec.encode_skill_bytes req) with
    | Ok payload -> Ok (Codec.decode_skill_bytes payload)
    | Error _ as e -> e

  let delete_skill (c : client)
      ~(encode_request : skill_id -> bytes)
      (req : skill_id) : (empty_response, string) result =
    match c.call ~service:"SkillService" ~op:"delete-skill" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_skills (c : client)
      ~(decode_response : bytes -> skill list)
      (req : house_scoped_list_request) : (skill list, string) result =
    match c.call ~service:"SkillService" ~op:"list-skills" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let add_member_skill (c : client) (req : member_skill_ref) : (empty_response, string) result =
    match c.call ~service:"SkillService" ~op:"add-member-skill" ~payload:(Codec.encode_member_skill_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_member_skill (c : client) (req : member_skill_ref) : (empty_response, string) result =
    match c.call ~service:"SkillService" ~op:"remove-member-skill" ~payload:(Codec.encode_member_skill_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_member_skills (c : client)
      ~(decode_response : bytes -> skill list)
      (req : member_scoped_list_request) : (skill list, string) result =
    match c.call ~service:"SkillService" ~op:"list-member-skills" ~payload:(Codec.encode_member_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let add_group_skill (c : client) (req : group_skill_ref) : (empty_response, string) result =
    match c.call ~service:"SkillService" ~op:"add-group-skill" ~payload:(Codec.encode_group_skill_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_group_skill (c : client) (req : group_skill_ref) : (empty_response, string) result =
    match c.call ~service:"SkillService" ~op:"remove-group-skill" ~payload:(Codec.encode_group_skill_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_group_skills (c : client)
      ~(encode_request : group_id -> bytes)
      ~(decode_response : bytes -> skill list)
      (req : group_id) : (skill list, string) result =
    match c.call ~service:"SkillService" ~op:"list-group-skills" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Group_service = struct
  let create_group (c : client) (req : group) : (group, string) result =
    match c.call ~service:"GroupService" ~op:"create-group" ~payload:(Codec.encode_group_bytes req) with
    | Ok payload -> Ok (Codec.decode_group_bytes payload)
    | Error _ as e -> e

  let update_group (c : client) (req : group) : (group, string) result =
    match c.call ~service:"GroupService" ~op:"update-group" ~payload:(Codec.encode_group_bytes req) with
    | Ok payload -> Ok (Codec.decode_group_bytes payload)
    | Error _ as e -> e

  let delete_group (c : client)
      ~(encode_request : group_id -> bytes)
      (req : group_id) : (empty_response, string) result =
    match c.call ~service:"GroupService" ~op:"delete-group" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_groups (c : client)
      ~(decode_response : bytes -> group list)
      (req : house_scoped_list_request) : (group list, string) result =
    match c.call ~service:"GroupService" ~op:"list-groups" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let add_group_member (c : client) (req : group_member_ref) : (empty_response, string) result =
    match c.call ~service:"GroupService" ~op:"add-group-member" ~payload:(Codec.encode_group_member_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_group_member (c : client) (req : group_member_ref) : (empty_response, string) result =
    match c.call ~service:"GroupService" ~op:"remove-group-member" ~payload:(Codec.encode_group_member_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_group_members (c : client)
      ~(decode_response : bytes -> member list)
      (req : member_scoped_list_request) : (member list, string) result =
    match c.call ~service:"GroupService" ~op:"list-group-members" ~payload:(Codec.encode_member_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Project_service = struct
  let create_project (c : client) (req : project) : (project, string) result =
    match c.call ~service:"ProjectService" ~op:"create-project" ~payload:(Codec.encode_project_bytes req) with
    | Ok payload -> Ok (Codec.decode_project_bytes payload)
    | Error _ as e -> e

  let get_project (c : client)
      ~(encode_request : project_id -> bytes)
      (req : project_id) : (project, string) result =
    match c.call ~service:"ProjectService" ~op:"get-project" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_project_bytes payload)
    | Error _ as e -> e

  let update_project (c : client) (req : project) : (project, string) result =
    match c.call ~service:"ProjectService" ~op:"update-project" ~payload:(Codec.encode_project_bytes req) with
    | Ok payload -> Ok (Codec.decode_project_bytes payload)
    | Error _ as e -> e

  let delete_project (c : client)
      ~(encode_request : project_id -> bytes)
      (req : project_id) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"delete-project" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_projects (c : client) (req : house_scoped_list_request) : (project_list, string) result =
    match c.call ~service:"ProjectService" ~op:"list-projects" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_project_list_bytes payload)
    | Error _ as e -> e

  let list_project_tasks (c : client) (req : project_scoped_list_request) : (task_list, string) result =
    match c.call ~service:"ProjectService" ~op:"list-project-tasks" ~payload:(Codec.encode_project_scoped_list_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_task_list_bytes payload)
    | Error _ as e -> e

  let add_project_task (c : client) (req : project_task_order_request) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"add-project-task" ~payload:(Codec.encode_project_task_order_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_project_task (c : client) (req : project_task_ref) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"remove-project-task" ~payload:(Codec.encode_project_task_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let set_project_task_position (c : client) (req : project_task_order_request) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"set-project-task-position" ~payload:(Codec.encode_project_task_order_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_project_members (c : client)
      ~(encode_request : project_id -> bytes)
      ~(decode_response : bytes -> member list)
      (req : project_id) : (member list, string) result =
    match c.call ~service:"ProjectService" ~op:"list-project-members" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let add_project_member (c : client) (req : project_member_ref) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"add-project-member" ~payload:(Codec.encode_project_member_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_project_member (c : client) (req : project_member_ref) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"remove-project-member" ~payload:(Codec.encode_project_member_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_project_owners (c : client)
      ~(encode_request : project_id -> bytes)
      ~(decode_response : bytes -> member list)
      (req : project_id) : (member list, string) result =
    match c.call ~service:"ProjectService" ~op:"list-project-owners" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let add_project_owner (c : client) (req : project_owner_ref) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"add-project-owner" ~payload:(Codec.encode_project_owner_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_project_owner (c : client) (req : project_owner_ref) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"remove-project-owner" ~payload:(Codec.encode_project_owner_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_milestones (c : client)
      ~(encode_request : project_id -> bytes)
      ~(decode_response : bytes -> milestone list)
      (req : project_id) : (milestone list, string) result =
    match c.call ~service:"ProjectService" ~op:"list-milestones" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let create_milestone (c : client) (req : milestone) : (milestone, string) result =
    match c.call ~service:"ProjectService" ~op:"create-milestone" ~payload:(Codec.encode_milestone_bytes req) with
    | Ok payload -> Ok (Codec.decode_milestone_bytes payload)
    | Error _ as e -> e

  let update_milestone (c : client) (req : milestone) : (milestone, string) result =
    match c.call ~service:"ProjectService" ~op:"update-milestone" ~payload:(Codec.encode_milestone_bytes req) with
    | Ok payload -> Ok (Codec.decode_milestone_bytes payload)
    | Error _ as e -> e

  let delete_milestone (c : client)
      ~(encode_request : milestone_id -> bytes)
      (req : milestone_id) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"delete-milestone" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let set_project_visibility (c : client) (req : set_project_visibility_request) : (project, string) result =
    match c.call ~service:"ProjectService" ~op:"set-project-visibility" ~payload:(Codec.encode_set_project_visibility_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_project_bytes payload)
    | Error _ as e -> e

  let list_project_grants (c : client)
      ~(encode_request : project_id -> bytes)
      ~(decode_response : bytes -> grant list)
      (req : project_id) : (grant list, string) result =
    match c.call ~service:"ProjectService" ~op:"list-project-grants" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let put_project_grant (c : client) (req : put_project_grant_request) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"put-project-grant" ~payload:(Codec.encode_put_project_grant_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let delete_project_grant (c : client) (req : project_grant_ref) : (empty_response, string) result =
    match c.call ~service:"ProjectService" ~op:"delete-project-grant" ~payload:(Codec.encode_project_grant_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e
end

module Event_service = struct
  let create_event (c : client) (req : event) : (event, string) result =
    match c.call ~service:"EventService" ~op:"create-event" ~payload:(Codec.encode_event_bytes req) with
    | Ok payload -> Ok (Codec.decode_event_bytes payload)
    | Error _ as e -> e

  let get_event (c : client)
      ~(encode_request : event_id -> bytes)
      (req : event_id) : (event, string) result =
    match c.call ~service:"EventService" ~op:"get-event" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_event_bytes payload)
    | Error _ as e -> e

  let update_event (c : client) (req : event) : (event, string) result =
    match c.call ~service:"EventService" ~op:"update-event" ~payload:(Codec.encode_event_bytes req) with
    | Ok payload -> Ok (Codec.decode_event_bytes payload)
    | Error _ as e -> e

  let delete_event (c : client)
      ~(encode_request : event_id -> bytes)
      (req : event_id) : (empty_response, string) result =
    match c.call ~service:"EventService" ~op:"delete-event" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let delete_event_and_future (c : client)
      ~(encode_request : event_id -> bytes)
      (req : event_id) : (empty_response, string) result =
    match c.call ~service:"EventService" ~op:"delete-event-and-future" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_events (c : client)
      ~(decode_response : bytes -> event list)
      (req : house_scoped_list_request) : (event list, string) result =
    match c.call ~service:"EventService" ~op:"list-events" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let get_calendar_view (c : client)
      ~(encode_request : house_id -> bytes)
      (req : house_id) : (calendar_view, string) result =
    match c.call ~service:"EventService" ~op:"get-calendar-view" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_calendar_view_bytes payload)
    | Error _ as e -> e

  let set_calendar_view (c : client) (req : calendar_view) : (calendar_view, string) result =
    match c.call ~service:"EventService" ~op:"set-calendar-view" ~payload:(Codec.encode_calendar_view_bytes req) with
    | Ok payload -> Ok (Codec.decode_calendar_view_bytes payload)
    | Error _ as e -> e
end

module Task_service = struct
  let create_task (c : client) (req : task) : (task, string) result =
    match c.call ~service:"TaskService" ~op:"create-task" ~payload:(Codec.encode_task_bytes req) with
    | Ok payload -> Ok (Codec.decode_task_bytes payload)
    | Error _ as e -> e

  let get_task (c : client)
      ~(encode_request : task_id -> bytes)
      (req : task_id) : (task, string) result =
    match c.call ~service:"TaskService" ~op:"get-task" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_task_bytes payload)
    | Error _ as e -> e

  let update_task (c : client) (req : task) : (task, string) result =
    match c.call ~service:"TaskService" ~op:"update-task" ~payload:(Codec.encode_task_bytes req) with
    | Ok payload -> Ok (Codec.decode_task_bytes payload)
    | Error _ as e -> e

  let delete_task (c : client)
      ~(encode_request : task_id -> bytes)
      (req : task_id) : (empty_response, string) result =
    match c.call ~service:"TaskService" ~op:"delete-task" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_tasks (c : client) (req : house_scoped_list_request) : (task_list, string) result =
    match c.call ~service:"TaskService" ~op:"list-tasks" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_task_list_bytes payload)
    | Error _ as e -> e

  let set_task_visibility (c : client) (req : set_task_visibility_request) : (task, string) result =
    match c.call ~service:"TaskService" ~op:"set-task-visibility" ~payload:(Codec.encode_set_task_visibility_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_task_bytes payload)
    | Error _ as e -> e

  let list_task_grants (c : client)
      ~(encode_request : task_id -> bytes)
      ~(decode_response : bytes -> grant list)
      (req : task_id) : (grant list, string) result =
    match c.call ~service:"TaskService" ~op:"list-task-grants" ~payload:(encode_request req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let put_task_grant (c : client) (req : put_task_grant_request) : (empty_response, string) result =
    match c.call ~service:"TaskService" ~op:"put-task-grant" ~payload:(Codec.encode_put_task_grant_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let delete_task_grant (c : client) (req : task_grant_ref) : (empty_response, string) result =
    match c.call ~service:"TaskService" ~op:"delete-task-grant" ~payload:(Codec.encode_task_grant_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e
end

module Dependency_service = struct
  let add_dependency (c : client) (req : dependency_ref) : (empty_response, string) result =
    match c.call ~service:"DependencyService" ~op:"add-dependency" ~payload:(Codec.encode_dependency_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let remove_dependency (c : client) (req : dependency_ref) : (empty_response, string) result =
    match c.call ~service:"DependencyService" ~op:"remove-dependency" ~payload:(Codec.encode_dependency_ref_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let get_dependencies (c : client) (req : dependency_target) : (dependency_graph, string) result =
    match c.call ~service:"DependencyService" ~op:"get-dependencies" ~payload:(Codec.encode_dependency_target_bytes req) with
    | Ok payload -> Ok (Codec.decode_dependency_graph_bytes payload)
    | Error _ as e -> e
end

module Comment_service = struct
  let create_comment (c : client) (req : comment) : (comment, string) result =
    match c.call ~service:"CommentService" ~op:"create-comment" ~payload:(Codec.encode_comment_bytes req) with
    | Ok payload -> Ok (Codec.decode_comment_bytes payload)
    | Error _ as e -> e

  let get_comment (c : client)
      ~(encode_request : comment_id -> bytes)
      (req : comment_id) : (comment, string) result =
    match c.call ~service:"CommentService" ~op:"get-comment" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_comment_bytes payload)
    | Error _ as e -> e

  let update_comment (c : client) (req : comment) : (comment, string) result =
    match c.call ~service:"CommentService" ~op:"update-comment" ~payload:(Codec.encode_comment_bytes req) with
    | Ok payload -> Ok (Codec.decode_comment_bytes payload)
    | Error _ as e -> e

  let delete_comment (c : client)
      ~(encode_request : comment_id -> bytes)
      (req : comment_id) : (empty_response, string) result =
    match c.call ~service:"CommentService" ~op:"delete-comment" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_comments (c : client)
      ~(decode_response : bytes -> comment list)
      (req : comment_list_request) : (comment list, string) result =
    match c.call ~service:"CommentService" ~op:"list-comments" ~payload:(Codec.encode_comment_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Notification_service = struct
  let list_notifications (c : client)
      ~(decode_response : bytes -> notification list)
      (req : notification_list_request) : (notification list, string) result =
    match c.call ~service:"NotificationService" ~op:"list-notifications" ~payload:(Codec.encode_notification_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let unread_count (c : client)
      ~(encode_request : house_id -> bytes)
      (req : house_id) : (notification_unread_count, string) result =
    match c.call ~service:"NotificationService" ~op:"unread-count" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_notification_unread_count_bytes payload)
    | Error _ as e -> e

  let mark_read (c : client)
      ~(encode_request : notification_id -> bytes)
      (req : notification_id) : (notification, string) result =
    match c.call ~service:"NotificationService" ~op:"mark-read" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_notification_bytes payload)
    | Error _ as e -> e

  let mark_all_read (c : client)
      ~(encode_request : house_id -> bytes)
      (req : house_id) : (empty_response, string) result =
    match c.call ~service:"NotificationService" ~op:"mark-all-read" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e
end

module Share_service = struct
  let create_share (c : client) (req : share) : (share, string) result =
    match c.call ~service:"ShareService" ~op:"create-share" ~payload:(Codec.encode_share_bytes req) with
    | Ok payload -> Ok (Codec.decode_share_bytes payload)
    | Error _ as e -> e

  let delete_share (c : client)
      ~(encode_request : share_id -> bytes)
      (req : share_id) : (empty_response, string) result =
    match c.call ~service:"ShareService" ~op:"delete-share" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let list_shares_by_resource (c : client)
      ~(decode_response : bytes -> share list)
      (req : resource_ref) : (share list, string) result =
    match c.call ~service:"ShareService" ~op:"list-shares-by-resource" ~payload:(Codec.encode_resource_ref_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e

  let check_access (c : client) (req : share_access_request) : (share, string) result =
    match c.call ~service:"ShareService" ~op:"check-access" ~payload:(Codec.encode_share_access_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_share_bytes payload)
    | Error _ as e -> e
end

module Member_audit_service = struct
  let list_audits_for_member (c : client)
      ~(decode_response : bytes -> member_audit list)
      (req : member_scoped_list_request) : (member_audit list, string) result =
    match c.call ~service:"MemberAuditService" ~op:"list-audits-for-member" ~payload:(Codec.encode_member_scoped_list_request_bytes req) with
    | Ok payload -> Ok (decode_response payload)
    | Error _ as e -> e
end

module Settings_service = struct
  let get_settings (c : client)
      ~(encode_request : house_id -> bytes)
      (req : house_id) : (effective_settings, string) result =
    match c.call ~service:"SettingsService" ~op:"get-settings" ~payload:(encode_request req) with
    | Ok payload -> Ok (Codec.decode_effective_settings_bytes payload)
    | Error _ as e -> e

  let update_settings (c : client) (req : update_settings_request) : (effective_settings, string) result =
    match c.call ~service:"SettingsService" ~op:"update-settings" ~payload:(Codec.encode_update_settings_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_effective_settings_bytes payload)
    | Error _ as e -> e
end

module Bug_service = struct
  let report_bug (c : client) (req : bug_report_request) : (task, string) result =
    match c.call ~service:"BugService" ~op:"report-bug" ~payload:(Codec.encode_bug_report_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_task_bytes payload)
    | Error _ as e -> e
end

module Audit_service = struct
  let query_audit (c : client) (req : audit_query) : (audit_page, string) result =
    match c.call ~service:"AuditService" ~op:"query-audit" ~payload:(Codec.encode_audit_query_bytes req) with
    | Ok payload -> Ok (Codec.decode_audit_page_bytes payload)
    | Error _ as e -> e
end

module Trash_service = struct
  let list_trash (c : client) (req : house_scoped_list_request) : (trash_page, string) result =
    match c.call ~service:"TrashService" ~op:"list-trash" ~payload:(Codec.encode_house_scoped_list_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_trash_page_bytes payload)
    | Error _ as e -> e

  let restore (c : client) (req : restore_request) : (empty_response, string) result =
    match c.call ~service:"TrashService" ~op:"restore" ~payload:(Codec.encode_restore_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e

  let purge (c : client) (req : purge_request) : (empty_response, string) result =
    match c.call ~service:"TrashService" ~op:"purge" ~payload:(Codec.encode_purge_request_bytes req) with
    | Ok payload -> Ok (Codec.decode_empty_response_bytes payload)
    | Error _ as e -> e
end
