(* Code generated by csilgen; DO NOT EDIT. *)

type t =
  | Uint of int64
  | Nint of int64 (* the logical (negative) value; encodes as CBOR major type 1 *)
  | Bool of bool
  | Float of float
  | Null
  | Text of string
  | Bytes of bytes
  | Array of t list
  | Map of (t * t) list
  | Tag of int * t

let int64 (n : int64) : t = if Int64.compare n 0L >= 0 then Uint n else Nint n

let add_head buf major (u : int64) =
  let mt = major lsl 5 in
  let byte shift = Char.chr (Int64.to_int (Int64.logand (Int64.shift_right_logical u shift) 0xffL)) in
  if Int64.unsigned_compare u 24L < 0 then
    Buffer.add_char buf (Char.chr (mt lor Int64.to_int u))
  else if Int64.unsigned_compare u 0x100L < 0 then begin
    Buffer.add_char buf (Char.chr (mt lor 24));
    Buffer.add_char buf (byte 0)
  end
  else if Int64.unsigned_compare u 0x10000L < 0 then begin
    Buffer.add_char buf (Char.chr (mt lor 25));
    Buffer.add_char buf (byte 8);
    Buffer.add_char buf (byte 0)
  end
  else if Int64.unsigned_compare u 0x100000000L < 0 then begin
    Buffer.add_char buf (Char.chr (mt lor 26));
    for i = 3 downto 0 do Buffer.add_char buf (byte (i * 8)) done
  end
  else begin
    Buffer.add_char buf (Char.chr (mt lor 27));
    for i = 7 downto 0 do Buffer.add_char buf (byte (i * 8)) done
  end

let rec enc buf = function
  | Uint n -> add_head buf 0 n
  | Nint n -> add_head buf 1 (Int64.sub (Int64.neg n) 1L)
  | Bool b -> Buffer.add_char buf (if b then '\xf5' else '\xf4')
  | Null -> Buffer.add_char buf '\xf6'
  | Float f ->
    Buffer.add_char buf '\xfb';
    let bits = Int64.bits_of_float f in
    for i = 7 downto 0 do
      Buffer.add_char buf (Char.chr (Int64.to_int (Int64.logand (Int64.shift_right_logical bits (i * 8)) 0xffL)))
    done
  | Text s -> add_head buf 3 (Int64.of_int (String.length s)); Buffer.add_string buf s
  | Bytes b -> add_head buf 2 (Int64.of_int (Bytes.length b)); Buffer.add_bytes buf b
  | Array xs -> add_head buf 4 (Int64.of_int (List.length xs)); List.iter (enc buf) xs
  | Map kvs ->
    (* Canonical map ordering (RFC 8949 §4.2.1): entries are sorted by the bytewise
       lexicographic order of their *encoded* keys, so the same logical map always
       yields the same bytes regardless of insertion order (records are already in
       canonical order at generation time, so this is idempotent for them). *)
    let enc_key k = let b = Buffer.create 16 in enc b k; Buffer.to_bytes b in
    let sorted =
      List.stable_sort (fun (k1, _) (k2, _) -> compare (enc_key k1) (enc_key k2)) kvs
    in
    add_head buf 5 (Int64.of_int (List.length sorted));
    List.iter (fun (k, v) -> enc buf k; enc buf v) sorted
  | Tag (t, v) -> add_head buf 6 (Int64.of_int t); enc buf v

let encode (v : t) : bytes =
  let buf = Buffer.create 64 in
  enc buf v;
  Buffer.to_bytes buf

let decode (b : bytes) : (t, string) result =
  let len = Bytes.length b in
  let byte i = Char.code (Bytes.get b i) in
  let need pos count =
    if pos < 0 || count < 0 || pos > len || len - pos < count then
      failwith "csilgen: truncated input"
  in
  let valid_utf8 s =
    let n = String.length s in
    let code i = Char.code s.[i] in
    let cont i = i < n && let c = code i in c >= 0x80 && c <= 0xbf in
    let rec loop i =
      if i = n then true else
      let c = code i in
      if c < 0x80 then loop (i + 1)
      else if c >= 0xc2 && c <= 0xdf && cont (i + 1) then loop (i + 2)
      else if c >= 0xe0 && c <= 0xef && i + 2 < n then
        let d = code (i + 1) in
        let second =
          if c = 0xe0 then d >= 0xa0 && d <= 0xbf
          else if c = 0xed then d >= 0x80 && d <= 0x9f
          else d >= 0x80 && d <= 0xbf
        in
        second && cont (i + 2) && loop (i + 3)
      else if c >= 0xf0 && c <= 0xf4 && i + 3 < n then
        let d = code (i + 1) in
        let second =
          if c = 0xf0 then d >= 0x90 && d <= 0xbf
          else if c = 0xf4 then d >= 0x80 && d <= 0x8f
          else d >= 0x80 && d <= 0xbf
        in
        second && cont (i + 2) && cont (i + 3) && loop (i + 4)
      else false
    in
    loop 0
  in
  let read_arg pos low =
    if low < 24 then (Int64.of_int low, pos + 1)
    else if low = 24 then (need pos 2; Int64.of_int (byte (pos + 1)), pos + 2)
    else if low = 25 then (need pos 3; Int64.of_int ((byte (pos + 1) lsl 8) lor byte (pos + 2)), pos + 3)
    else if low = 26 then begin
      need pos 5;
      let v = ref 0L in
      for i = 1 to 4 do v := Int64.logor (Int64.shift_left !v 8) (Int64.of_int (byte (pos + i))) done;
      (!v, pos + 5)
    end
    else if low = 27 then begin
      need pos 9;
      let v = ref 0L in
      for i = 1 to 8 do v := Int64.logor (Int64.shift_left !v 8) (Int64.of_int (byte (pos + i))) done;
      (!v, pos + 9)
    end
    else failwith "csilgen: bad head"
  in
  let rec dec depth pos =
    if depth > 64 then failwith "csilgen: nesting limit exceeded";
    need pos 1;
    let ib = byte pos in
    let major = ib lsr 5 and low = ib land 0x1f in
    if major = 7 then
      match low with
      | 20 -> (Bool false, pos + 1)
      | 21 -> (Bool true, pos + 1)
      | 22 | 23 -> (Null, pos + 1)
      | 26 ->
        let arg, p = read_arg pos low in
        (Float (Int32.float_of_bits (Int64.to_int32 arg)), p)
      | 27 ->
        let arg, p = read_arg pos low in
        (Float (Int64.float_of_bits arg), p)
      | _ -> failwith "csilgen: unsupported simple value"
    else begin
      let arg, p = read_arg pos low in
      match major with
      | 0 -> (Uint arg, p)
      | 1 -> (Nint (Int64.sub (Int64.neg arg) 1L), p)
      | 2 ->
        if arg < 0L || arg > Int64.of_int (len - p) then failwith "csilgen: truncated byte string";
        let n = Int64.to_int arg in (Bytes (Bytes.sub b p n), p + n)
      | 3 ->
        if arg < 0L || arg > Int64.of_int (len - p) then failwith "csilgen: truncated text string";
        let n = Int64.to_int arg in
        let s = Bytes.sub_string b p n in
        if not (valid_utf8 s) then failwith "csilgen: invalid utf-8";
        (Text s, p + n)
      | 4 ->
        if arg < 0L || arg > Int64.of_int (len - p) then failwith "csilgen: array length exceeds remaining input";
        let n = Int64.to_int arg in
        let rec loop i pos acc =
          if i = 0 then (List.rev acc, pos)
          else let v, np = dec (depth + 1) pos in loop (i - 1) np (v :: acc)
        in
        let items, np = loop n p [] in
        (Array items, np)
      | 5 ->
        if arg < 0L || arg > Int64.of_int (len - p) then failwith "csilgen: map length exceeds remaining input";
        let n = Int64.to_int arg in
        let rec loop i pos acc =
          if i = 0 then (List.rev acc, pos)
          else
            let k, p1 = dec (depth + 1) pos in
            let v, p2 = dec (depth + 1) p1 in
            loop (i - 1) p2 ((k, v) :: acc)
        in
        let kvs, np = loop n p [] in
        (Map kvs, np)
      | 6 -> let inner, np = dec (depth + 1) p in (Tag (Int64.to_int arg, inner), np)
      | _ -> failwith "csilgen: bad major"
    end
  in
  try
    let v, np = dec 0 0 in
    if np <> len then Error "csilgen: trailing bytes" else Ok v
  with
  | Failure m -> Error m
  | _ -> Error "csilgen: malformed cbor"

let to_i64 = function Uint n | Nint n -> n | _ -> failwith "csilgen: expected int"
let to_text = function Text s -> s | _ -> failwith "csilgen: expected text"
let to_bytes = function Bytes b -> b | _ -> failwith "csilgen: expected bytes"
let to_bool = function Bool b -> b | _ -> failwith "csilgen: expected bool"
let to_float = function
  | Float f -> f
  | Uint n | Nint n -> Int64.to_float n
  | _ -> failwith "csilgen: expected float"

(* The `decimal` core type rides as a CBOR tag-4 decimal fraction `[exponent,
   mantissa]` (value = mantissa * 10^exponent), byte-identical with the other
   generators. OCaml has no decimal type, so it is carried as the exact decimal text
   and parsed/formatted here. *)
let decimal_to_cbor (s : string) : t =
  let s = String.trim s in
  let neg, rest =
    if String.length s > 0 && s.[0] = '-' then (true, String.sub s 1 (String.length s - 1))
    else if String.length s > 0 && s.[0] = '+' then (false, String.sub s 1 (String.length s - 1))
    else (false, s)
  in
  let int_part, frac_part =
    match String.index_opt rest '.' with
    | Some i -> (String.sub rest 0 i, String.sub rest (i + 1) (String.length rest - i - 1))
    | None -> (rest, "")
  in
  let digits = int_part ^ frac_part in
  let magnitude = if digits = "" then 0L else Int64.of_string digits in
  let mantissa = if neg then Int64.neg magnitude else magnitude in
  let exponent = Int64.of_int (-String.length frac_part) in
  Tag (4, Array [ int64 exponent; int64 mantissa ])

let decimal_of_cbor (v : t) : string =
  match v with
  | Tag (4, Array [ e; m ]) ->
    let exponent = Int64.to_int (to_i64 e) in
    let mantissa = to_i64 m in
    let digits = Int64.to_string (Int64.abs mantissa) in
    let body =
      if exponent >= 0 then digits ^ String.make exponent '0'
      else
        let scale = -exponent in
        let dl = String.length digits in
        if dl > scale then
          String.sub digits 0 (dl - scale) ^ "." ^ String.sub digits (dl - scale) scale
        else "0." ^ String.make (scale - dl) '0' ^ digits
    in
    if Int64.compare mantissa 0L < 0 then "-" ^ body else body
  | _ -> failwith "csilgen: expected CBOR tag 4 decimal"
