(* Code generated by csilgen; DO NOT EDIT. *)

(* A handler returns either a typed reply (the [variant] names the chosen output
   arm and [payload] is its encoded bytes) or a transport-level failure. *)
type outcome =
  | Reply of { variant : string; payload : bytes }
  | Transport_error of { status : int64; message : string }

let reply ~variant ~payload = Reply { variant; payload }
let transport_error ~status ~message = Transport_error { status; message }

module Auth_service = struct
  type handler = {
    (* request payload decodes to: login_request *)
    login : bytes -> outcome;
    (* request payload decodes to: complete_request *)
    complete : bytes -> outcome;
    (* request payload decodes to: empty_request *)
    refresh : bytes -> outcome;
    (* request payload decodes to: empty_request *)
    logout : bytes -> outcome;
    (* request payload decodes to: empty_request *)
    me : bytes -> outcome;
    (* request payload decodes to: begin_cli_login_request *)
    begin_cli_login : bytes -> outcome;
    (* request payload decodes to: approve_cli_login_request *)
    inspect_cli_login : bytes -> outcome;
    (* request payload decodes to: approve_cli_login_request *)
    approve_cli_login : bytes -> outcome;
    (* request payload decodes to: deny_cli_login_request *)
    deny_cli_login : bytes -> outcome;
    (* request payload decodes to: exchange_cli_login_request *)
    exchange_cli_login : bytes -> outcome;
    (* request payload decodes to: refresh_session_request *)
    refresh_session : bytes -> outcome;
    (* request payload decodes to: empty_request *)
    list_sessions : bytes -> outcome;
    (* request payload decodes to: revoke_session_request *)
    revoke_session : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "login" -> h.login payload
    | "complete" -> h.complete payload
    | "refresh" -> h.refresh payload
    | "logout" -> h.logout payload
    | "me" -> h.me payload
    | "begin-cli-login" -> h.begin_cli_login payload
    | "inspect-cli-login" -> h.inspect_cli_login payload
    | "approve-cli-login" -> h.approve_cli_login payload
    | "deny-cli-login" -> h.deny_cli_login payload
    | "exchange-cli-login" -> h.exchange_cli_login payload
    | "refresh-session" -> h.refresh_session payload
    | "list-sessions" -> h.list_sessions payload
    | "revoke-session" -> h.revoke_session payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Dev_auth_service = struct
  type handler = {
    (* request payload decodes to: empty_request *)
    list_dev_users : bytes -> outcome;
    (* request payload decodes to: dev_login_request *)
    dev_login : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "list-dev-users" -> h.list_dev_users payload
    | "dev-login" -> h.dev_login payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module House_service = struct
  type handler = {
    (* request payload decodes to: house *)
    create_house : bytes -> outcome;
    (* request payload decodes to: house_id *)
    get_house : bytes -> outcome;
    (* request payload decodes to: house *)
    update_house : bytes -> outcome;
    (* request payload decodes to: house_id *)
    delete_house : bytes -> outcome;
    (* request payload decodes to: house_list_request *)
    list_houses : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-house" -> h.create_house payload
    | "get-house" -> h.get_house payload
    | "update-house" -> h.update_house payload
    | "delete-house" -> h.delete_house payload
    | "list-houses" -> h.list_houses payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Member_service = struct
  type handler = {
    (* request payload decodes to: member *)
    create_member : bytes -> outcome;
    (* request payload decodes to: member_id *)
    get_member : bytes -> outcome;
    (* request payload decodes to: member *)
    get_member_by_identity : bytes -> outcome;
    (* request payload decodes to: member *)
    update_member : bytes -> outcome;
    (* request payload decodes to: member_id *)
    deactivate_member : bytes -> outcome;
    (* request payload decodes to: member_id *)
    reactivate_member : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_members : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-member" -> h.create_member payload
    | "get-member" -> h.get_member payload
    | "get-member-by-identity" -> h.get_member_by_identity payload
    | "update-member" -> h.update_member payload
    | "deactivate-member" -> h.deactivate_member payload
    | "reactivate-member" -> h.reactivate_member payload
    | "list-members" -> h.list_members payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Trusted_domain_service = struct
  type handler = {
    (* request payload decodes to: trusted_domain *)
    add_trusted_domain : bytes -> outcome;
    (* request payload decodes to: trusted_domain_id *)
    remove_trusted_domain : bytes -> outcome;
    (* request payload decodes to: house_id *)
    list_trusted_domains : bytes -> outcome;
    (* request payload decodes to: trusted_domain *)
    is_domain_trusted : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "add-trusted-domain" -> h.add_trusted_domain payload
    | "remove-trusted-domain" -> h.remove_trusted_domain payload
    | "list-trusted-domains" -> h.list_trusted_domains payload
    | "is-domain-trusted" -> h.is_domain_trusted payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Role_service = struct
  type handler = {
    (* request payload decodes to: role *)
    create_role : bytes -> outcome;
    (* request payload decodes to: role *)
    update_role : bytes -> outcome;
    (* request payload decodes to: role_id *)
    delete_role : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_roles : bytes -> outcome;
    (* request payload decodes to: member_role_ref *)
    grant_role : bytes -> outcome;
    (* request payload decodes to: member_role_ref *)
    revoke_role : bytes -> outcome;
    (* request payload decodes to: member_scoped_list_request *)
    list_member_roles : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-role" -> h.create_role payload
    | "update-role" -> h.update_role payload
    | "delete-role" -> h.delete_role payload
    | "list-roles" -> h.list_roles payload
    | "grant-role" -> h.grant_role payload
    | "revoke-role" -> h.revoke_role payload
    | "list-member-roles" -> h.list_member_roles payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Skill_service = struct
  type handler = {
    (* request payload decodes to: skill *)
    create_skill : bytes -> outcome;
    (* request payload decodes to: skill *)
    update_skill : bytes -> outcome;
    (* request payload decodes to: skill_id *)
    delete_skill : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_skills : bytes -> outcome;
    (* request payload decodes to: member_skill_ref *)
    add_member_skill : bytes -> outcome;
    (* request payload decodes to: member_skill_ref *)
    remove_member_skill : bytes -> outcome;
    (* request payload decodes to: member_scoped_list_request *)
    list_member_skills : bytes -> outcome;
    (* request payload decodes to: group_skill_ref *)
    add_group_skill : bytes -> outcome;
    (* request payload decodes to: group_skill_ref *)
    remove_group_skill : bytes -> outcome;
    (* request payload decodes to: group_id *)
    list_group_skills : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-skill" -> h.create_skill payload
    | "update-skill" -> h.update_skill payload
    | "delete-skill" -> h.delete_skill payload
    | "list-skills" -> h.list_skills payload
    | "add-member-skill" -> h.add_member_skill payload
    | "remove-member-skill" -> h.remove_member_skill payload
    | "list-member-skills" -> h.list_member_skills payload
    | "add-group-skill" -> h.add_group_skill payload
    | "remove-group-skill" -> h.remove_group_skill payload
    | "list-group-skills" -> h.list_group_skills payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Group_service = struct
  type handler = {
    (* request payload decodes to: group *)
    create_group : bytes -> outcome;
    (* request payload decodes to: group *)
    update_group : bytes -> outcome;
    (* request payload decodes to: group_id *)
    delete_group : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_groups : bytes -> outcome;
    (* request payload decodes to: group_member_ref *)
    add_group_member : bytes -> outcome;
    (* request payload decodes to: group_member_ref *)
    remove_group_member : bytes -> outcome;
    (* request payload decodes to: member_scoped_list_request *)
    list_group_members : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-group" -> h.create_group payload
    | "update-group" -> h.update_group payload
    | "delete-group" -> h.delete_group payload
    | "list-groups" -> h.list_groups payload
    | "add-group-member" -> h.add_group_member payload
    | "remove-group-member" -> h.remove_group_member payload
    | "list-group-members" -> h.list_group_members payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Project_service = struct
  type handler = {
    (* request payload decodes to: project *)
    create_project : bytes -> outcome;
    (* request payload decodes to: project_id *)
    get_project : bytes -> outcome;
    (* request payload decodes to: project *)
    update_project : bytes -> outcome;
    (* request payload decodes to: project_id *)
    delete_project : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_projects : bytes -> outcome;
    (* request payload decodes to: project_scoped_list_request *)
    list_project_tasks : bytes -> outcome;
    (* request payload decodes to: project_task_order_request *)
    add_project_task : bytes -> outcome;
    (* request payload decodes to: project_task_ref *)
    remove_project_task : bytes -> outcome;
    (* request payload decodes to: project_task_order_request *)
    set_project_task_position : bytes -> outcome;
    (* request payload decodes to: project_id *)
    list_project_members : bytes -> outcome;
    (* request payload decodes to: project_member_ref *)
    add_project_member : bytes -> outcome;
    (* request payload decodes to: project_member_ref *)
    remove_project_member : bytes -> outcome;
    (* request payload decodes to: project_id *)
    list_project_owners : bytes -> outcome;
    (* request payload decodes to: project_owner_ref *)
    add_project_owner : bytes -> outcome;
    (* request payload decodes to: project_owner_ref *)
    remove_project_owner : bytes -> outcome;
    (* request payload decodes to: project_id *)
    list_milestones : bytes -> outcome;
    (* request payload decodes to: milestone *)
    create_milestone : bytes -> outcome;
    (* request payload decodes to: milestone *)
    update_milestone : bytes -> outcome;
    (* request payload decodes to: milestone_id *)
    delete_milestone : bytes -> outcome;
    (* request payload decodes to: set_project_visibility_request *)
    set_project_visibility : bytes -> outcome;
    (* request payload decodes to: project_id *)
    list_project_grants : bytes -> outcome;
    (* request payload decodes to: put_project_grant_request *)
    put_project_grant : bytes -> outcome;
    (* request payload decodes to: project_grant_ref *)
    delete_project_grant : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-project" -> h.create_project payload
    | "get-project" -> h.get_project payload
    | "update-project" -> h.update_project payload
    | "delete-project" -> h.delete_project payload
    | "list-projects" -> h.list_projects payload
    | "list-project-tasks" -> h.list_project_tasks payload
    | "add-project-task" -> h.add_project_task payload
    | "remove-project-task" -> h.remove_project_task payload
    | "set-project-task-position" -> h.set_project_task_position payload
    | "list-project-members" -> h.list_project_members payload
    | "add-project-member" -> h.add_project_member payload
    | "remove-project-member" -> h.remove_project_member payload
    | "list-project-owners" -> h.list_project_owners payload
    | "add-project-owner" -> h.add_project_owner payload
    | "remove-project-owner" -> h.remove_project_owner payload
    | "list-milestones" -> h.list_milestones payload
    | "create-milestone" -> h.create_milestone payload
    | "update-milestone" -> h.update_milestone payload
    | "delete-milestone" -> h.delete_milestone payload
    | "set-project-visibility" -> h.set_project_visibility payload
    | "list-project-grants" -> h.list_project_grants payload
    | "put-project-grant" -> h.put_project_grant payload
    | "delete-project-grant" -> h.delete_project_grant payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Event_service = struct
  type handler = {
    (* request payload decodes to: event *)
    create_event : bytes -> outcome;
    (* request payload decodes to: event_id *)
    get_event : bytes -> outcome;
    (* request payload decodes to: event *)
    update_event : bytes -> outcome;
    (* request payload decodes to: event_id *)
    delete_event : bytes -> outcome;
    (* request payload decodes to: event_id *)
    delete_event_and_future : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_events : bytes -> outcome;
    (* request payload decodes to: house_id *)
    get_calendar_view : bytes -> outcome;
    (* request payload decodes to: calendar_view *)
    set_calendar_view : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-event" -> h.create_event payload
    | "get-event" -> h.get_event payload
    | "update-event" -> h.update_event payload
    | "delete-event" -> h.delete_event payload
    | "delete-event-and-future" -> h.delete_event_and_future payload
    | "list-events" -> h.list_events payload
    | "get-calendar-view" -> h.get_calendar_view payload
    | "set-calendar-view" -> h.set_calendar_view payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Task_service = struct
  type handler = {
    (* request payload decodes to: task *)
    create_task : bytes -> outcome;
    (* request payload decodes to: task_id *)
    get_task : bytes -> outcome;
    (* request payload decodes to: task *)
    update_task : bytes -> outcome;
    (* request payload decodes to: task_id *)
    delete_task : bytes -> outcome;
    (* request payload decodes to: house_scoped_list_request *)
    list_tasks : bytes -> outcome;
    (* request payload decodes to: set_task_visibility_request *)
    set_task_visibility : bytes -> outcome;
    (* request payload decodes to: task_id *)
    list_task_grants : bytes -> outcome;
    (* request payload decodes to: put_task_grant_request *)
    put_task_grant : bytes -> outcome;
    (* request payload decodes to: task_grant_ref *)
    delete_task_grant : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-task" -> h.create_task payload
    | "get-task" -> h.get_task payload
    | "update-task" -> h.update_task payload
    | "delete-task" -> h.delete_task payload
    | "list-tasks" -> h.list_tasks payload
    | "set-task-visibility" -> h.set_task_visibility payload
    | "list-task-grants" -> h.list_task_grants payload
    | "put-task-grant" -> h.put_task_grant payload
    | "delete-task-grant" -> h.delete_task_grant payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Dependency_service = struct
  type handler = {
    (* request payload decodes to: dependency_ref *)
    add_dependency : bytes -> outcome;
    (* request payload decodes to: dependency_ref *)
    remove_dependency : bytes -> outcome;
    (* request payload decodes to: dependency_target *)
    get_dependencies : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "add-dependency" -> h.add_dependency payload
    | "remove-dependency" -> h.remove_dependency payload
    | "get-dependencies" -> h.get_dependencies payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Comment_service = struct
  type handler = {
    (* request payload decodes to: comment *)
    create_comment : bytes -> outcome;
    (* request payload decodes to: comment_id *)
    get_comment : bytes -> outcome;
    (* request payload decodes to: comment *)
    update_comment : bytes -> outcome;
    (* request payload decodes to: comment_id *)
    delete_comment : bytes -> outcome;
    (* request payload decodes to: comment_list_request *)
    list_comments : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-comment" -> h.create_comment payload
    | "get-comment" -> h.get_comment payload
    | "update-comment" -> h.update_comment payload
    | "delete-comment" -> h.delete_comment payload
    | "list-comments" -> h.list_comments payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Notification_service = struct
  type handler = {
    (* request payload decodes to: notification_list_request *)
    list_notifications : bytes -> outcome;
    (* request payload decodes to: house_id *)
    unread_count : bytes -> outcome;
    (* request payload decodes to: notification_id *)
    mark_read : bytes -> outcome;
    (* request payload decodes to: house_id *)
    mark_all_read : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "list-notifications" -> h.list_notifications payload
    | "unread-count" -> h.unread_count payload
    | "mark-read" -> h.mark_read payload
    | "mark-all-read" -> h.mark_all_read payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Share_service = struct
  type handler = {
    (* request payload decodes to: share *)
    create_share : bytes -> outcome;
    (* request payload decodes to: share_id *)
    delete_share : bytes -> outcome;
    (* request payload decodes to: resource_ref *)
    list_shares_by_resource : bytes -> outcome;
    (* request payload decodes to: share_access_request *)
    check_access : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "create-share" -> h.create_share payload
    | "delete-share" -> h.delete_share payload
    | "list-shares-by-resource" -> h.list_shares_by_resource payload
    | "check-access" -> h.check_access payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Member_audit_service = struct
  type handler = {
    (* request payload decodes to: member_scoped_list_request *)
    list_audits_for_member : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "list-audits-for-member" -> h.list_audits_for_member payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Settings_service = struct
  type handler = {
    (* request payload decodes to: house_id *)
    get_settings : bytes -> outcome;
    (* request payload decodes to: update_settings_request *)
    update_settings : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "get-settings" -> h.get_settings payload
    | "update-settings" -> h.update_settings payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Bug_service = struct
  type handler = {
    (* request payload decodes to: bug_report_request *)
    report_bug : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "report-bug" -> h.report_bug payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Audit_service = struct
  type handler = {
    (* request payload decodes to: audit_query *)
    query_audit : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "query-audit" -> h.query_audit payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end

module Trash_service = struct
  type handler = {
    (* request payload decodes to: house_scoped_list_request *)
    list_trash : bytes -> outcome;
    (* request payload decodes to: restore_request *)
    restore : bytes -> outcome;
    (* request payload decodes to: purge_request *)
    purge : bytes -> outcome;
  }

  (* Verbose router: dispatch one request by operation name to its handler
     field, which decodes the opaque payload with the generated [Types]. *)
  let route (h : handler) ~(op : string) ~(payload : bytes) =
    match op with
    | "list-trash" -> h.list_trash payload
    | "restore" -> h.restore payload
    | "purge" -> h.purge payload
    | other -> transport_error ~status:2L ~message:("unknown op: " ^ other)
end
