apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "longhouse.fullname" . }}
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
data:
  LONGHOUSE_API_PORT: {{ .Values.server.apiPort | quote }}
  LONGHOUSE_TCP_PORT: {{ .Values.server.tcpPort | quote }}
  {{- if .Values.server.linkkeysDomain }}
  LONGHOUSE_LINKKEYS_DOMAIN: {{ .Values.server.linkkeysDomain | quote }}
  {{- end }}
  {{- if .Values.server.linkkeysUrl }}
  LONGHOUSE_LINKKEYS_URL: {{ .Values.server.linkkeysUrl | quote }}
  {{- end }}
  {{- if .Values.server.initialAdmin.domain }}
  LONGHOUSE_INITIAL_ADMIN_DOMAIN: {{ .Values.server.initialAdmin.domain | quote }}
  {{- end }}
  {{- if .Values.server.initialAdmin.userId }}
  LONGHOUSE_INITIAL_ADMIN_USER_ID: {{ .Values.server.initialAdmin.userId | quote }}
  {{- end }}
  {{- if .Values.server.initialHouseName }}
  LONGHOUSE_INITIAL_HOUSE_NAME: {{ .Values.server.initialHouseName | quote }}
  {{- end }}
  {{- if .Values.linkkeysRp.enabled }}
  LONGHOUSE_LINKKEYS_PKI_URL: "https://{{ include "longhouse.fullname" . }}-linkkeys-rp:{{ .Values.linkkeysRp.port }}"
  {{- else if .Values.linkkeysRp.url }}
  LONGHOUSE_LINKKEYS_PKI_URL: {{ .Values.linkkeysRp.url | quote }}
  {{- end }}
  {{- if .Values.linkkeysRp.allowInvalidCerts }}
  LONGHOUSE_LINKKEYS_PKI_ALLOW_INVALID_CERTS: "true"
  {{- end }}
  {{- if .Values.linkkeysRp.transport }}
  LONGHOUSE_LINKKEYS_TRANSPORT: {{ .Values.linkkeysRp.transport | quote }}
  {{- end }}
  {{- if .Values.linkkeysRp.tcpAddr }}
  LONGHOUSE_LINKKEYS_TCP_ADDR: {{ .Values.linkkeysRp.tcpAddr | quote }}
  {{- end }}
  {{- if .Values.linkkeysRp.tcpFingerprints }}
  LONGHOUSE_LINKKEYS_TCP_FINGERPRINTS: {{ .Values.linkkeysRp.tcpFingerprints | quote }}
  {{- end }}
  {{- if .Values.linkkeysRp.tcpAllowInsecure }}
  LONGHOUSE_LINKKEYS_TCP_ALLOW_INSECURE: "true"
  {{- end }}
  {{- if .Values.server.linkkeysIdpDomain }}
  LONGHOUSE_LINKKEYS_IDP_DOMAIN: {{ .Values.server.linkkeysIdpDomain | quote }}
  {{- end }}
  {{- if .Values.server.linkkeysIdpUrl }}
  LONGHOUSE_LINKKEYS_IDP_URL: {{ .Values.server.linkkeysIdpUrl | quote }}
  {{- end }}
  {{- if .Values.server.appCallbackUrl }}
  LONGHOUSE_APP_CALLBACK_URL: {{ .Values.server.appCallbackUrl | quote }}
  {{- end }}
  {{- if .Values.server.env }}
  LONGHOUSE_ENV: {{ .Values.server.env | quote }}
  {{- end }}
  {{- if .Values.server.devAuthEnabled }}
  LONGHOUSE_DEV_AUTH_ENABLED: "true"
  {{- end }}
