apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "longhouse.fullname" . }}
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
data:
  LONGHOUSE_API_PORT: {{ .Values.server.apiPort | quote }}
  LONGHOUSE_TCP_PORT: {{ .Values.server.tcpPort | quote }}
  {{- if .Values.server.linkkeysDomain }}
  LONGHOUSE_LINKKEYS_DOMAIN: {{ .Values.server.linkkeysDomain | quote }}
  {{- end }}
  {{- if .Values.server.linkkeysUrl }}
  LONGHOUSE_LINKKEYS_URL: {{ .Values.server.linkkeysUrl | quote }}
  {{- end }}
  {{- if .Values.server.initialAdmin.domain }}
  LONGHOUSE_INITIAL_ADMIN_DOMAIN: {{ .Values.server.initialAdmin.domain | quote }}
  {{- end }}
  {{- if .Values.server.initialAdmin.userId }}
  LONGHOUSE_INITIAL_ADMIN_USER_ID: {{ .Values.server.initialAdmin.userId | quote }}
  {{- end }}
  {{- if .Values.server.initialHouseName }}
  LONGHOUSE_INITIAL_HOUSE_NAME: {{ .Values.server.initialHouseName | quote }}
  {{- end }}
