{{- if .Values.ingress.api.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "longhouse.fullname" . }}-api
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
  {{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.api.className }}
  ingressClassName: {{ .Values.ingress.api.className }}
  {{- end }}
  {{- if .Values.ingress.api.tls }}
  tls:
    {{- range .Values.ingress.api.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.api.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "longhouse.fullname" $ }}-api
                port:
                  number: {{ $.Values.service.api.httpPort }}
          {{- end }}
    {{- end }}
{{- end }}
