apiVersion: v1
kind: Secret
metadata:
  name: {{ include "longhouse.fullname" . }}
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.postgresql.enabled }}
  LONGHOUSE_DB_URI: {{ .Values.database.url | quote }}
  {{- end }}
