apiVersion: v1
kind: Secret
metadata:
  name: {{ include "longhouse.fullname" . }}
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.postgresql.enabled }}
  LONGHOUSE_DB_URI: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if .Values.webapp.sessionSecret }}
  LONGHOUSE_SESSION_SECRET: {{ .Values.webapp.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.linkkeysRp.apiKey }}
  LONGHOUSE_LINKKEYS_PKI_API_KEY: {{ .Values.linkkeysRp.apiKey | quote }}
  {{- end }}
  {{- if .Values.api.jwtSecret }}
  LONGHOUSE_JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
  {{- end }}
