apiVersion: v1
kind: Service
metadata:
  name: {{ include "longhouse.fullname" . }}-web
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "longhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
