apiVersion: v1
kind: Service
metadata:
  name: {{ include "longhouse.fullname" . }}-api
  labels:
    {{- include "longhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "longhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
