# Code generated by csilgen; DO NOT EDIT.

defmodule Csilgen.Generated.AuthServer do
  @moduledoc "Server handler behaviour + routers for the AuthService service."

  @callback login(req :: Csilgen.Generated.LoginRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.LoginResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback complete(req :: Csilgen.Generated.CompleteRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.LoginResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback refresh(req :: Csilgen.Generated.EmptyRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.LoginResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback logout(req :: Csilgen.Generated.EmptyRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback me(req :: Csilgen.Generated.EmptyRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.MeResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.DevAuthServer do
  @moduledoc "Server handler behaviour + routers for the DevAuthService service."

  @callback list_dev_users(req :: Csilgen.Generated.EmptyRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.DevUsersResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback dev_login(req :: Csilgen.Generated.DevLoginRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.LoginResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.HouseServer do
  @moduledoc "Server handler behaviour + routers for the HouseService service."

  @callback create_house(req :: Csilgen.Generated.House.t(), ctx :: map()) :: {:ok, Csilgen.Generated.House.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_house(req :: Csilgen.Generated.HouseID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.House.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_house(req :: Csilgen.Generated.House.t(), ctx :: map()) :: {:ok, Csilgen.Generated.House.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_house(req :: Csilgen.Generated.HouseID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_houses(req :: Csilgen.Generated.HouseListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.House.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.MemberServer do
  @moduledoc "Server handler behaviour + routers for the MemberService service."

  @callback create_member(req :: Csilgen.Generated.Member.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Member.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_member(req :: Csilgen.Generated.MemberID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Member.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_member_by_identity(req :: Csilgen.Generated.Member.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Member.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_member(req :: Csilgen.Generated.Member.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Member.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback deactivate_member(req :: Csilgen.Generated.MemberID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback reactivate_member(req :: Csilgen.Generated.MemberID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_members(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Member.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.TrustedDomainServer do
  @moduledoc "Server handler behaviour + routers for the TrustedDomainService service."

  @callback add_trusted_domain(req :: Csilgen.Generated.TrustedDomain.t(), ctx :: map()) :: {:ok, Csilgen.Generated.TrustedDomain.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_trusted_domain(req :: Csilgen.Generated.TrustedDomainID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_trusted_domains(req :: Csilgen.Generated.HouseID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.TrustedDomain.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback is_domain_trusted(req :: Csilgen.Generated.TrustedDomain.t(), ctx :: map()) :: {:ok, Csilgen.Generated.BoolResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.RoleServer do
  @moduledoc "Server handler behaviour + routers for the RoleService service."

  @callback create_role(req :: Csilgen.Generated.Role.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Role.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_role(req :: Csilgen.Generated.Role.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Role.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_role(req :: Csilgen.Generated.RoleID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_roles(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Role.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback grant_role(req :: Csilgen.Generated.MemberRoleRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback revoke_role(req :: Csilgen.Generated.MemberRoleRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_member_roles(req :: Csilgen.Generated.MemberScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Role.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.SkillServer do
  @moduledoc "Server handler behaviour + routers for the SkillService service."

  @callback create_skill(req :: Csilgen.Generated.Skill.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Skill.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_skill(req :: Csilgen.Generated.Skill.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Skill.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_skill(req :: Csilgen.Generated.SkillID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_skills(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Skill.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback add_member_skill(req :: Csilgen.Generated.MemberSkillRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_member_skill(req :: Csilgen.Generated.MemberSkillRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_member_skills(req :: Csilgen.Generated.MemberScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Skill.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback add_group_skill(req :: Csilgen.Generated.GroupSkillRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_group_skill(req :: Csilgen.Generated.GroupSkillRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_group_skills(req :: Csilgen.Generated.GroupID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Skill.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.GroupServer do
  @moduledoc "Server handler behaviour + routers for the GroupService service."

  @callback create_group(req :: Csilgen.Generated.Group.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Group.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_group(req :: Csilgen.Generated.Group.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Group.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_group(req :: Csilgen.Generated.GroupID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_groups(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Group.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback add_group_member(req :: Csilgen.Generated.GroupMemberRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_group_member(req :: Csilgen.Generated.GroupMemberRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_group_members(req :: Csilgen.Generated.MemberScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Member.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.ProjectServer do
  @moduledoc "Server handler behaviour + routers for the ProjectService service."

  @callback create_project(req :: Csilgen.Generated.Project.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Project.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_project(req :: Csilgen.Generated.ProjectID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Project.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_project(req :: Csilgen.Generated.Project.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Project.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_project(req :: Csilgen.Generated.ProjectID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_projects(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.ProjectList.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_project_tasks(req :: Csilgen.Generated.ProjectScopedListRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.TaskList.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback add_project_task(req :: Csilgen.Generated.ProjectTaskOrderRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_project_task(req :: Csilgen.Generated.ProjectTaskRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback set_project_task_position(req :: Csilgen.Generated.ProjectTaskOrderRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_project_members(req :: Csilgen.Generated.ProjectID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Member.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback add_project_member(req :: Csilgen.Generated.ProjectMemberRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_project_member(req :: Csilgen.Generated.ProjectMemberRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_project_owners(req :: Csilgen.Generated.ProjectID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Member.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback add_project_owner(req :: Csilgen.Generated.ProjectOwnerRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_project_owner(req :: Csilgen.Generated.ProjectOwnerRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_milestones(req :: Csilgen.Generated.ProjectID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Milestone.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback create_milestone(req :: Csilgen.Generated.Milestone.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Milestone.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_milestone(req :: Csilgen.Generated.Milestone.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Milestone.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_milestone(req :: Csilgen.Generated.MilestoneID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback set_project_visibility(req :: Csilgen.Generated.SetProjectVisibilityRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Project.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_project_grants(req :: Csilgen.Generated.ProjectID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Grant.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback put_project_grant(req :: Csilgen.Generated.PutProjectGrantRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_project_grant(req :: Csilgen.Generated.ProjectGrantRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.EventServer do
  @moduledoc "Server handler behaviour + routers for the EventService service."

  @callback create_event(req :: Csilgen.Generated.Event.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Event.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_event(req :: Csilgen.Generated.EventID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Event.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_event(req :: Csilgen.Generated.Event.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Event.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_event(req :: Csilgen.Generated.EventID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_event_and_future(req :: Csilgen.Generated.EventID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_events(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Event.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.TaskServer do
  @moduledoc "Server handler behaviour + routers for the TaskService service."

  @callback create_task(req :: Csilgen.Generated.Task.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Task.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_task(req :: Csilgen.Generated.TaskID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Task.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_task(req :: Csilgen.Generated.Task.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Task.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_task(req :: Csilgen.Generated.TaskID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_tasks(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.TaskList.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback set_task_visibility(req :: Csilgen.Generated.SetTaskVisibilityRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Task.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_task_grants(req :: Csilgen.Generated.TaskID.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Grant.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback put_task_grant(req :: Csilgen.Generated.PutTaskGrantRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_task_grant(req :: Csilgen.Generated.TaskGrantRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.DependencyServer do
  @moduledoc "Server handler behaviour + routers for the DependencyService service."

  @callback add_dependency(req :: Csilgen.Generated.DependencyRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback remove_dependency(req :: Csilgen.Generated.DependencyRef.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_dependencies(req :: Csilgen.Generated.DependencyTarget.t(), ctx :: map()) :: {:ok, Csilgen.Generated.DependencyGraph.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.CommentServer do
  @moduledoc "Server handler behaviour + routers for the CommentService service."

  @callback create_comment(req :: Csilgen.Generated.Comment.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Comment.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback get_comment(req :: Csilgen.Generated.CommentID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Comment.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_comment(req :: Csilgen.Generated.Comment.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Comment.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_comment(req :: Csilgen.Generated.CommentID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_comments(req :: Csilgen.Generated.CommentListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Comment.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.NotificationServer do
  @moduledoc "Server handler behaviour + routers for the NotificationService service."

  @callback list_notifications(req :: Csilgen.Generated.NotificationListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Notification.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback unread_count(req :: Csilgen.Generated.HouseID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.NotificationUnreadCount.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback mark_read(req :: Csilgen.Generated.NotificationID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Notification.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback mark_all_read(req :: Csilgen.Generated.HouseID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.ShareServer do
  @moduledoc "Server handler behaviour + routers for the ShareService service."

  @callback create_share(req :: Csilgen.Generated.Share.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Share.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback delete_share(req :: Csilgen.Generated.ShareID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback list_shares_by_resource(req :: Csilgen.Generated.ResourceRef.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.Share.t()]} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback check_access(req :: Csilgen.Generated.ShareAccessRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Share.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.MemberAuditServer do
  @moduledoc "Server handler behaviour + routers for the MemberAuditService service."

  @callback list_audits_for_member(req :: Csilgen.Generated.MemberScopedListRequest.t(), ctx :: map()) :: {:ok, [Csilgen.Generated.MemberAudit.t()]} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.SettingsServer do
  @moduledoc "Server handler behaviour + routers for the SettingsService service."

  @callback get_settings(req :: Csilgen.Generated.HouseID.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EffectiveSettings.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback update_settings(req :: Csilgen.Generated.UpdateSettingsRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EffectiveSettings.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.BugServer do
  @moduledoc "Server handler behaviour + routers for the BugService service."

  @callback report_bug(req :: Csilgen.Generated.BugReportRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.Task.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.AuditServer do
  @moduledoc "Server handler behaviour + routers for the AuditService service."

  @callback query_audit(req :: Csilgen.Generated.AuditQuery.t(), ctx :: map()) :: {:ok, Csilgen.Generated.AuditPage.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

defmodule Csilgen.Generated.TrashServer do
  @moduledoc "Server handler behaviour + routers for the TrashService service."

  @callback list_trash(req :: Csilgen.Generated.HouseScopedListRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.TrashPage.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback restore(req :: Csilgen.Generated.RestoreRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}
  @callback purge(req :: Csilgen.Generated.PurgeRequest.t(), ctx :: map()) :: {:ok, Csilgen.Generated.EmptyResponse.t()} | {:error, Csilgen.Generated.ServiceError.t()}

end

