# Code generated by csilgen; DO NOT EDIT.

defmodule Csilgen.Generated.Validation do
  @moduledoc "Generated validators from CSIL constraints."

  @spec validate_house(Csilgen.Generated.House.t()) :: :ok | {:error, String.t()}
  def validate_house(%Csilgen.Generated.House{} = v) do
    with :ok <- (if String.length(v.name) >= 1, do: :ok, else: {:error, "field 'name' must have at least 1 elements"}),
         :ok <- (if String.length(v.name) <= 256, do: :ok, else: {:error, "field 'name' must have at most 256 elements"}) do
      :ok
    end
  end

  @spec validate_role(Csilgen.Generated.Role.t()) :: :ok | {:error, String.t()}
  def validate_role(%Csilgen.Generated.Role{} = v) do
    with :ok <- (if String.length(v.name) >= 1, do: :ok, else: {:error, "field 'name' must have at least 1 elements"}),
         :ok <- (if String.length(v.name) <= 128, do: :ok, else: {:error, "field 'name' must have at most 128 elements"}) do
      :ok
    end
  end

  @spec validate_skill(Csilgen.Generated.Skill.t()) :: :ok | {:error, String.t()}
  def validate_skill(%Csilgen.Generated.Skill{} = v) do
    with :ok <- (if String.length(v.name) >= 1, do: :ok, else: {:error, "field 'name' must have at least 1 elements"}),
         :ok <- (if String.length(v.name) <= 256, do: :ok, else: {:error, "field 'name' must have at most 256 elements"}) do
      :ok
    end
  end

  @spec validate_group(Csilgen.Generated.Group.t()) :: :ok | {:error, String.t()}
  def validate_group(%Csilgen.Generated.Group{} = v) do
    with :ok <- (if String.length(v.name) >= 1, do: :ok, else: {:error, "field 'name' must have at least 1 elements"}),
         :ok <- (if String.length(v.name) <= 256, do: :ok, else: {:error, "field 'name' must have at most 256 elements"}) do
      :ok
    end
  end

  @spec validate_project(Csilgen.Generated.Project.t()) :: :ok | {:error, String.t()}
  def validate_project(%Csilgen.Generated.Project{} = v) do
    with :ok <- (if String.length(v.name) >= 1, do: :ok, else: {:error, "field 'name' must have at least 1 elements"}),
         :ok <- (if String.length(v.name) <= 256, do: :ok, else: {:error, "field 'name' must have at most 256 elements"}) do
      :ok
    end
  end

  @spec validate_milestone(Csilgen.Generated.Milestone.t()) :: :ok | {:error, String.t()}
  def validate_milestone(%Csilgen.Generated.Milestone{} = v) do
    with :ok <- (if String.length(v.label) >= 1, do: :ok, else: {:error, "field 'label' must have at least 1 elements"}),
         :ok <- (if String.length(v.label) <= 256, do: :ok, else: {:error, "field 'label' must have at most 256 elements"}) do
      :ok
    end
  end

  @spec validate_event(Csilgen.Generated.Event.t()) :: :ok | {:error, String.t()}
  def validate_event(%Csilgen.Generated.Event{} = v) do
    with :ok <- (if String.length(v.title) >= 1, do: :ok, else: {:error, "field 'title' must have at least 1 elements"}),
         :ok <- (if String.length(v.title) <= 512, do: :ok, else: {:error, "field 'title' must have at most 512 elements"}) do
      :ok
    end
  end

  @spec validate_task(Csilgen.Generated.Task.t()) :: :ok | {:error, String.t()}
  def validate_task(%Csilgen.Generated.Task{} = v) do
    with :ok <- (if String.length(v.title) >= 1, do: :ok, else: {:error, "field 'title' must have at least 1 elements"}),
         :ok <- (if String.length(v.title) <= 512, do: :ok, else: {:error, "field 'title' must have at most 512 elements"}) do
      :ok
    end
  end

  @spec validate_comment(Csilgen.Generated.Comment.t()) :: :ok | {:error, String.t()}
  def validate_comment(%Csilgen.Generated.Comment{} = v) do
    with :ok <- (if String.length(v.body) >= 1, do: :ok, else: {:error, "field 'body' must have at least 1 elements"}),
         :ok <- (if String.length(v.body) <= 10000, do: :ok, else: {:error, "field 'body' must have at most 10000 elements"}) do
      :ok
    end
  end

  @spec validate_bug_report_request(Csilgen.Generated.BugReportRequest.t()) :: :ok | {:error, String.t()}
  def validate_bug_report_request(%Csilgen.Generated.BugReportRequest{} = v) do
    with :ok <- (if String.length(v.title) >= 1, do: :ok, else: {:error, "field 'title' must have at least 1 elements"}),
         :ok <- (if String.length(v.title) <= 512, do: :ok, else: {:error, "field 'title' must have at most 512 elements"}) do
      :ok
    end
  end

end
