// Package api contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"context"
)

// AuthService defines the service interface
type AuthService interface {
	Login(ctx context.Context, req LoginRequest) (interface{}, error)
	Complete(ctx context.Context, req CompleteRequest) (interface{}, error)
	Refresh(ctx context.Context, req EmptyRequest) (interface{}, error)
	Me(ctx context.Context, req EmptyRequest) (interface{}, error)
}

// HouseService defines the service interface
type HouseService interface {
	CreateHouse(ctx context.Context, req House) (interface{}, error)
	GetHouse(ctx context.Context, req HouseID) (interface{}, error)
	UpdateHouse(ctx context.Context, req House) (interface{}, error)
	DeleteHouse(ctx context.Context, req HouseID) (interface{}, error)
	ListHouses(ctx context.Context, req HouseListRequest) (interface{}, error)
}

// MemberService defines the service interface
type MemberService interface {
	CreateMember(ctx context.Context, req Member) (interface{}, error)
	GetMember(ctx context.Context, req MemberID) (interface{}, error)
	GetMemberByIdentity(ctx context.Context, req Member) (interface{}, error)
	UpdateMember(ctx context.Context, req Member) (interface{}, error)
	DeleteMember(ctx context.Context, req MemberID) (interface{}, error)
	ListMembers(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
}

// TrustedDomainService defines the service interface
type TrustedDomainService interface {
	AddTrustedDomain(ctx context.Context, req TrustedDomain) (interface{}, error)
	RemoveTrustedDomain(ctx context.Context, req TrustedDomainID) (interface{}, error)
	ListTrustedDomains(ctx context.Context, req HouseID) (interface{}, error)
	IsDomainTrusted(ctx context.Context, req TrustedDomain) (interface{}, error)
}

// RoleService defines the service interface
type RoleService interface {
	CreateRole(ctx context.Context, req Role) (interface{}, error)
	UpdateRole(ctx context.Context, req Role) (interface{}, error)
	DeleteRole(ctx context.Context, req RoleID) (interface{}, error)
	ListRoles(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
	GrantRole(ctx context.Context, req MemberRoleRef) (interface{}, error)
	RevokeRole(ctx context.Context, req MemberRoleRef) (interface{}, error)
	ListMemberRoles(ctx context.Context, req MemberScopedListRequest) (interface{}, error)
}

// SkillService defines the service interface
type SkillService interface {
	CreateSkill(ctx context.Context, req Skill) (interface{}, error)
	UpdateSkill(ctx context.Context, req Skill) (interface{}, error)
	DeleteSkill(ctx context.Context, req SkillID) (interface{}, error)
	ListSkills(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
	AddMemberSkill(ctx context.Context, req MemberSkillRef) (interface{}, error)
	RemoveMemberSkill(ctx context.Context, req MemberSkillRef) (interface{}, error)
	ListMemberSkills(ctx context.Context, req MemberScopedListRequest) (interface{}, error)
}

// GroupService defines the service interface
type GroupService interface {
	CreateGroup(ctx context.Context, req Group) (interface{}, error)
	UpdateGroup(ctx context.Context, req Group) (interface{}, error)
	DeleteGroup(ctx context.Context, req GroupID) (interface{}, error)
	ListGroups(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
	AddGroupMember(ctx context.Context, req GroupMemberRef) (interface{}, error)
	RemoveGroupMember(ctx context.Context, req GroupMemberRef) (interface{}, error)
	ListGroupMembers(ctx context.Context, req MemberScopedListRequest) (interface{}, error)
}

// ProjectService defines the service interface
type ProjectService interface {
	CreateProject(ctx context.Context, req Project) (interface{}, error)
	UpdateProject(ctx context.Context, req Project) (interface{}, error)
	DeleteProject(ctx context.Context, req ProjectID) (interface{}, error)
	ListProjects(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
	ListProjectTasks(ctx context.Context, req ProjectScopedListRequest) (interface{}, error)
	AddProjectTask(ctx context.Context, req ProjectTaskOrderRequest) (interface{}, error)
	RemoveProjectTask(ctx context.Context, req ProjectTaskRef) (interface{}, error)
	SetProjectTaskPosition(ctx context.Context, req ProjectTaskOrderRequest) (interface{}, error)
}

// EventService defines the service interface
type EventService interface {
	CreateEvent(ctx context.Context, req Event) (interface{}, error)
	GetEvent(ctx context.Context, req EventID) (interface{}, error)
	UpdateEvent(ctx context.Context, req Event) (interface{}, error)
	DeleteEvent(ctx context.Context, req EventID) (interface{}, error)
	ListEvents(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
}

// TaskService defines the service interface
type TaskService interface {
	CreateTask(ctx context.Context, req Task) (interface{}, error)
	GetTask(ctx context.Context, req TaskID) (interface{}, error)
	UpdateTask(ctx context.Context, req Task) (interface{}, error)
	DeleteTask(ctx context.Context, req TaskID) (interface{}, error)
	ListTasks(ctx context.Context, req HouseScopedListRequest) (interface{}, error)
}

// CommentService defines the service interface
type CommentService interface {
	CreateComment(ctx context.Context, req Comment) (interface{}, error)
	GetComment(ctx context.Context, req CommentID) (interface{}, error)
	UpdateComment(ctx context.Context, req Comment) (interface{}, error)
	DeleteComment(ctx context.Context, req CommentID) (interface{}, error)
	ListComments(ctx context.Context, req CommentListRequest) (interface{}, error)
}

// ShareService defines the service interface
type ShareService interface {
	CreateShare(ctx context.Context, req Share) (interface{}, error)
	DeleteShare(ctx context.Context, req ShareID) (interface{}, error)
	ListSharesByResource(ctx context.Context, req ResourceRef) (interface{}, error)
	CheckAccess(ctx context.Context, req ShareAccessRequest) (interface{}, error)
}

// MemberAuditService defines the service interface
type MemberAuditService interface {
	ListAuditsForMember(ctx context.Context, req MemberScopedListRequest) (interface{}, error)
}
