// Package api contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

// HouseID is a type alias
type HouseID string

// MemberID is a type alias
type MemberID string

// RoleID is a type alias
type RoleID string

// SkillID is a type alias
type SkillID string

// GroupID is a type alias
type GroupID string

// ProjectID is a type alias
type ProjectID string

// EventID is a type alias
type EventID string

// TaskID is a type alias
type TaskID string

// CommentID is a type alias
type CommentID string

// ShareID is a type alias
type ShareID string

// TrustedDomainID is a type alias
type TrustedDomainID string

// MemberAuditID is a type alias
type MemberAuditID string

// MilestoneID is a type alias
type MilestoneID string

// Timestamp is a type alias
type Timestamp string

// TaskStatus is a type alias
type TaskStatus interface{}

// TargetType is a type alias
type TargetType interface{}

// AccessLevel is a type alias
type AccessLevel interface{}

// ResourceType is a type alias
type ResourceType interface{}

// ProjectStatus is a type alias
type ProjectStatus interface{}

// RecurrenceFreq is a type alias
type RecurrenceFreq interface{}

// MilestoneState is a type alias
type MilestoneState interface{}

// House represents a structured data type
type House struct {
	HouseId     HouseID   `json:"house_id" yaml:"house_id"`
	Name        string    `json:"name" yaml:"name"`
	Description *string   `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedAt   Timestamp `json:"created_at" yaml:"created_at"`
	UpdatedAt   Timestamp `json:"updated_at" yaml:"updated_at"`
}

// Member represents a structured data type
type Member struct {
	MemberId        MemberID   `json:"member_id" yaml:"member_id"`
	HouseId         HouseID    `json:"house_id" yaml:"house_id"`
	LinkkeysDomain  string     `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	LinkkeysUserId  string     `json:"linkkeys_user_id" yaml:"linkkeys_user_id"`
	DisplayName     *string    `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	CachedPublicKey *[]byte    `json:"cached_public_key,omitempty" yaml:"cached_public_key,omitempty"`
	CreatedAt       Timestamp  `json:"created_at" yaml:"created_at"`
	UpdatedAt       Timestamp  `json:"updated_at" yaml:"updated_at"`
	LastSeenAt      *Timestamp `json:"last_seen_at,omitempty" yaml:"last_seen_at,omitempty"`
}

// TrustedDomain represents a structured data type
type TrustedDomain struct {
	TrustedDomainId TrustedDomainID `json:"trusted_domain_id" yaml:"trusted_domain_id"`
	HouseId         HouseID         `json:"house_id" yaml:"house_id"`
	Domain          string          `json:"domain" yaml:"domain"`
	CreatedAt       Timestamp       `json:"created_at" yaml:"created_at"`
}

// Role represents a structured data type
type Role struct {
	RoleId      RoleID    `json:"role_id" yaml:"role_id"`
	HouseId     HouseID   `json:"house_id" yaml:"house_id"`
	Name        string    `json:"name" yaml:"name"`
	Description *string   `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedAt   Timestamp `json:"created_at" yaml:"created_at"`
	UpdatedAt   Timestamp `json:"updated_at" yaml:"updated_at"`
}

// MemberRole represents a structured data type
type MemberRole struct {
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
	RoleId    RoleID    `json:"role_id" yaml:"role_id"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// MemberAudit represents a structured data type
type MemberAudit struct {
	AuditId         MemberAuditID `json:"audit_id" yaml:"audit_id"`
	HouseId         HouseID       `json:"house_id" yaml:"house_id"`
	SubjectMemberId MemberID      `json:"subject_member_id" yaml:"subject_member_id"`
	ActorMemberId   *MemberID     `json:"actor_member_id,omitempty" yaml:"actor_member_id,omitempty"`
	Action          string        `json:"action" yaml:"action"`
	TargetType      *string       `json:"target_type,omitempty" yaml:"target_type,omitempty"`
	TargetId        *string       `json:"target_id,omitempty" yaml:"target_id,omitempty"`
	Detail          *string       `json:"detail,omitempty" yaml:"detail,omitempty"`
	CreatedAt       Timestamp     `json:"created_at" yaml:"created_at"`
}

// Skill represents a structured data type
type Skill struct {
	SkillId     SkillID   `json:"skill_id" yaml:"skill_id"`
	HouseId     HouseID   `json:"house_id" yaml:"house_id"`
	Name        string    `json:"name" yaml:"name"`
	Description *string   `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedAt   Timestamp `json:"created_at" yaml:"created_at"`
	UpdatedAt   Timestamp `json:"updated_at" yaml:"updated_at"`
}

// MemberSkill represents a structured data type
type MemberSkill struct {
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
	SkillId   SkillID   `json:"skill_id" yaml:"skill_id"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// GroupSkill represents a structured data type
type GroupSkill struct {
	GroupId   GroupID   `json:"group_id" yaml:"group_id"`
	SkillId   SkillID   `json:"skill_id" yaml:"skill_id"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// Group represents a structured data type
type Group struct {
	GroupId     GroupID   `json:"group_id" yaml:"group_id"`
	HouseId     HouseID   `json:"house_id" yaml:"house_id"`
	Name        string    `json:"name" yaml:"name"`
	Description *string   `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedAt   Timestamp `json:"created_at" yaml:"created_at"`
	UpdatedAt   Timestamp `json:"updated_at" yaml:"updated_at"`
}

// GroupMember represents a structured data type
type GroupMember struct {
	GroupId   GroupID   `json:"group_id" yaml:"group_id"`
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// Project represents a structured data type
type Project struct {
	ProjectId   ProjectID      `json:"project_id" yaml:"project_id"`
	HouseId     HouseID        `json:"house_id" yaml:"house_id"`
	Name        string         `json:"name" yaml:"name"`
	Description *string        `json:"description,omitempty" yaml:"description,omitempty"`
	Category    *string        `json:"category,omitempty" yaml:"category,omitempty"`
	Status      *ProjectStatus `json:"status,omitempty" yaml:"status,omitempty"`
	CreatedAt   Timestamp      `json:"created_at" yaml:"created_at"`
	UpdatedAt   Timestamp      `json:"updated_at" yaml:"updated_at"`
}

// ProjectTask represents a structured data type
type ProjectTask struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	TaskId    TaskID    `json:"task_id" yaml:"task_id"`
	Position  int64     `json:"position" yaml:"position"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// ProjectMember represents a structured data type
type ProjectMember struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// ProjectOwner represents a structured data type
type ProjectOwner struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
	CreatedAt Timestamp `json:"created_at" yaml:"created_at"`
}

// Milestone represents a structured data type
type Milestone struct {
	MilestoneId MilestoneID    `json:"milestone_id" yaml:"milestone_id"`
	ProjectId   ProjectID      `json:"project_id" yaml:"project_id"`
	Label       string         `json:"label" yaml:"label"`
	WhenLabel   string         `json:"when_label" yaml:"when_label"`
	State       MilestoneState `json:"state" yaml:"state"`
	Position    int64          `json:"position" yaml:"position"`
	CreatedAt   Timestamp      `json:"created_at" yaml:"created_at"`
	UpdatedAt   Timestamp      `json:"updated_at" yaml:"updated_at"`
}

// Event represents a structured data type
type Event struct {
	EventId       EventID    `json:"event_id" yaml:"event_id"`
	HouseId       HouseID    `json:"house_id" yaml:"house_id"`
	OwnerMemberId MemberID   `json:"owner_member_id" yaml:"owner_member_id"`
	Title         string     `json:"title" yaml:"title"`
	Description   *string    `json:"description,omitempty" yaml:"description,omitempty"`
	Location      *string    `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAt      *Timestamp `json:"starts_at,omitempty" yaml:"starts_at,omitempty"`
	EndsAt        *Timestamp `json:"ends_at,omitempty" yaml:"ends_at,omitempty"`
	AllDay        *bool      `json:"all_day,omitempty" yaml:"all_day,omitempty"`
	CreatedAt     Timestamp  `json:"created_at" yaml:"created_at"`
	UpdatedAt     Timestamp  `json:"updated_at" yaml:"updated_at"`
}

// Task represents a structured data type
type Task struct {
	TaskId               TaskID          `json:"task_id" yaml:"task_id"`
	HouseId              HouseID         `json:"house_id" yaml:"house_id"`
	OwnerMemberId        MemberID        `json:"owner_member_id" yaml:"owner_member_id"`
	Assignees            []MemberID      `json:"assignees,omitempty" yaml:"assignees,omitempty"`
	AssignedToSkillId    *SkillID        `json:"assigned_to_skill_id,omitempty" yaml:"assigned_to_skill_id,omitempty"`
	ParentTaskId         *TaskID         `json:"parent_task_id,omitempty" yaml:"parent_task_id,omitempty"`
	Title                string          `json:"title" yaml:"title"`
	Description          *string         `json:"description,omitempty" yaml:"description,omitempty"`
	Status               *TaskStatus     `json:"status,omitempty" yaml:"status,omitempty"`
	DueAt                *Timestamp      `json:"due_at,omitempty" yaml:"due_at,omitempty"`
	Tag                  *string         `json:"tag,omitempty" yaml:"tag,omitempty"`
	EstimateMinutes      *uint64         `json:"estimate_minutes,omitempty" yaml:"estimate_minutes,omitempty"`
	RecurrenceFreq       *RecurrenceFreq `json:"recurrence_freq,omitempty" yaml:"recurrence_freq,omitempty"`
	RecurrenceInterval   *int64          `json:"recurrence_interval,omitempty" yaml:"recurrence_interval,omitempty"`
	RecurrenceByWeekday  []int64         `json:"recurrence_by_weekday,omitempty" yaml:"recurrence_by_weekday,omitempty"`
	NextRecurrenceAt     *Timestamp      `json:"next_recurrence_at,omitempty" yaml:"next_recurrence_at,omitempty"`
	RecurrenceRootTaskId *TaskID         `json:"recurrence_root_task_id,omitempty" yaml:"recurrence_root_task_id,omitempty"`
	DeletedAt            *Timestamp      `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	CreatedAt            Timestamp       `json:"created_at" yaml:"created_at"`
	UpdatedAt            Timestamp       `json:"updated_at" yaml:"updated_at"`
}

// Comment represents a structured data type
type Comment struct {
	CommentId  CommentID  `json:"comment_id" yaml:"comment_id"`
	HouseId    HouseID    `json:"house_id" yaml:"house_id"`
	MemberId   MemberID   `json:"member_id" yaml:"member_id"`
	TargetType TargetType `json:"target_type" yaml:"target_type"`
	TargetId   string     `json:"target_id" yaml:"target_id"`
	Body       string     `json:"body" yaml:"body"`
	CreatedAt  Timestamp  `json:"created_at" yaml:"created_at"`
	UpdatedAt  Timestamp  `json:"updated_at" yaml:"updated_at"`
}

// Share represents a structured data type
type Share struct {
	ShareId        ShareID      `json:"share_id" yaml:"share_id"`
	HouseId        HouseID      `json:"house_id" yaml:"house_id"`
	SharedBy       MemberID     `json:"shared_by" yaml:"shared_by"`
	LinkkeysDomain string       `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	LinkkeysUserId string       `json:"linkkeys_user_id" yaml:"linkkeys_user_id"`
	ResourceType   ResourceType `json:"resource_type" yaml:"resource_type"`
	ResourceId     string       `json:"resource_id" yaml:"resource_id"`
	AccessLevel    *AccessLevel `json:"access_level,omitempty" yaml:"access_level,omitempty"`
	CreatedAt      Timestamp    `json:"created_at" yaml:"created_at"`
	ExpiresAt      *Timestamp   `json:"expires_at,omitempty" yaml:"expires_at,omitempty"`
}

// HouseSummary represents a structured data type
type HouseSummary struct {
	HouseId  HouseID  `json:"house_id" yaml:"house_id"`
	Name     string   `json:"name" yaml:"name"`
	MemberId MemberID `json:"member_id" yaml:"member_id"`
	Roles    []string `json:"roles" yaml:"roles"`
}

// HouseRoles represents a structured data type
type HouseRoles struct {
	House  HouseID  `json:"house" yaml:"house"`
	Member MemberID `json:"member" yaml:"member"`
	Roles  []string `json:"roles" yaml:"roles"`
}

// Identity represents a structured data type
type Identity struct {
	Domain      string       `json:"domain" yaml:"domain"`
	UserId      string       `json:"user_id" yaml:"user_id"`
	DisplayName *string      `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	Houses      []HouseRoles `json:"houses" yaml:"houses"`
	Iat         int64        `json:"iat" yaml:"iat"`
	Exp         int64        `json:"exp" yaml:"exp"`
}

// LoginRequest represents a structured data type
type LoginRequest struct {
	SignedAssertion string `json:"signed_assertion" yaml:"signed_assertion"`
}

// CompleteRequest represents a structured data type
type CompleteRequest struct {
	EncryptedToken string `json:"encrypted_token" yaml:"encrypted_token"`
}

// LoginResponse represents a structured data type
type LoginResponse struct {
	Token       string    `json:"token" yaml:"token"`
	Domain      string    `json:"domain" yaml:"domain"`
	UserId      string    `json:"user_id" yaml:"user_id"`
	DisplayName *string   `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	ExpiresAt   Timestamp `json:"expires_at" yaml:"expires_at"`
}

// DevUserEntry represents a structured data type
type DevUserEntry struct {
	MemberId       MemberID `json:"member_id" yaml:"member_id"`
	HouseId        HouseID  `json:"house_id" yaml:"house_id"`
	HouseName      string   `json:"house_name" yaml:"house_name"`
	DisplayName    *string  `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	LinkkeysDomain *string  `json:"linkkeys_domain,omitempty" yaml:"linkkeys_domain,omitempty"`
	LinkkeysUserId *string  `json:"linkkeys_user_id,omitempty" yaml:"linkkeys_user_id,omitempty"`
	Roles          []string `json:"roles" yaml:"roles"`
}

// DevUsersResponse represents a structured data type
type DevUsersResponse struct {
	Users []DevUserEntry `json:"users" yaml:"users"`
}

// DevLoginRequest represents a structured data type
type DevLoginRequest struct {
	MemberId MemberID `json:"member_id" yaml:"member_id"`
}

// MeResponse represents a structured data type
type MeResponse struct {
	Domain      string         `json:"domain" yaml:"domain"`
	UserId      string         `json:"user_id" yaml:"user_id"`
	DisplayName *string        `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	ExpiresAt   Timestamp      `json:"expires_at" yaml:"expires_at"`
	Houses      []HouseSummary `json:"houses" yaml:"houses"`
}

// EmptyRequest represents a structured data type
type EmptyRequest struct {
}

// EmptyResponse represents a structured data type
type EmptyResponse struct {
}

// BoolResponse represents a structured data type
type BoolResponse struct {
	Value bool `json:"value" yaml:"value"`
}

// HouseListRequest represents a structured data type
type HouseListRequest struct {
	Limit  *uint64 `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset *uint64 `json:"offset,omitempty" yaml:"offset,omitempty"`
}

// HouseScopedListRequest represents a structured data type
type HouseScopedListRequest struct {
	HouseId HouseID `json:"house_id" yaml:"house_id"`
	Limit   *uint64 `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset  *uint64 `json:"offset,omitempty" yaml:"offset,omitempty"`
}

// MemberScopedListRequest represents a structured data type
type MemberScopedListRequest struct {
	HouseId  HouseID  `json:"house_id" yaml:"house_id"`
	MemberId MemberID `json:"member_id" yaml:"member_id"`
	Limit    *uint64  `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset   *uint64  `json:"offset,omitempty" yaml:"offset,omitempty"`
}

// ProjectScopedListRequest represents a structured data type
type ProjectScopedListRequest struct {
	HouseId   HouseID   `json:"house_id" yaml:"house_id"`
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	Limit     *uint64   `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset    *uint64   `json:"offset,omitempty" yaml:"offset,omitempty"`
}

// CommentListRequest represents a structured data type
type CommentListRequest struct {
	TargetType TargetType `json:"target_type" yaml:"target_type"`
	TargetId   string     `json:"target_id" yaml:"target_id"`
	Limit      *uint64    `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset     *uint64    `json:"offset,omitempty" yaml:"offset,omitempty"`
}

// ShareAccessRequest represents a structured data type
type ShareAccessRequest struct {
	LinkkeysDomain string       `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	LinkkeysUserId string       `json:"linkkeys_user_id" yaml:"linkkeys_user_id"`
	ResourceType   ResourceType `json:"resource_type" yaml:"resource_type"`
	ResourceId     string       `json:"resource_id" yaml:"resource_id"`
}

// ResourceRef represents a structured data type
type ResourceRef struct {
	ResourceType ResourceType `json:"resource_type" yaml:"resource_type"`
	ResourceId   string       `json:"resource_id" yaml:"resource_id"`
}

// MemberRoleRef represents a structured data type
type MemberRoleRef struct {
	MemberId MemberID `json:"member_id" yaml:"member_id"`
	RoleId   RoleID   `json:"role_id" yaml:"role_id"`
}

// MemberSkillRef represents a structured data type
type MemberSkillRef struct {
	MemberId MemberID `json:"member_id" yaml:"member_id"`
	SkillId  SkillID  `json:"skill_id" yaml:"skill_id"`
}

// GroupSkillRef represents a structured data type
type GroupSkillRef struct {
	GroupId GroupID `json:"group_id" yaml:"group_id"`
	SkillId SkillID `json:"skill_id" yaml:"skill_id"`
}

// GroupMemberRef represents a structured data type
type GroupMemberRef struct {
	GroupId  GroupID  `json:"group_id" yaml:"group_id"`
	MemberId MemberID `json:"member_id" yaml:"member_id"`
}

// ProjectTaskRef represents a structured data type
type ProjectTaskRef struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	TaskId    TaskID    `json:"task_id" yaml:"task_id"`
}

// ProjectTaskOrderRequest represents a structured data type
type ProjectTaskOrderRequest struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	TaskId    TaskID    `json:"task_id" yaml:"task_id"`
	Position  int64     `json:"position" yaml:"position"`
}

// ProjectMemberRef represents a structured data type
type ProjectMemberRef struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
}

// ProjectOwnerRef represents a structured data type
type ProjectOwnerRef struct {
	ProjectId ProjectID `json:"project_id" yaml:"project_id"`
	MemberId  MemberID  `json:"member_id" yaml:"member_id"`
}

// ServiceError represents a structured data type
type ServiceError struct {
	Code    uint64 `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}
